-- retro-metropolis - erzeugt von retro-coding-themes, nicht von Hand aendern.
-- Quelle: src/retro_coding_themes/data/metropolis.json, Ableitung in derive.py.

vim.cmd("highlight clear")
if vim.fn.exists("syntax_on") == 1 then
  vim.cmd("syntax reset")
end

vim.o.background = "dark"
vim.g.colors_name = "retro-metropolis"

local hl = vim.api.nvim_set_hl

hl(0, "Normal", { fg = "#F0F2F8", bg = "#0A2A5E" })
hl(0, "NormalNC", { link = "Normal" })
hl(0, "NormalFloat", { fg = "#F0F2F8", bg = "#213E6D" })
hl(0, "FloatBorder", { fg = "#768AAB", bg = "#213E6D" })
hl(0, "FloatTitle", { fg = "#FFD53B", bg = "#213E6D", bold = true })
hl(0, "ColorColumn", { bg = "#1A3869" })
hl(0, "Conceal", { fg = "#7A8CA9" })
hl(0, "Cursor", { fg = "#0A2A5E", bg = "#F0F2F8" })
hl(0, "lCursor", { link = "Cursor" })
hl(0, "TermCursor", { link = "Cursor" })
hl(0, "CursorLine", { bg = "#1A3869" })
hl(0, "CursorColumn", { link = "CursorLine" })
hl(0, "CursorLineNr", { fg = "#FFD53B", bold = true })
hl(0, "LineNr", { fg = "#7A8CA9" })
hl(0, "SignColumn", { bg = "#0A2A5E" })
hl(0, "FoldColumn", { fg = "#7A8CA9" })
hl(0, "Folded", { fg = "#A0ACC2", bg = "#213E6D" })
hl(0, "EndOfBuffer", { fg = "#0A2A5E" })
hl(0, "NonText", { fg = "#7A8CA9" })
hl(0, "Whitespace", { fg = "#445C84" })
hl(0, "SpecialKey", { fg = "#7A8CA9" })
hl(0, "Visual", { bg = "#606652" })
hl(0, "VisualNOS", { link = "Visual" })
hl(0, "MatchParen", { fg = "#FFD53B", bg = "#334E7A", bold = true })
hl(0, "Pmenu", { fg = "#F0F2F8", bg = "#213E6D" })
hl(0, "PmenuSel", { fg = "#F0F2F8", bg = "#334E7A", bold = true })
hl(0, "PmenuSbar", { bg = "#213E6D" })
hl(0, "PmenuThumb", { bg = "#768AAB" })
hl(0, "PmenuKind", { fg = "#82ABEF" })
hl(0, "PmenuKindSel", { fg = "#82ABEF", bg = "#334E7A" })
hl(0, "PmenuExtra", { fg = "#7A8CA9" })
hl(0, "PmenuExtraSel", { fg = "#7A8CA9", bg = "#334E7A" })
hl(0, "WildMenu", { link = "PmenuSel" })
hl(0, "StatusLine", { fg = "#FFFFFF", bg = "#E02030", bold = true })
hl(0, "StatusLineNC", { fg = "#A0ACC2", bg = "#213E6D" })
hl(0, "WinBar", { fg = "#A0ACC2", bg = "#0A2A5E" })
hl(0, "WinBarNC", { fg = "#7A8CA9", bg = "#0A2A5E" })
hl(0, "WinSeparator", { fg = "#768AAB" })
hl(0, "TabLine", { fg = "#A0ACC2", bg = "#213E6D" })
hl(0, "TabLineFill", { bg = "#0A2A5E" })
hl(0, "TabLineSel", { fg = "#FFFFFF", bg = "#E02030", bold = true })
hl(0, "Search", { fg = "#F0F2F8", bg = "#595052" })
hl(0, "IncSearch", { fg = "#0A2A5E", bg = "#ED963D", bold = true })
hl(0, "CurSearch", { link = "IncSearch" })
hl(0, "Substitute", { fg = "#0A2A5E", bg = "#F98B93" })
hl(0, "QuickFixLine", { bg = "#334E7A", bold = true })
hl(0, "Directory", { fg = "#F09098" })
hl(0, "Title", { fg = "#FFD53B", bold = true })
hl(0, "Question", { fg = "#47C059" })
hl(0, "MoreMsg", { fg = "#47C059" })
hl(0, "ModeMsg", { fg = "#F0F2F8", bold = true })
hl(0, "MsgArea", { fg = "#F0F2F8", bg = "#0A2A5E" })
hl(0, "MsgSeparator", { fg = "#768AAB" })
hl(0, "WarningMsg", { fg = "#FFD53B" })
hl(0, "ErrorMsg", { fg = "#F98B93" })
hl(0, "SpellBad", { sp = "#F98B93", undercurl = true })
hl(0, "SpellCap", { sp = "#FFD53B", undercurl = true })
hl(0, "SpellLocal", { sp = "#F09098", undercurl = true })
hl(0, "SpellRare", { sp = "#8AABE2", undercurl = true })
hl(0, "Comment", { fg = "#89AAE1", italic = true })
hl(0, "Constant", { fg = "#ED963D" })
hl(0, "String", { fg = "#47C059" })
hl(0, "Character", { fg = "#47C059" })
hl(0, "Number", { fg = "#ED963D" })
hl(0, "Boolean", { fg = "#ED963D" })
hl(0, "Float", { fg = "#ED963D" })
hl(0, "Identifier", { fg = "#F0F2F8" })
hl(0, "Function", { fg = "#F09098" })
hl(0, "Statement", { fg = "#FFD53B" })
hl(0, "Conditional", { fg = "#FFD53B" })
hl(0, "Repeat", { fg = "#FFD53B" })
hl(0, "Label", { fg = "#FFD53B" })
hl(0, "Operator", { fg = "#C2CAD9" })
hl(0, "Keyword", { fg = "#FFD53B" })
hl(0, "Exception", { fg = "#FFD53B" })
hl(0, "PreProc", { fg = "#ECA072" })
hl(0, "Include", { fg = "#FFD53B" })
hl(0, "Define", { fg = "#ECA072" })
hl(0, "Macro", { fg = "#ECA072" })
hl(0, "PreCondit", { fg = "#ECA072" })
hl(0, "Type", { fg = "#82ABEF" })
hl(0, "StorageClass", { fg = "#FFD53B" })
hl(0, "Structure", { fg = "#82ABEF" })
hl(0, "Typedef", { fg = "#82ABEF" })
hl(0, "Special", { fg = "#ECA072" })
hl(0, "SpecialChar", { fg = "#ECA072" })
hl(0, "Tag", { fg = "#FFD53B" })
hl(0, "Delimiter", { fg = "#C2CAD9" })
hl(0, "SpecialComment", { fg = "#89AAE1", bold = true })
hl(0, "Debug", { fg = "#F98B93" })
hl(0, "Underlined", { fg = "#F09098", underline = true })
hl(0, "Ignore", { fg = "#7A8CA9" })
hl(0, "Error", { fg = "#F98B93", bold = true })
hl(0, "Todo", { fg = "#0A2A5E", bg = "#ED963D", bold = true })
hl(0, "Added", { fg = "#47C059" })
hl(0, "Changed", { fg = "#FFD53B" })
hl(0, "Removed", { fg = "#F98B93" })
hl(0, "DiffAdd", { bg = "#15455D" })
hl(0, "DiffChange", { bg = "#273F5A" })
hl(0, "DiffDelete", { bg = "#353B68" })
hl(0, "DiffText", { bg = "#535D54", bold = true })
hl(0, "DiagnosticError", { fg = "#F98B93" })
hl(0, "DiagnosticWarn", { fg = "#FFD53B" })
hl(0, "DiagnosticInfo", { fg = "#F09098" })
hl(0, "DiagnosticHint", { fg = "#8AABE2" })
hl(0, "DiagnosticOk", { fg = "#47C059" })
hl(0, "DiagnosticUnderlineError", { sp = "#F98B93", undercurl = true })
hl(0, "DiagnosticUnderlineWarn", { sp = "#FFD53B", undercurl = true })
hl(0, "DiagnosticUnderlineInfo", { sp = "#F09098", undercurl = true })
hl(0, "DiagnosticUnderlineHint", { sp = "#8AABE2", undercurl = true })
hl(0, "DiagnosticUnderlineOk", { sp = "#47C059", undercurl = true })
hl(0, "DiagnosticVirtualTextError", { fg = "#F98B93", bg = "#273664" })
hl(0, "DiagnosticVirtualTextWarn", { fg = "#FFD53B", bg = "#273F5A" })
hl(0, "DiagnosticVirtualTextInfo", { fg = "#F09098", bg = "#263665" })
hl(0, "DiagnosticVirtualTextHint", { fg = "#8AABE2", bg = "#19396E" })
hl(0, "@variable", { fg = "#F0F2F8" })
hl(0, "@variable.builtin", { fg = "#ECA072", italic = true })
hl(0, "@variable.parameter", { fg = "#F0F2F8" })
hl(0, "@variable.member", { fg = "#F0F2F8" })
hl(0, "@constant", { fg = "#ED963D" })
hl(0, "@constant.builtin", { fg = "#ECA072" })
hl(0, "@constant.macro", { fg = "#ECA072" })
hl(0, "@module", { fg = "#82ABEF" })
hl(0, "@label", { fg = "#FFD53B" })
hl(0, "@string", { fg = "#47C059" })
hl(0, "@string.documentation", { fg = "#89AAE1" })
hl(0, "@string.escape", { fg = "#ECA072" })
hl(0, "@string.regexp", { fg = "#ECA072" })
hl(0, "@string.special", { fg = "#ECA072" })
hl(0, "@character", { fg = "#47C059" })
hl(0, "@character.special", { fg = "#ECA072" })
hl(0, "@boolean", { fg = "#ED963D" })
hl(0, "@number", { fg = "#ED963D" })
hl(0, "@number.float", { fg = "#ED963D" })
hl(0, "@type", { fg = "#82ABEF" })
hl(0, "@type.builtin", { fg = "#82ABEF", italic = true })
hl(0, "@type.definition", { fg = "#82ABEF" })
hl(0, "@attribute", { fg = "#ECA072" })
hl(0, "@attribute.builtin", { fg = "#ECA072" })
hl(0, "@property", { fg = "#F0F2F8" })
hl(0, "@function", { fg = "#F09098" })
hl(0, "@function.builtin", { fg = "#ECA072" })
hl(0, "@function.macro", { fg = "#ECA072" })
hl(0, "@function.method", { fg = "#F09098" })
hl(0, "@constructor", { fg = "#82ABEF" })
hl(0, "@operator", { fg = "#C2CAD9" })
hl(0, "@keyword", { fg = "#FFD53B" })
hl(0, "@keyword.function", { fg = "#FFD53B" })
hl(0, "@keyword.operator", { fg = "#FFD53B" })
hl(0, "@keyword.import", { fg = "#FFD53B" })
hl(0, "@keyword.return", { fg = "#FFD53B" })
hl(0, "@keyword.exception", { fg = "#FFD53B" })
hl(0, "@punctuation.delimiter", { fg = "#C2CAD9" })
hl(0, "@punctuation.bracket", { fg = "#C2CAD9" })
hl(0, "@punctuation.special", { fg = "#ECA072" })
hl(0, "@comment", { fg = "#89AAE1", italic = true })
hl(0, "@comment.documentation", { fg = "#89AAE1", italic = true })
hl(0, "@comment.error", { fg = "#0A2A5E", bg = "#F98B93", bold = true })
hl(0, "@comment.warning", { fg = "#0A2A5E", bg = "#FFD53B", bold = true })
hl(0, "@comment.todo", { link = "Todo" })
hl(0, "@comment.note", { fg = "#0A2A5E", bg = "#F09098", bold = true })
hl(0, "@tag", { fg = "#FFD53B" })
hl(0, "@tag.builtin", { fg = "#FFD53B" })
hl(0, "@tag.attribute", { fg = "#F09098", italic = true })
hl(0, "@tag.delimiter", { fg = "#C2CAD9" })
hl(0, "@markup.strong", { fg = "#F0F2F8", bold = true })
hl(0, "@markup.italic", { fg = "#F0F2F8", italic = true })
hl(0, "@markup.strikethrough", { fg = "#A0ACC2", strikethrough = true })
hl(0, "@markup.underline", { fg = "#F0F2F8", underline = true })
hl(0, "@markup.quote", { fg = "#A0ACC2", italic = true })
hl(0, "@markup.math", { fg = "#ED963D" })
hl(0, "@markup.link", { fg = "#F09098" })
hl(0, "@markup.link.label", { fg = "#FFD53B" })
hl(0, "@markup.link.url", { fg = "#F09098", underline = true })
hl(0, "@markup.raw", { fg = "#47C059" })
hl(0, "@markup.list", { fg = "#FFD53B" })
hl(0, "@markup.list.checked", { fg = "#47C059" })
hl(0, "@markup.list.unchecked", { fg = "#A0ACC2" })
hl(0, "@diff.plus", { fg = "#47C059" })
hl(0, "@diff.minus", { fg = "#F98B93" })
hl(0, "@diff.delta", { fg = "#FFD53B" })
hl(0, "@lsp.type.namespace", { link = "@module" })
hl(0, "@lsp.type.class", { link = "@type" })
hl(0, "@lsp.type.enum", { link = "@type" })
hl(0, "@lsp.type.interface", { link = "@type" })
hl(0, "@lsp.type.struct", { link = "@type" })
hl(0, "@lsp.type.parameter", { link = "@variable.parameter" })
hl(0, "@lsp.type.property", { link = "@property" })
hl(0, "@lsp.type.enumMember", { link = "@constant" })
hl(0, "@lsp.type.method", { link = "@function.method" })
hl(0, "MiniIconsAzure", { fg = "#F09098" })
hl(0, "MiniIconsBlue", { fg = "#F09098" })
hl(0, "MiniIconsCyan", { fg = "#82ABEF" })
hl(0, "MiniIconsGreen", { fg = "#47C059" })
hl(0, "MiniIconsGrey", { fg = "#A0ACC2" })
hl(0, "MiniIconsOrange", { fg = "#ED963D" })
hl(0, "MiniIconsPurple", { fg = "#ECA072" })
hl(0, "MiniIconsRed", { fg = "#F98B93" })
hl(0, "MiniIconsYellow", { fg = "#FFD53B" })
hl(0, "MiniFilesTitleFocused", { fg = "#FFD53B", bg = "#213E6D", bold = true })
hl(0, "MiniFilesDirectory", { fg = "#F09098" })
hl(0, "MiniFilesFile", { fg = "#F0F2F8" })
hl(0, "MiniFilesCursorLine", { bg = "#334E7A" })
hl(0, "MiniPickMatchCurrent", { bg = "#334E7A", bold = true })
hl(0, "MiniPickMatchRanges", { fg = "#FFD53B", bold = true })
hl(0, "MiniPickPrompt", { fg = "#FFD53B", bold = true })
hl(0, "MiniPickBorderText", { fg = "#FFD53B" })
hl(0, "MiniClueDescGroup", { fg = "#82ABEF" })
hl(0, "MiniClueDescSingle", { fg = "#F0F2F8" })
hl(0, "MiniClueNextKey", { fg = "#FFD53B", bold = true })
hl(0, "MiniClueTitle", { fg = "#FFD53B", bg = "#213E6D", bold = true })
hl(0, "RenderMarkdownCode", { bg = "#213E6D" })
hl(0, "RenderMarkdownCodeInline", { fg = "#47C059", bg = "#213E6D" })
hl(0, "RenderMarkdownBullet", { fg = "#FFD53B" })
hl(0, "RenderMarkdownQuote", { fg = "#A0ACC2" })
hl(0, "RenderMarkdownDash", { fg = "#768AAB" })
hl(0, "RenderMarkdownTableHead", { fg = "#82ABEF", bold = true })
hl(0, "RenderMarkdownTableRow", { fg = "#A0ACC2" })
hl(0, "RenderMarkdownLink", { fg = "#F09098" })
hl(0, "RenderMarkdownChecked", { fg = "#47C059" })
hl(0, "RenderMarkdownUnchecked", { fg = "#A0ACC2" })
hl(0, "@markup.heading.1", { fg = "#FFD53B", bold = true })
hl(0, "RenderMarkdownH1", { fg = "#FFD53B", bold = true })
hl(0, "RenderMarkdownH1Bg", { fg = "#FFD53B", bg = "#2F4459", bold = true })
hl(0, "@markup.heading.2", { fg = "#F09098", bold = true })
hl(0, "RenderMarkdownH2", { fg = "#F09098", bold = true })
hl(0, "RenderMarkdownH2Bg", { fg = "#F09098", bg = "#2C3967", bold = true })
hl(0, "@markup.heading.3", { fg = "#47C059", bold = true })
hl(0, "RenderMarkdownH3", { fg = "#47C059", bold = true })
hl(0, "RenderMarkdownH3Bg", { fg = "#47C059", bg = "#13405D", bold = true })
hl(0, "@markup.heading.4", { fg = "#ED963D", bold = true })
hl(0, "RenderMarkdownH4", { fg = "#ED963D", bold = true })
hl(0, "RenderMarkdownH4Bg", { fg = "#ED963D", bg = "#2C3A59", bold = true })
hl(0, "@markup.heading.5", { fg = "#82ABEF", bold = true })
hl(0, "RenderMarkdownH5", { fg = "#82ABEF", bold = true })
hl(0, "RenderMarkdownH5Bg", { fg = "#82ABEF", bg = "#1C3D74", bold = true })
hl(0, "@markup.heading.6", { fg = "#ECA072", bold = true })
hl(0, "RenderMarkdownH6", { fg = "#ECA072", bold = true })
hl(0, "RenderMarkdownH6Bg", { fg = "#ECA072", bg = "#2C3C61", bold = true })

vim.g.terminal_color_0 = "#445C84"
vim.g.terminal_color_1 = "#F98B93"
vim.g.terminal_color_2 = "#47C059"
vim.g.terminal_color_3 = "#FFD53B"
vim.g.terminal_color_4 = "#F09098"
vim.g.terminal_color_5 = "#ECA072"
vim.g.terminal_color_6 = "#FFD53B"
vim.g.terminal_color_7 = "#A0ACC2"
vim.g.terminal_color_8 = "#7284A3"
vim.g.terminal_color_9 = "#FAA2A9"
vim.g.terminal_color_10 = "#6CCD7A"
vim.g.terminal_color_11 = "#FFDD62"
vim.g.terminal_color_12 = "#F3A6AD"
vim.g.terminal_color_13 = "#F0B38E"
vim.g.terminal_color_14 = "#FFDD62"
vim.g.terminal_color_15 = "#F0F2F8"
