-- retro-luna - erzeugt von retro-coding-themes, nicht von Hand aendern.
-- Quelle: src/retro_coding_themes/data/luna.json, Ableitung in derive.py.

vim.cmd("highlight clear")
if vim.fn.exists("syntax_on") == 1 then
  vim.cmd("syntax reset")
end

vim.o.background = "dark"
vim.g.colors_name = "retro-luna"

local hl = vim.api.nvim_set_hl

hl(0, "Normal", { fg = "#FFFFFF", bg = "#003399" })
hl(0, "NormalNC", { link = "Normal" })
hl(0, "NormalFloat", { fg = "#FFFFFF", bg = "#1A47A3" })
hl(0, "FloatBorder", { fg = "#819ACD", bg = "#1A47A3" })
hl(0, "FloatTitle", { fg = "#9CC0FF", bg = "#1A47A3", bold = true })
hl(0, "ColorColumn", { bg = "#1241A0" })
hl(0, "Conceal", { fg = "#829BCD" })
hl(0, "Cursor", { fg = "#003399", bg = "#FFFFFF" })
hl(0, "lCursor", { link = "Cursor" })
hl(0, "TermCursor", { link = "Cursor" })
hl(0, "CursorLine", { bg = "#1241A0" })
hl(0, "CursorColumn", { link = "CursorLine" })
hl(0, "CursorLineNr", { fg = "#9CC0FF", bold = true })
hl(0, "LineNr", { fg = "#829BCD" })
hl(0, "SignColumn", { bg = "#003399" })
hl(0, "FoldColumn", { fg = "#829BCD" })
hl(0, "Folded", { fg = "#ADBEDE", bg = "#1A47A3" })
hl(0, "EndOfBuffer", { fg = "#003399" })
hl(0, "NonText", { fg = "#829BCD" })
hl(0, "Whitespace", { fg = "#4066B2" })
hl(0, "SpecialKey", { fg = "#829BCD" })
hl(0, "Visual", { bg = "#003FB3" })
hl(0, "VisualNOS", { link = "Visual" })
hl(0, "MatchParen", { fg = "#9CC0FF", bg = "#2E58AB", bold = true })
hl(0, "Pmenu", { fg = "#FFFFFF", bg = "#1A47A3" })
hl(0, "PmenuSel", { fg = "#FFFFFF", bg = "#2E58AB", bold = true })
hl(0, "PmenuSbar", { bg = "#1A47A3" })
hl(0, "PmenuThumb", { bg = "#819ACD" })
hl(0, "PmenuKind", { fg = "#1CD3E1" })
hl(0, "PmenuKindSel", { fg = "#1CD3E1", bg = "#2E58AB" })
hl(0, "PmenuExtra", { fg = "#829BCD" })
hl(0, "PmenuExtraSel", { fg = "#829BCD", bg = "#2E58AB" })
hl(0, "WildMenu", { link = "PmenuSel" })
hl(0, "StatusLine", { fg = "#FFFFFF", bg = "#0054E3", bold = true })
hl(0, "StatusLineNC", { fg = "#ADBEDE", bg = "#1A47A3" })
hl(0, "WinBar", { fg = "#ADBEDE", bg = "#003399" })
hl(0, "WinBarNC", { fg = "#829BCD", bg = "#003399" })
hl(0, "WinSeparator", { fg = "#819ACD" })
hl(0, "TabLine", { fg = "#ADBEDE", bg = "#1A47A3" })
hl(0, "TabLineFill", { bg = "#003399" })
hl(0, "TabLineSel", { fg = "#FFFFFF", bg = "#0054E3", bold = true })
hl(0, "Search", { fg = "#FFFFFF", bg = "#596963" })
hl(0, "IncSearch", { fg = "#003399", bg = "#FFCC00", bold = true })
hl(0, "CurSearch", { link = "IncSearch" })
hl(0, "Substitute", { fg = "#003399", bg = "#F9A9AF" })
hl(0, "QuickFixLine", { bg = "#2E58AB", bold = true })
hl(0, "Directory", { fg = "#45D945" })
hl(0, "Title", { fg = "#9CC0FF", bold = true })
hl(0, "Question", { fg = "#45D945" })
hl(0, "MoreMsg", { fg = "#45D945" })
hl(0, "ModeMsg", { fg = "#FFFFFF", bold = true })
hl(0, "MsgArea", { fg = "#FFFFFF", bg = "#003399" })
hl(0, "MsgSeparator", { fg = "#819ACD" })
hl(0, "WarningMsg", { fg = "#FFCC00" })
hl(0, "ErrorMsg", { fg = "#F9A9AF" })
hl(0, "SpellBad", { sp = "#F9A9AF", undercurl = true })
hl(0, "SpellCap", { sp = "#FFCC00", undercurl = true })
hl(0, "SpellLocal", { sp = "#9CC0FF", undercurl = true })
hl(0, "SpellRare", { sp = "#88CD88", undercurl = true })
hl(0, "Comment", { fg = "#90D090", italic = true })
hl(0, "Constant", { fg = "#FFCC00" })
hl(0, "String", { fg = "#22DAA4" })
hl(0, "Character", { fg = "#22DAA4" })
hl(0, "Number", { fg = "#FFCC00" })
hl(0, "Boolean", { fg = "#FFCC00" })
hl(0, "Float", { fg = "#FFCC00" })
hl(0, "Identifier", { fg = "#FFFFFF" })
hl(0, "Function", { fg = "#45D945" })
hl(0, "Statement", { fg = "#9CC0FF" })
hl(0, "Conditional", { fg = "#9CC0FF" })
hl(0, "Repeat", { fg = "#9CC0FF" })
hl(0, "Label", { fg = "#9CC0FF" })
hl(0, "Operator", { fg = "#CCD6EB" })
hl(0, "Keyword", { fg = "#9CC0FF" })
hl(0, "Exception", { fg = "#9CC0FF" })
hl(0, "PreProc", { fg = "#F8AC78" })
hl(0, "Include", { fg = "#9CC0FF" })
hl(0, "Define", { fg = "#F8AC78" })
hl(0, "Macro", { fg = "#F8AC78" })
hl(0, "PreCondit", { fg = "#F8AC78" })
hl(0, "Type", { fg = "#1CD3E1" })
hl(0, "StorageClass", { fg = "#9CC0FF" })
hl(0, "Structure", { fg = "#1CD3E1" })
hl(0, "Typedef", { fg = "#1CD3E1" })
hl(0, "Special", { fg = "#F8AC78" })
hl(0, "SpecialChar", { fg = "#F8AC78" })
hl(0, "Tag", { fg = "#9CC0FF" })
hl(0, "Delimiter", { fg = "#CCD6EB" })
hl(0, "SpecialComment", { fg = "#90D090", bold = true })
hl(0, "Debug", { fg = "#F9A9AF" })
hl(0, "Underlined", { fg = "#45D945", underline = true })
hl(0, "Ignore", { fg = "#829BCD" })
hl(0, "Error", { fg = "#F9A9AF", bold = true })
hl(0, "Todo", { fg = "#003399", bg = "#FFCC00", bold = true })
hl(0, "Added", { fg = "#45D945" })
hl(0, "Changed", { fg = "#FFCC00" })
hl(0, "Removed", { fg = "#F9A9AF" })
hl(0, "DiffAdd", { bg = "#0C518A" })
hl(0, "DiffChange", { bg = "#1F4587" })
hl(0, "DiffDelete", { bg = "#2D489D" })
hl(0, "DiffText", { bg = "#4C616B", bold = true })
hl(0, "DiagnosticError", { fg = "#F9A9AF" })
hl(0, "DiagnosticWarn", { fg = "#FFCC00" })
hl(0, "DiagnosticInfo", { fg = "#9CC0FF" })
hl(0, "DiagnosticHint", { fg = "#88CD88" })
hl(0, "DiagnosticOk", { fg = "#45D945" })
hl(0, "DiagnosticUnderlineError", { sp = "#F9A9AF", undercurl = true })
hl(0, "DiagnosticUnderlineWarn", { sp = "#FFCC00", undercurl = true })
hl(0, "DiagnosticUnderlineInfo", { sp = "#9CC0FF", undercurl = true })
hl(0, "DiagnosticUnderlineHint", { sp = "#88CD88", undercurl = true })
hl(0, "DiagnosticUnderlineOk", { sp = "#45D945", undercurl = true })
hl(0, "DiagnosticVirtualTextError", { fg = "#F9A9AF", bg = "#1E419C" })
hl(0, "DiagnosticVirtualTextWarn", { fg = "#FFCC00", bg = "#1F4587" })
hl(0, "DiagnosticVirtualTextInfo", { fg = "#9CC0FF", bg = "#1344A5" })
hl(0, "DiagnosticVirtualTextHint", { fg = "#88CD88", bg = "#104597" })
hl(0, "@variable", { fg = "#FFFFFF" })
hl(0, "@variable.builtin", { fg = "#F8AC78", italic = true })
hl(0, "@variable.parameter", { fg = "#FFFFFF" })
hl(0, "@variable.member", { fg = "#FFFFFF" })
hl(0, "@constant", { fg = "#FFCC00" })
hl(0, "@constant.builtin", { fg = "#F8AC78" })
hl(0, "@constant.macro", { fg = "#F8AC78" })
hl(0, "@module", { fg = "#1CD3E1" })
hl(0, "@label", { fg = "#9CC0FF" })
hl(0, "@string", { fg = "#22DAA4" })
hl(0, "@string.documentation", { fg = "#90D090" })
hl(0, "@string.escape", { fg = "#F8AC78" })
hl(0, "@string.regexp", { fg = "#F8AC78" })
hl(0, "@string.special", { fg = "#F8AC78" })
hl(0, "@character", { fg = "#22DAA4" })
hl(0, "@character.special", { fg = "#F8AC78" })
hl(0, "@boolean", { fg = "#FFCC00" })
hl(0, "@number", { fg = "#FFCC00" })
hl(0, "@number.float", { fg = "#FFCC00" })
hl(0, "@type", { fg = "#1CD3E1" })
hl(0, "@type.builtin", { fg = "#1CD3E1", italic = true })
hl(0, "@type.definition", { fg = "#1CD3E1" })
hl(0, "@attribute", { fg = "#F8AC78" })
hl(0, "@attribute.builtin", { fg = "#F8AC78" })
hl(0, "@property", { fg = "#FFFFFF" })
hl(0, "@function", { fg = "#45D945" })
hl(0, "@function.builtin", { fg = "#F8AC78" })
hl(0, "@function.macro", { fg = "#F8AC78" })
hl(0, "@function.method", { fg = "#45D945" })
hl(0, "@constructor", { fg = "#1CD3E1" })
hl(0, "@operator", { fg = "#CCD6EB" })
hl(0, "@keyword", { fg = "#9CC0FF" })
hl(0, "@keyword.function", { fg = "#9CC0FF" })
hl(0, "@keyword.operator", { fg = "#9CC0FF" })
hl(0, "@keyword.import", { fg = "#9CC0FF" })
hl(0, "@keyword.return", { fg = "#9CC0FF" })
hl(0, "@keyword.exception", { fg = "#9CC0FF" })
hl(0, "@punctuation.delimiter", { fg = "#CCD6EB" })
hl(0, "@punctuation.bracket", { fg = "#CCD6EB" })
hl(0, "@punctuation.special", { fg = "#F8AC78" })
hl(0, "@comment", { fg = "#90D090", italic = true })
hl(0, "@comment.documentation", { fg = "#90D090", italic = true })
hl(0, "@comment.error", { fg = "#003399", bg = "#F9A9AF", bold = true })
hl(0, "@comment.warning", { fg = "#003399", bg = "#FFCC00", bold = true })
hl(0, "@comment.todo", { link = "Todo" })
hl(0, "@comment.note", { fg = "#003399", bg = "#9CC0FF", bold = true })
hl(0, "@tag", { fg = "#9CC0FF" })
hl(0, "@tag.builtin", { fg = "#9CC0FF" })
hl(0, "@tag.attribute", { fg = "#45D945", italic = true })
hl(0, "@tag.delimiter", { fg = "#CCD6EB" })
hl(0, "@markup.strong", { fg = "#FFFFFF", bold = true })
hl(0, "@markup.italic", { fg = "#FFFFFF", italic = true })
hl(0, "@markup.strikethrough", { fg = "#ADBEDE", strikethrough = true })
hl(0, "@markup.underline", { fg = "#FFFFFF", underline = true })
hl(0, "@markup.quote", { fg = "#ADBEDE", italic = true })
hl(0, "@markup.math", { fg = "#FFCC00" })
hl(0, "@markup.link", { fg = "#45D945" })
hl(0, "@markup.link.label", { fg = "#9CC0FF" })
hl(0, "@markup.link.url", { fg = "#45D945", underline = true })
hl(0, "@markup.raw", { fg = "#22DAA4" })
hl(0, "@markup.list", { fg = "#9CC0FF" })
hl(0, "@markup.list.checked", { fg = "#45D945" })
hl(0, "@markup.list.unchecked", { fg = "#ADBEDE" })
hl(0, "@diff.plus", { fg = "#45D945" })
hl(0, "@diff.minus", { fg = "#F9A9AF" })
hl(0, "@diff.delta", { fg = "#FFCC00" })
hl(0, "@lsp.type.namespace", { link = "@module" })
hl(0, "@lsp.type.class", { link = "@type" })
hl(0, "@lsp.type.enum", { link = "@type" })
hl(0, "@lsp.type.interface", { link = "@type" })
hl(0, "@lsp.type.struct", { link = "@type" })
hl(0, "@lsp.type.parameter", { link = "@variable.parameter" })
hl(0, "@lsp.type.property", { link = "@property" })
hl(0, "@lsp.type.enumMember", { link = "@constant" })
hl(0, "@lsp.type.method", { link = "@function.method" })
hl(0, "MiniIconsAzure", { fg = "#45D945" })
hl(0, "MiniIconsBlue", { fg = "#9CC0FF" })
hl(0, "MiniIconsCyan", { fg = "#1CD3E1" })
hl(0, "MiniIconsGreen", { fg = "#45D945" })
hl(0, "MiniIconsGrey", { fg = "#ADBEDE" })
hl(0, "MiniIconsOrange", { fg = "#FFCC00" })
hl(0, "MiniIconsPurple", { fg = "#F8AC78" })
hl(0, "MiniIconsRed", { fg = "#F9A9AF" })
hl(0, "MiniIconsYellow", { fg = "#FFCC00" })
hl(0, "MiniFilesTitleFocused", { fg = "#9CC0FF", bg = "#1A47A3", bold = true })
hl(0, "MiniFilesDirectory", { fg = "#45D945" })
hl(0, "MiniFilesFile", { fg = "#FFFFFF" })
hl(0, "MiniFilesCursorLine", { bg = "#2E58AB" })
hl(0, "MiniPickMatchCurrent", { bg = "#2E58AB", bold = true })
hl(0, "MiniPickMatchRanges", { fg = "#9CC0FF", bold = true })
hl(0, "MiniPickPrompt", { fg = "#9CC0FF", bold = true })
hl(0, "MiniPickBorderText", { fg = "#9CC0FF" })
hl(0, "MiniClueDescGroup", { fg = "#1CD3E1" })
hl(0, "MiniClueDescSingle", { fg = "#FFFFFF" })
hl(0, "MiniClueNextKey", { fg = "#9CC0FF", bold = true })
hl(0, "MiniClueTitle", { fg = "#9CC0FF", bg = "#1A47A3", bold = true })
hl(0, "RenderMarkdownCode", { bg = "#1A47A3" })
hl(0, "RenderMarkdownCodeInline", { fg = "#22DAA4", bg = "#1A47A3" })
hl(0, "RenderMarkdownBullet", { fg = "#9CC0FF" })
hl(0, "RenderMarkdownQuote", { fg = "#ADBEDE" })
hl(0, "RenderMarkdownDash", { fg = "#819ACD" })
hl(0, "RenderMarkdownTableHead", { fg = "#1CD3E1", bold = true })
hl(0, "RenderMarkdownTableRow", { fg = "#ADBEDE" })
hl(0, "RenderMarkdownLink", { fg = "#45D945" })
hl(0, "RenderMarkdownChecked", { fg = "#45D945" })
hl(0, "RenderMarkdownUnchecked", { fg = "#ADBEDE" })
hl(0, "@markup.heading.1", { fg = "#9CC0FF", bold = true })
hl(0, "RenderMarkdownH1", { fg = "#9CC0FF", bold = true })
hl(0, "RenderMarkdownH1Bg", { fg = "#9CC0FF", bg = "#1748A8", bold = true })
hl(0, "@markup.heading.2", { fg = "#45D945", bold = true })
hl(0, "RenderMarkdownH2", { fg = "#45D945", bold = true })
hl(0, "RenderMarkdownH2Bg", { fg = "#45D945", bg = "#0A4C8C", bold = true })
hl(0, "@markup.heading.3", { fg = "#22DAA4", bold = true })
hl(0, "RenderMarkdownH3", { fg = "#22DAA4", bold = true })
hl(0, "RenderMarkdownH3Bg", { fg = "#22DAA4", bg = "#054C9B", bold = true })
hl(0, "@markup.heading.4", { fg = "#FFCC00", bold = true })
hl(0, "RenderMarkdownH4", { fg = "#FFCC00", bold = true })
hl(0, "RenderMarkdownH4Bg", { fg = "#FFCC00", bg = "#264A82", bold = true })
hl(0, "@markup.heading.5", { fg = "#1CD3E1", bold = true })
hl(0, "RenderMarkdownH5", { fg = "#1CD3E1", bold = true })
hl(0, "RenderMarkdownH5Bg", { fg = "#1CD3E1", bg = "#044BA4", bold = true })
hl(0, "@markup.heading.6", { fg = "#F8AC78", bold = true })
hl(0, "RenderMarkdownH6", { fg = "#F8AC78", bold = true })
hl(0, "RenderMarkdownH6Bg", { fg = "#F8AC78", bg = "#254594", bold = true })

vim.g.terminal_color_0 = "#4066B2"
vim.g.terminal_color_1 = "#F9A9AF"
vim.g.terminal_color_2 = "#45D945"
vim.g.terminal_color_3 = "#FFCC00"
vim.g.terminal_color_4 = "#9CC0FF"
vim.g.terminal_color_5 = "#F8AC78"
vim.g.terminal_color_6 = "#9CC0FF"
vim.g.terminal_color_7 = "#ADBEDE"
vim.g.terminal_color_8 = "#738FC7"
vim.g.terminal_color_9 = "#FABABF"
vim.g.terminal_color_10 = "#6AE16A"
vim.g.terminal_color_11 = "#FFD633"
vim.g.terminal_color_12 = "#B0CDFF"
vim.g.terminal_color_13 = "#F9BD93"
vim.g.terminal_color_14 = "#B0CDFF"
vim.g.terminal_color_15 = "#FFFFFF"
