-- retro-razzy - erzeugt von retro-coding-themes, nicht von Hand aendern.
-- Quelle: src/retro_coding_themes/data/razzy.json, Ableitung in derive.py.

vim.cmd("highlight clear")
if vim.fn.exists("syntax_on") == 1 then
  vim.cmd("syntax reset")
end

vim.o.background = "dark"
vim.g.colors_name = "retro-razzy"

local hl = vim.api.nvim_set_hl

hl(0, "Normal", { fg = "#EEEEEE", bg = "#1E1E2E" })
hl(0, "NormalNC", { link = "Normal" })
hl(0, "NormalFloat", { fg = "#EEEEEE", bg = "#333341" })
hl(0, "FloatBorder", { fg = "#7D7D89", bg = "#333341" })
hl(0, "FloatTitle", { fg = "#ED7798", bg = "#333341", bold = true })
hl(0, "ColorColumn", { bg = "#2D2D3B" })
hl(0, "Conceal", { fg = "#7C7C84" })
hl(0, "Cursor", { fg = "#1E1E2E", bg = "#EEEEEE" })
hl(0, "lCursor", { link = "Cursor" })
hl(0, "TermCursor", { link = "Cursor" })
hl(0, "CursorLine", { bg = "#2D2D3B" })
hl(0, "CursorColumn", { link = "CursorLine" })
hl(0, "CursorLineNr", { fg = "#ED7798", bold = true })
hl(0, "LineNr", { fg = "#7C7C84" })
hl(0, "SignColumn", { bg = "#1E1E2E" })
hl(0, "FoldColumn", { fg = "#7C7C84" })
hl(0, "Folded", { fg = "#A5A5AB", bg = "#333341" })
hl(0, "EndOfBuffer", { fg = "#1E1E2E" })
hl(0, "NonText", { fg = "#7C7C84" })
hl(0, "Whitespace", { fg = "#52525E" })
hl(0, "SpecialKey", { fg = "#7C7C84" })
hl(0, "Visual", { bg = "#581D38" })
hl(0, "VisualNOS", { link = "Visual" })
hl(0, "MatchParen", { fg = "#ED7798", bg = "#434351", bold = true })
hl(0, "Pmenu", { fg = "#EEEEEE", bg = "#333341" })
hl(0, "PmenuSel", { fg = "#EEEEEE", bg = "#434351", bold = true })
hl(0, "PmenuSbar", { bg = "#333341" })
hl(0, "PmenuThumb", { bg = "#7D7D89" })
hl(0, "PmenuKind", { fg = "#BD9777" })
hl(0, "PmenuKindSel", { fg = "#BD9777", bg = "#434351" })
hl(0, "PmenuExtra", { fg = "#7C7C84" })
hl(0, "PmenuExtraSel", { fg = "#7C7C84", bg = "#434351" })
hl(0, "WildMenu", { link = "PmenuSel" })
hl(0, "StatusLine", { fg = "#FFFFFF", bg = "#C51A4A", bold = true })
hl(0, "StatusLineNC", { fg = "#A5A5AB", bg = "#333341" })
hl(0, "WinBar", { fg = "#A5A5AB", bg = "#1E1E2E" })
hl(0, "WinBarNC", { fg = "#7C7C84", bg = "#1E1E2E" })
hl(0, "WinSeparator", { fg = "#7D7D89" })
hl(0, "TabLine", { fg = "#A5A5AB", bg = "#333341" })
hl(0, "TabLineFill", { bg = "#1E1E2E" })
hl(0, "TabLineSel", { fg = "#FFFFFF", bg = "#C51A4A", bold = true })
hl(0, "Search", { fg = "#EEEEEE", bg = "#644D21" })
hl(0, "IncSearch", { fg = "#1E1E2E", bg = "#E5A50A", bold = true })
hl(0, "CurSearch", { link = "IncSearch" })
hl(0, "Substitute", { fg = "#1E1E2E", bg = "#E97D7D" })
hl(0, "QuickFixLine", { bg = "#434351", bold = true })
hl(0, "Directory", { fg = "#6CC24A" })
hl(0, "Title", { fg = "#ED7798", bold = true })
hl(0, "Question", { fg = "#6CC24A" })
hl(0, "MoreMsg", { fg = "#6CC24A" })
hl(0, "ModeMsg", { fg = "#EEEEEE", bold = true })
hl(0, "MsgArea", { fg = "#EEEEEE", bg = "#1E1E2E" })
hl(0, "MsgSeparator", { fg = "#7D7D89" })
hl(0, "WarningMsg", { fg = "#E5A50A" })
hl(0, "ErrorMsg", { fg = "#E97D7D" })
hl(0, "SpellBad", { sp = "#E97D7D", undercurl = true })
hl(0, "SpellCap", { sp = "#E5A50A", undercurl = true })
hl(0, "SpellLocal", { sp = "#ED7798", undercurl = true })
hl(0, "SpellRare", { sp = "#9AD183", undercurl = true })
hl(0, "Comment", { fg = "#ADD89C", italic = true })
hl(0, "Constant", { fg = "#E5A50A" })
hl(0, "String", { fg = "#A6A158" })
hl(0, "Character", { fg = "#A6A158" })
hl(0, "Number", { fg = "#E5A50A" })
hl(0, "Boolean", { fg = "#E5A50A" })
hl(0, "Float", { fg = "#E5A50A" })
hl(0, "Identifier", { fg = "#EEEEEE" })
hl(0, "Function", { fg = "#6CC24A" })
hl(0, "Statement", { fg = "#ED7798" })
hl(0, "Conditional", { fg = "#ED7798" })
hl(0, "Repeat", { fg = "#ED7798" })
hl(0, "Label", { fg = "#ED7798" })
hl(0, "Operator", { fg = "#C4C4C8" })
hl(0, "Keyword", { fg = "#ED7798" })
hl(0, "Exception", { fg = "#ED7798" })
hl(0, "PreProc", { fg = "#E68442" })
hl(0, "Include", { fg = "#ED7798" })
hl(0, "Define", { fg = "#E68442" })
hl(0, "Macro", { fg = "#E68442" })
hl(0, "PreCondit", { fg = "#E68442" })
hl(0, "Type", { fg = "#BD9777" })
hl(0, "StorageClass", { fg = "#ED7798" })
hl(0, "Structure", { fg = "#BD9777" })
hl(0, "Typedef", { fg = "#BD9777" })
hl(0, "Special", { fg = "#E68442" })
hl(0, "SpecialChar", { fg = "#E68442" })
hl(0, "Tag", { fg = "#ED7798" })
hl(0, "Delimiter", { fg = "#C4C4C8" })
hl(0, "SpecialComment", { fg = "#ADD89C", bold = true })
hl(0, "Debug", { fg = "#E97D7D" })
hl(0, "Underlined", { fg = "#6CC24A", underline = true })
hl(0, "Ignore", { fg = "#7C7C84" })
hl(0, "Error", { fg = "#E97D7D", bold = true })
hl(0, "Todo", { fg = "#1E1E2E", bg = "#E5A50A", bold = true })
hl(0, "Added", { fg = "#6CC24A" })
hl(0, "Changed", { fg = "#E5A50A" })
hl(0, "Removed", { fg = "#E97D7D" })
hl(0, "DiffAdd", { bg = "#2C3C33" })
hl(0, "DiffChange", { bg = "#362E2A" })
hl(0, "DiffDelete", { bg = "#432F3C" })
hl(0, "DiffText", { bg = "#5A4623", bold = true })
hl(0, "DiagnosticError", { fg = "#E97D7D" })
hl(0, "DiagnosticWarn", { fg = "#E5A50A" })
hl(0, "DiagnosticInfo", { fg = "#ED7798" })
hl(0, "DiagnosticHint", { fg = "#9AD183" })
hl(0, "DiagnosticOk", { fg = "#6CC24A" })
hl(0, "DiagnosticUnderlineError", { sp = "#E97D7D", undercurl = true })
hl(0, "DiagnosticUnderlineWarn", { sp = "#E5A50A", undercurl = true })
hl(0, "DiagnosticUnderlineInfo", { sp = "#ED7798", undercurl = true })
hl(0, "DiagnosticUnderlineHint", { sp = "#9AD183", undercurl = true })
hl(0, "DiagnosticUnderlineOk", { sp = "#6CC24A", undercurl = true })
hl(0, "DiagnosticVirtualTextError", { fg = "#E97D7D", bg = "#362937" })
hl(0, "DiagnosticVirtualTextWarn", { fg = "#E5A50A", bg = "#362E2A" })
hl(0, "DiagnosticVirtualTextInfo", { fg = "#ED7798", bg = "#37293B" })
hl(0, "DiagnosticVirtualTextHint", { fg = "#9AD183", bg = "#2D3338" })
hl(0, "@variable", { fg = "#EEEEEE" })
hl(0, "@variable.builtin", { fg = "#E68442", italic = true })
hl(0, "@variable.parameter", { fg = "#EEEEEE" })
hl(0, "@variable.member", { fg = "#EEEEEE" })
hl(0, "@constant", { fg = "#E5A50A" })
hl(0, "@constant.builtin", { fg = "#E68442" })
hl(0, "@constant.macro", { fg = "#E68442" })
hl(0, "@module", { fg = "#BD9777" })
hl(0, "@label", { fg = "#ED7798" })
hl(0, "@string", { fg = "#A6A158" })
hl(0, "@string.documentation", { fg = "#ADD89C" })
hl(0, "@string.escape", { fg = "#E68442" })
hl(0, "@string.regexp", { fg = "#E68442" })
hl(0, "@string.special", { fg = "#E68442" })
hl(0, "@character", { fg = "#A6A158" })
hl(0, "@character.special", { fg = "#E68442" })
hl(0, "@boolean", { fg = "#E5A50A" })
hl(0, "@number", { fg = "#E5A50A" })
hl(0, "@number.float", { fg = "#E5A50A" })
hl(0, "@type", { fg = "#BD9777" })
hl(0, "@type.builtin", { fg = "#BD9777", italic = true })
hl(0, "@type.definition", { fg = "#BD9777" })
hl(0, "@attribute", { fg = "#E68442" })
hl(0, "@attribute.builtin", { fg = "#E68442" })
hl(0, "@property", { fg = "#EEEEEE" })
hl(0, "@function", { fg = "#6CC24A" })
hl(0, "@function.builtin", { fg = "#E68442" })
hl(0, "@function.macro", { fg = "#E68442" })
hl(0, "@function.method", { fg = "#6CC24A" })
hl(0, "@constructor", { fg = "#BD9777" })
hl(0, "@operator", { fg = "#C4C4C8" })
hl(0, "@keyword", { fg = "#ED7798" })
hl(0, "@keyword.function", { fg = "#ED7798" })
hl(0, "@keyword.operator", { fg = "#ED7798" })
hl(0, "@keyword.import", { fg = "#ED7798" })
hl(0, "@keyword.return", { fg = "#ED7798" })
hl(0, "@keyword.exception", { fg = "#ED7798" })
hl(0, "@punctuation.delimiter", { fg = "#C4C4C8" })
hl(0, "@punctuation.bracket", { fg = "#C4C4C8" })
hl(0, "@punctuation.special", { fg = "#E68442" })
hl(0, "@comment", { fg = "#ADD89C", italic = true })
hl(0, "@comment.documentation", { fg = "#ADD89C", italic = true })
hl(0, "@comment.error", { fg = "#1E1E2E", bg = "#E97D7D", bold = true })
hl(0, "@comment.warning", { fg = "#1E1E2E", bg = "#E5A50A", bold = true })
hl(0, "@comment.todo", { link = "Todo" })
hl(0, "@comment.note", { fg = "#1E1E2E", bg = "#ED7798", bold = true })
hl(0, "@tag", { fg = "#ED7798" })
hl(0, "@tag.builtin", { fg = "#ED7798" })
hl(0, "@tag.attribute", { fg = "#6CC24A", italic = true })
hl(0, "@tag.delimiter", { fg = "#C4C4C8" })
hl(0, "@markup.strong", { fg = "#EEEEEE", bold = true })
hl(0, "@markup.italic", { fg = "#EEEEEE", italic = true })
hl(0, "@markup.strikethrough", { fg = "#A5A5AB", strikethrough = true })
hl(0, "@markup.underline", { fg = "#EEEEEE", underline = true })
hl(0, "@markup.quote", { fg = "#A5A5AB", italic = true })
hl(0, "@markup.math", { fg = "#E5A50A" })
hl(0, "@markup.link", { fg = "#6CC24A" })
hl(0, "@markup.link.label", { fg = "#ED7798" })
hl(0, "@markup.link.url", { fg = "#6CC24A", underline = true })
hl(0, "@markup.raw", { fg = "#A6A158" })
hl(0, "@markup.list", { fg = "#ED7798" })
hl(0, "@markup.list.checked", { fg = "#6CC24A" })
hl(0, "@markup.list.unchecked", { fg = "#A5A5AB" })
hl(0, "@diff.plus", { fg = "#6CC24A" })
hl(0, "@diff.minus", { fg = "#E97D7D" })
hl(0, "@diff.delta", { fg = "#E5A50A" })
hl(0, "@lsp.type.namespace", { link = "@module" })
hl(0, "@lsp.type.class", { link = "@type" })
hl(0, "@lsp.type.enum", { link = "@type" })
hl(0, "@lsp.type.interface", { link = "@type" })
hl(0, "@lsp.type.struct", { link = "@type" })
hl(0, "@lsp.type.parameter", { link = "@variable.parameter" })
hl(0, "@lsp.type.property", { link = "@property" })
hl(0, "@lsp.type.enumMember", { link = "@constant" })
hl(0, "@lsp.type.method", { link = "@function.method" })
hl(0, "MiniIconsAzure", { fg = "#6CC24A" })
hl(0, "MiniIconsBlue", { fg = "#ED7798" })
hl(0, "MiniIconsCyan", { fg = "#BD9777" })
hl(0, "MiniIconsGreen", { fg = "#6CC24A" })
hl(0, "MiniIconsGrey", { fg = "#A5A5AB" })
hl(0, "MiniIconsOrange", { fg = "#E5A50A" })
hl(0, "MiniIconsPurple", { fg = "#E68442" })
hl(0, "MiniIconsRed", { fg = "#E97D7D" })
hl(0, "MiniIconsYellow", { fg = "#E5A50A" })
hl(0, "MiniFilesTitleFocused", { fg = "#ED7798", bg = "#333341", bold = true })
hl(0, "MiniFilesDirectory", { fg = "#6CC24A" })
hl(0, "MiniFilesFile", { fg = "#EEEEEE" })
hl(0, "MiniFilesCursorLine", { bg = "#434351" })
hl(0, "MiniPickMatchCurrent", { bg = "#434351", bold = true })
hl(0, "MiniPickMatchRanges", { fg = "#ED7798", bold = true })
hl(0, "MiniPickPrompt", { fg = "#ED7798", bold = true })
hl(0, "MiniPickBorderText", { fg = "#ED7798" })
hl(0, "MiniClueDescGroup", { fg = "#BD9777" })
hl(0, "MiniClueDescSingle", { fg = "#EEEEEE" })
hl(0, "MiniClueNextKey", { fg = "#ED7798", bold = true })
hl(0, "MiniClueTitle", { fg = "#ED7798", bg = "#333341", bold = true })
hl(0, "RenderMarkdownCode", { bg = "#333341" })
hl(0, "RenderMarkdownCodeInline", { fg = "#A6A158", bg = "#333341" })
hl(0, "RenderMarkdownBullet", { fg = "#ED7798" })
hl(0, "RenderMarkdownQuote", { fg = "#A5A5AB" })
hl(0, "RenderMarkdownDash", { fg = "#7D7D89" })
hl(0, "RenderMarkdownTableHead", { fg = "#BD9777", bold = true })
hl(0, "RenderMarkdownTableRow", { fg = "#A5A5AB" })
hl(0, "RenderMarkdownLink", { fg = "#6CC24A" })
hl(0, "RenderMarkdownChecked", { fg = "#6CC24A" })
hl(0, "RenderMarkdownUnchecked", { fg = "#A5A5AB" })
hl(0, "@markup.heading.1", { fg = "#ED7798", bold = true })
hl(0, "RenderMarkdownH1", { fg = "#ED7798", bold = true })
hl(0, "RenderMarkdownH1Bg", { fg = "#ED7798", bg = "#3D2B3E", bold = true })
hl(0, "@markup.heading.2", { fg = "#6CC24A", bold = true })
hl(0, "RenderMarkdownH2", { fg = "#6CC24A", bold = true })
hl(0, "RenderMarkdownH2Bg", { fg = "#6CC24A", bg = "#2A3732", bold = true })
hl(0, "@markup.heading.3", { fg = "#A6A158", bold = true })
hl(0, "RenderMarkdownH3", { fg = "#A6A158", bold = true })
hl(0, "RenderMarkdownH3Bg", { fg = "#A6A158", bg = "#323234", bold = true })
hl(0, "@markup.heading.4", { fg = "#E5A50A", bold = true })
hl(0, "RenderMarkdownH4", { fg = "#E5A50A", bold = true })
hl(0, "RenderMarkdownH4Bg", { fg = "#E5A50A", bg = "#3C3229", bold = true })
hl(0, "@markup.heading.5", { fg = "#BD9777", bold = true })
hl(0, "RenderMarkdownH5", { fg = "#BD9777", bold = true })
hl(0, "RenderMarkdownH5Bg", { fg = "#BD9777", bg = "#363039", bold = true })
hl(0, "@markup.heading.6", { fg = "#E68442", bold = true })
hl(0, "RenderMarkdownH6", { fg = "#E68442", bold = true })
hl(0, "RenderMarkdownH6Bg", { fg = "#E68442", bg = "#3C2D31", bold = true })

vim.g.terminal_color_0 = "#52525E"
vim.g.terminal_color_1 = "#E97D7D"
vim.g.terminal_color_2 = "#6CC24A"
vim.g.terminal_color_3 = "#E5A50A"
vim.g.terminal_color_4 = "#ED7798"
vim.g.terminal_color_5 = "#E68442"
vim.g.terminal_color_6 = "#ED7798"
vim.g.terminal_color_7 = "#A5A5AB"
vim.g.terminal_color_8 = "#7C7C84"
vim.g.terminal_color_9 = "#ED9797"
vim.g.terminal_color_10 = "#89CE6E"
vim.g.terminal_color_11 = "#EAB73B"
vim.g.terminal_color_12 = "#F192AD"
vim.g.terminal_color_13 = "#EB9D68"
vim.g.terminal_color_14 = "#F192AD"
vim.g.terminal_color_15 = "#EEEEEE"
