-- retro-boing - erzeugt von retro-coding-themes, nicht von Hand aendern.
-- Quelle: src/retro_coding_themes/data/boing.json, Ableitung in derive.py.

vim.cmd("highlight clear")
if vim.fn.exists("syntax_on") == 1 then
  vim.cmd("syntax reset")
end

vim.o.background = "dark"
vim.g.colors_name = "retro-boing"

local hl = vim.api.nvim_set_hl

hl(0, "Normal", { fg = "#FFFFFF", bg = "#004D9B" })
hl(0, "NormalNC", { link = "Normal" })
hl(0, "NormalFloat", { fg = "#FFFFFF", bg = "#1A5FA5" })
hl(0, "FloatBorder", { fg = "#94B4D5", bg = "#1A5FA5" })
hl(0, "FloatTitle", { fg = "#FFCF99", bg = "#1A5FA5", bold = true })
hl(0, "ColorColumn", { bg = "#1259A2" })
hl(0, "Conceal", { fg = "#94B4D5" })
hl(0, "Cursor", { fg = "#004D9B", bg = "#FFFFFF" })
hl(0, "lCursor", { link = "Cursor" })
hl(0, "TermCursor", { link = "Cursor" })
hl(0, "CursorLine", { bg = "#1259A2" })
hl(0, "CursorColumn", { link = "CursorLine" })
hl(0, "CursorLineNr", { fg = "#FFCF99", bold = true })
hl(0, "LineNr", { fg = "#94B4D5" })
hl(0, "SignColumn", { bg = "#004D9B" })
hl(0, "FoldColumn", { fg = "#94B4D5" })
hl(0, "Folded", { fg = "#CBDBEA", bg = "#1A5FA5" })
hl(0, "EndOfBuffer", { fg = "#004D9B" })
hl(0, "NonText", { fg = "#94B4D5" })
hl(0, "Whitespace", { fg = "#407AB4" })
hl(0, "SpecialKey", { fg = "#94B4D5" })
hl(0, "Visual", { bg = "#596265" })
hl(0, "VisualNOS", { link = "Visual" })
hl(0, "MatchParen", { fg = "#FFCF99", bg = "#2E6DAD", bold = true })
hl(0, "Pmenu", { fg = "#FFFFFF", bg = "#1A5FA5" })
hl(0, "PmenuSel", { fg = "#FFFFFF", bg = "#2E6DAD", bold = true })
hl(0, "PmenuSbar", { bg = "#1A5FA5" })
hl(0, "PmenuThumb", { bg = "#94B4D5" })
hl(0, "PmenuKind", { fg = "#EBEBA0" })
hl(0, "PmenuKindSel", { fg = "#EBEBA0", bg = "#2E6DAD" })
hl(0, "PmenuExtra", { fg = "#94B4D5" })
hl(0, "PmenuExtraSel", { fg = "#94B4D5", bg = "#2E6DAD" })
hl(0, "WildMenu", { link = "PmenuSel" })
hl(0, "StatusLine", { fg = "#000000", bg = "#FF8800", bold = true })
hl(0, "StatusLineNC", { fg = "#CBDBEA", bg = "#1A5FA5" })
hl(0, "WinBar", { fg = "#CBDBEA", bg = "#004D9B" })
hl(0, "WinBarNC", { fg = "#94B4D5", bg = "#004D9B" })
hl(0, "WinSeparator", { fg = "#94B4D5" })
hl(0, "TabLine", { fg = "#CBDBEA", bg = "#1A5FA5" })
hl(0, "TabLineFill", { bg = "#004D9B" })
hl(0, "TabLineSel", { fg = "#000000", bg = "#FF8800", bold = true })
hl(0, "Search", { fg = "#FFFFFF", bg = "#59838E" })
hl(0, "IncSearch", { fg = "#004D9B", bg = "#FFE875", bold = true })
hl(0, "CurSearch", { link = "IncSearch" })
hl(0, "Substitute", { fg = "#004D9B", bg = "#FFCECE" })
hl(0, "QuickFixLine", { bg = "#2E6DAD", bold = true })
hl(0, "Directory", { fg = "#B9DCFF" })
hl(0, "Title", { fg = "#FFCF99", bold = true })
hl(0, "Question", { fg = "#B4E4B4" })
hl(0, "MoreMsg", { fg = "#B4E4B4" })
hl(0, "ModeMsg", { fg = "#FFFFFF", bold = true })
hl(0, "MsgArea", { fg = "#FFFFFF", bg = "#004D9B" })
hl(0, "MsgSeparator", { fg = "#94B4D5" })
hl(0, "WarningMsg", { fg = "#FFD175" })
hl(0, "ErrorMsg", { fg = "#FFCECE" })
hl(0, "SpellBad", { sp = "#FFCECE", undercurl = true })
hl(0, "SpellCap", { sp = "#FFD175", undercurl = true })
hl(0, "SpellLocal", { sp = "#FFCF99", undercurl = true })
hl(0, "SpellRare", { sp = "#C8DAED", undercurl = true })
hl(0, "Comment", { fg = "#C8DAED", italic = true })
hl(0, "Constant", { fg = "#FFE875" })
hl(0, "String", { fg = "#B4E4B4" })
hl(0, "Character", { fg = "#B4E4B4" })
hl(0, "Number", { fg = "#FFE875" })
hl(0, "Boolean", { fg = "#FFE875" })
hl(0, "Float", { fg = "#FFE875" })
hl(0, "Identifier", { fg = "#FFFFFF" })
hl(0, "Function", { fg = "#B9DCFF" })
hl(0, "Statement", { fg = "#FFCF99" })
hl(0, "Conditional", { fg = "#FFCF99" })
hl(0, "Repeat", { fg = "#FFCF99" })
hl(0, "Label", { fg = "#FFCF99" })
hl(0, "Operator", { fg = "#CCDBEB" })
hl(0, "Keyword", { fg = "#FFCF99" })
hl(0, "Exception", { fg = "#FFCF99" })
hl(0, "PreProc", { fg = "#FFC5F2" })
hl(0, "Include", { fg = "#FFCF99" })
hl(0, "Define", { fg = "#FFC5F2" })
hl(0, "Macro", { fg = "#FFC5F2" })
hl(0, "PreCondit", { fg = "#FFC5F2" })
hl(0, "Type", { fg = "#EBEBA0" })
hl(0, "StorageClass", { fg = "#FFCF99" })
hl(0, "Structure", { fg = "#EBEBA0" })
hl(0, "Typedef", { fg = "#EBEBA0" })
hl(0, "Special", { fg = "#FFC5F2" })
hl(0, "SpecialChar", { fg = "#FFC5F2" })
hl(0, "Tag", { fg = "#FFCF99" })
hl(0, "Delimiter", { fg = "#CCDBEB" })
hl(0, "SpecialComment", { fg = "#C8DAED", bold = true })
hl(0, "Debug", { fg = "#FFCECE" })
hl(0, "Underlined", { fg = "#B9DCFF", underline = true })
hl(0, "Ignore", { fg = "#94B4D5" })
hl(0, "Error", { fg = "#FFCECE", bold = true })
hl(0, "Todo", { fg = "#004D9B", bg = "#FFE875", bold = true })
hl(0, "Added", { fg = "#B4E4B4" })
hl(0, "Changed", { fg = "#FFD175" })
hl(0, "Removed", { fg = "#FFCECE" })
hl(0, "DiffAdd", { bg = "#2068A0" })
hl(0, "DiffChange", { bg = "#1F5D96" })
hl(0, "DiffDelete", { bg = "#2E64A4" })
hl(0, "DiffText", { bg = "#4C7590", bold = true })
hl(0, "DiagnosticError", { fg = "#FFCECE" })
hl(0, "DiagnosticWarn", { fg = "#FFD175" })
hl(0, "DiagnosticInfo", { fg = "#FFCF99" })
hl(0, "DiagnosticHint", { fg = "#C8DAED" })
hl(0, "DiagnosticOk", { fg = "#B4E4B4" })
hl(0, "DiagnosticUnderlineError", { sp = "#FFCECE", undercurl = true })
hl(0, "DiagnosticUnderlineWarn", { sp = "#FFD175", undercurl = true })
hl(0, "DiagnosticUnderlineInfo", { sp = "#FFCF99", undercurl = true })
hl(0, "DiagnosticUnderlineHint", { sp = "#C8DAED", undercurl = true })
hl(0, "DiagnosticUnderlineOk", { sp = "#B4E4B4", undercurl = true })
hl(0, "DiagnosticVirtualTextError", { fg = "#FFCECE", bg = "#1F5CA1" })
hl(0, "DiagnosticVirtualTextWarn", { fg = "#FFD175", bg = "#1F5D96" })
hl(0, "DiagnosticVirtualTextInfo", { fg = "#FFCF99", bg = "#1F5D9B" })
hl(0, "DiagnosticVirtualTextHint", { fg = "#C8DAED", bg = "#185EA5" })
hl(0, "@variable", { fg = "#FFFFFF" })
hl(0, "@variable.builtin", { fg = "#FFC5F2", italic = true })
hl(0, "@variable.parameter", { fg = "#FFFFFF" })
hl(0, "@variable.member", { fg = "#FFFFFF" })
hl(0, "@constant", { fg = "#FFE875" })
hl(0, "@constant.builtin", { fg = "#FFC5F2" })
hl(0, "@constant.macro", { fg = "#FFC5F2" })
hl(0, "@module", { fg = "#EBEBA0" })
hl(0, "@label", { fg = "#FFCF99" })
hl(0, "@string", { fg = "#B4E4B4" })
hl(0, "@string.documentation", { fg = "#C8DAED" })
hl(0, "@string.escape", { fg = "#FFC5F2" })
hl(0, "@string.regexp", { fg = "#FFC5F2" })
hl(0, "@string.special", { fg = "#FFC5F2" })
hl(0, "@character", { fg = "#B4E4B4" })
hl(0, "@character.special", { fg = "#FFC5F2" })
hl(0, "@boolean", { fg = "#FFE875" })
hl(0, "@number", { fg = "#FFE875" })
hl(0, "@number.float", { fg = "#FFE875" })
hl(0, "@type", { fg = "#EBEBA0" })
hl(0, "@type.builtin", { fg = "#EBEBA0", italic = true })
hl(0, "@type.definition", { fg = "#EBEBA0" })
hl(0, "@attribute", { fg = "#FFC5F2" })
hl(0, "@attribute.builtin", { fg = "#FFC5F2" })
hl(0, "@property", { fg = "#FFFFFF" })
hl(0, "@function", { fg = "#B9DCFF" })
hl(0, "@function.builtin", { fg = "#FFC5F2" })
hl(0, "@function.macro", { fg = "#FFC5F2" })
hl(0, "@function.method", { fg = "#B9DCFF" })
hl(0, "@constructor", { fg = "#EBEBA0" })
hl(0, "@operator", { fg = "#CCDBEB" })
hl(0, "@keyword", { fg = "#FFCF99" })
hl(0, "@keyword.function", { fg = "#FFCF99" })
hl(0, "@keyword.operator", { fg = "#FFCF99" })
hl(0, "@keyword.import", { fg = "#FFCF99" })
hl(0, "@keyword.return", { fg = "#FFCF99" })
hl(0, "@keyword.exception", { fg = "#FFCF99" })
hl(0, "@punctuation.delimiter", { fg = "#CCDBEB" })
hl(0, "@punctuation.bracket", { fg = "#CCDBEB" })
hl(0, "@punctuation.special", { fg = "#FFC5F2" })
hl(0, "@comment", { fg = "#C8DAED", italic = true })
hl(0, "@comment.documentation", { fg = "#C8DAED", italic = true })
hl(0, "@comment.error", { fg = "#004D9B", bg = "#FFCECE", bold = true })
hl(0, "@comment.warning", { fg = "#004D9B", bg = "#FFD175", bold = true })
hl(0, "@comment.todo", { link = "Todo" })
hl(0, "@comment.note", { fg = "#004D9B", bg = "#FFCF99", bold = true })
hl(0, "@tag", { fg = "#FFCF99" })
hl(0, "@tag.builtin", { fg = "#FFCF99" })
hl(0, "@tag.attribute", { fg = "#B9DCFF", italic = true })
hl(0, "@tag.delimiter", { fg = "#CCDBEB" })
hl(0, "@markup.strong", { fg = "#FFFFFF", bold = true })
hl(0, "@markup.italic", { fg = "#FFFFFF", italic = true })
hl(0, "@markup.strikethrough", { fg = "#CBDBEA", strikethrough = true })
hl(0, "@markup.underline", { fg = "#FFFFFF", underline = true })
hl(0, "@markup.quote", { fg = "#CBDBEA", italic = true })
hl(0, "@markup.math", { fg = "#FFE875" })
hl(0, "@markup.link", { fg = "#B9DCFF" })
hl(0, "@markup.link.label", { fg = "#FFCF99" })
hl(0, "@markup.link.url", { fg = "#B9DCFF", underline = true })
hl(0, "@markup.raw", { fg = "#B4E4B4" })
hl(0, "@markup.list", { fg = "#FFCF99" })
hl(0, "@markup.list.checked", { fg = "#B4E4B4" })
hl(0, "@markup.list.unchecked", { fg = "#CBDBEA" })
hl(0, "@diff.plus", { fg = "#B4E4B4" })
hl(0, "@diff.minus", { fg = "#FFCECE" })
hl(0, "@diff.delta", { fg = "#FFD175" })
hl(0, "@lsp.type.namespace", { link = "@module" })
hl(0, "@lsp.type.class", { link = "@type" })
hl(0, "@lsp.type.enum", { link = "@type" })
hl(0, "@lsp.type.interface", { link = "@type" })
hl(0, "@lsp.type.struct", { link = "@type" })
hl(0, "@lsp.type.parameter", { link = "@variable.parameter" })
hl(0, "@lsp.type.property", { link = "@property" })
hl(0, "@lsp.type.enumMember", { link = "@constant" })
hl(0, "@lsp.type.method", { link = "@function.method" })
hl(0, "MiniIconsAzure", { fg = "#B9DCFF" })
hl(0, "MiniIconsBlue", { fg = "#FFCF99" })
hl(0, "MiniIconsCyan", { fg = "#EBEBA0" })
hl(0, "MiniIconsGreen", { fg = "#B4E4B4" })
hl(0, "MiniIconsGrey", { fg = "#CBDBEA" })
hl(0, "MiniIconsOrange", { fg = "#FFE875" })
hl(0, "MiniIconsPurple", { fg = "#FFC5F2" })
hl(0, "MiniIconsRed", { fg = "#FFCECE" })
hl(0, "MiniIconsYellow", { fg = "#FFD175" })
hl(0, "MiniFilesTitleFocused", { fg = "#FFCF99", bg = "#1A5FA5", bold = true })
hl(0, "MiniFilesDirectory", { fg = "#B9DCFF" })
hl(0, "MiniFilesFile", { fg = "#FFFFFF" })
hl(0, "MiniFilesCursorLine", { bg = "#2E6DAD" })
hl(0, "MiniPickMatchCurrent", { bg = "#2E6DAD", bold = true })
hl(0, "MiniPickMatchRanges", { fg = "#FFCF99", bold = true })
hl(0, "MiniPickPrompt", { fg = "#FFCF99", bold = true })
hl(0, "MiniPickBorderText", { fg = "#FFCF99" })
hl(0, "MiniClueDescGroup", { fg = "#EBEBA0" })
hl(0, "MiniClueDescSingle", { fg = "#FFFFFF" })
hl(0, "MiniClueNextKey", { fg = "#FFCF99", bold = true })
hl(0, "MiniClueTitle", { fg = "#FFCF99", bg = "#1A5FA5", bold = true })
hl(0, "RenderMarkdownCode", { bg = "#1A5FA5" })
hl(0, "RenderMarkdownCodeInline", { fg = "#B4E4B4", bg = "#1A5FA5" })
hl(0, "RenderMarkdownBullet", { fg = "#FFCF99" })
hl(0, "RenderMarkdownQuote", { fg = "#CBDBEA" })
hl(0, "RenderMarkdownDash", { fg = "#94B4D5" })
hl(0, "RenderMarkdownTableHead", { fg = "#EBEBA0", bold = true })
hl(0, "RenderMarkdownTableRow", { fg = "#CBDBEA" })
hl(0, "RenderMarkdownLink", { fg = "#B9DCFF" })
hl(0, "RenderMarkdownChecked", { fg = "#B4E4B4" })
hl(0, "RenderMarkdownUnchecked", { fg = "#CBDBEA" })
hl(0, "@markup.heading.1", { fg = "#FFCF99", bold = true })
hl(0, "RenderMarkdownH1", { fg = "#FFCF99", bold = true })
hl(0, "RenderMarkdownH1Bg", { fg = "#FFCF99", bg = "#26609B", bold = true })
hl(0, "@markup.heading.2", { fg = "#B9DCFF", bold = true })
hl(0, "RenderMarkdownH2", { fg = "#B9DCFF", bold = true })
hl(0, "RenderMarkdownH2Bg", { fg = "#B9DCFF", bg = "#1C62AA", bold = true })
hl(0, "@markup.heading.3", { fg = "#B4E4B4", bold = true })
hl(0, "RenderMarkdownH3", { fg = "#B4E4B4", bold = true })
hl(0, "RenderMarkdownH3Bg", { fg = "#B4E4B4", bg = "#1B649F", bold = true })
hl(0, "@markup.heading.4", { fg = "#FFE875", bold = true })
hl(0, "RenderMarkdownH4", { fg = "#FFE875", bold = true })
hl(0, "RenderMarkdownH4Bg", { fg = "#FFE875", bg = "#266495", bold = true })
hl(0, "@markup.heading.5", { fg = "#EBEBA0", bold = true })
hl(0, "RenderMarkdownH5", { fg = "#EBEBA0", bold = true })
hl(0, "RenderMarkdownH5Bg", { fg = "#EBEBA0", bg = "#23659C", bold = true })
hl(0, "@markup.heading.6", { fg = "#FFC5F2", bold = true })
hl(0, "RenderMarkdownH6", { fg = "#FFC5F2", bold = true })
hl(0, "RenderMarkdownH6Bg", { fg = "#FFC5F2", bg = "#265FA8", bold = true })

vim.g.terminal_color_0 = "#407AB4"
vim.g.terminal_color_1 = "#FFCECE"
vim.g.terminal_color_2 = "#B4E4B4"
vim.g.terminal_color_3 = "#FFD175"
vim.g.terminal_color_4 = "#FFCF99"
vim.g.terminal_color_5 = "#FFC5F2"
vim.g.terminal_color_6 = "#FFCF99"
vim.g.terminal_color_7 = "#CBDBEA"
vim.g.terminal_color_8 = "#739DC8"
vim.g.terminal_color_9 = "#FFD8D8"
vim.g.terminal_color_10 = "#C3E9C3"
vim.g.terminal_color_11 = "#FFDA91"
vim.g.terminal_color_12 = "#FFD9AD"
vim.g.terminal_color_13 = "#FFD1F5"
vim.g.terminal_color_14 = "#FFD9AD"
vim.g.terminal_color_15 = "#FFFFFF"
