-- retro-next - erzeugt von retro-coding-themes, nicht von Hand aendern.
-- Quelle: src/retro_coding_themes/data/next.json, Ableitung in derive.py.

vim.cmd("highlight clear")
if vim.fn.exists("syntax_on") == 1 then
  vim.cmd("syntax reset")
end

vim.o.background = "dark"
vim.g.colors_name = "retro-next"

local hl = vim.api.nvim_set_hl

hl(0, "Normal", { fg = "#E0E0E0", bg = "#2A2A2A" })
hl(0, "NormalNC", { link = "Normal" })
hl(0, "NormalFloat", { fg = "#E0E0E0", bg = "#3C3C3C" })
hl(0, "FloatBorder", { fg = "#868686", bg = "#3C3C3C" })
hl(0, "FloatTitle", { fg = "#BA98DD", bg = "#3C3C3C", bold = true })
hl(0, "ColorColumn", { bg = "#373737" })
hl(0, "Conceal", { fg = "#868686" })
hl(0, "Cursor", { fg = "#2A2A2A", bg = "#E0E0E0" })
hl(0, "lCursor", { link = "Cursor" })
hl(0, "TermCursor", { link = "Cursor" })
hl(0, "CursorLine", { bg = "#373737" })
hl(0, "CursorColumn", { link = "CursorLine" })
hl(0, "CursorLineNr", { fg = "#BA98DD", bold = true })
hl(0, "LineNr", { fg = "#868686" })
hl(0, "SignColumn", { bg = "#2A2A2A" })
hl(0, "FoldColumn", { fg = "#868686" })
hl(0, "Folded", { fg = "#A8A8A8", bg = "#3C3C3C" })
hl(0, "EndOfBuffer", { fg = "#2A2A2A" })
hl(0, "NonText", { fg = "#868686" })
hl(0, "Whitespace", { fg = "#585858" })
hl(0, "SpecialKey", { fg = "#868686" })
hl(0, "Visual", { bg = "#513F63" })
hl(0, "VisualNOS", { link = "Visual" })
hl(0, "MatchParen", { fg = "#BA98DD", bg = "#4B4B4B", bold = true })
hl(0, "Pmenu", { fg = "#E0E0E0", bg = "#3C3C3C" })
hl(0, "PmenuSel", { fg = "#E0E0E0", bg = "#4B4B4B", bold = true })
hl(0, "PmenuSbar", { bg = "#3C3C3C" })
hl(0, "PmenuThumb", { bg = "#868686" })
hl(0, "PmenuKind", { fg = "#E28BB7" })
hl(0, "PmenuKindSel", { fg = "#E28BB7", bg = "#4B4B4B" })
hl(0, "PmenuExtra", { fg = "#868686" })
hl(0, "PmenuExtraSel", { fg = "#868686", bg = "#4B4B4B" })
hl(0, "WildMenu", { link = "PmenuSel" })
hl(0, "StatusLine", { fg = "#000000", bg = "#9966CC", bold = true })
hl(0, "StatusLineNC", { fg = "#A8A8A8", bg = "#3C3C3C" })
hl(0, "WinBar", { fg = "#A8A8A8", bg = "#2A2A2A" })
hl(0, "WinBarNC", { fg = "#868686", bg = "#2A2A2A" })
hl(0, "WinSeparator", { fg = "#868686" })
hl(0, "TabLine", { fg = "#A8A8A8", bg = "#3C3C3C" })
hl(0, "TabLineFill", { bg = "#2A2A2A" })
hl(0, "TabLineSel", { fg = "#000000", bg = "#9966CC", bold = true })
hl(0, "Search", { fg = "#E0E0E0", bg = "#645331" })
hl(0, "IncSearch", { fg = "#2A2A2A", bg = "#CF9F3F", bold = true })
hl(0, "CurSearch", { link = "IncSearch" })
hl(0, "Substitute", { fg = "#2A2A2A", bg = "#E19090" })
hl(0, "QuickFixLine", { bg = "#4B4B4B", bold = true })
hl(0, "Directory", { fg = "#93AAAA" })
hl(0, "Title", { fg = "#BA98DD", bold = true })
hl(0, "Question", { fg = "#56BB56" })
hl(0, "MoreMsg", { fg = "#56BB56" })
hl(0, "ModeMsg", { fg = "#E0E0E0", bold = true })
hl(0, "MsgArea", { fg = "#E0E0E0", bg = "#2A2A2A" })
hl(0, "MsgSeparator", { fg = "#868686" })
hl(0, "WarningMsg", { fg = "#CF9F3F" })
hl(0, "ErrorMsg", { fg = "#E19090" })
hl(0, "SpellBad", { sp = "#E19090", undercurl = true })
hl(0, "SpellCap", { sp = "#CF9F3F", undercurl = true })
hl(0, "SpellLocal", { sp = "#BA98DD", undercurl = true })
hl(0, "SpellRare", { sp = "#A7A7A7", undercurl = true })
hl(0, "Comment", { fg = "#A7A7A7", italic = true })
hl(0, "Constant", { fg = "#CF9F3F" })
hl(0, "String", { fg = "#56BB56" })
hl(0, "Character", { fg = "#56BB56" })
hl(0, "Number", { fg = "#CF9F3F" })
hl(0, "Boolean", { fg = "#CF9F3F" })
hl(0, "Float", { fg = "#CF9F3F" })
hl(0, "Identifier", { fg = "#E0E0E0" })
hl(0, "Function", { fg = "#93AAAA" })
hl(0, "Statement", { fg = "#BA98DD" })
hl(0, "Conditional", { fg = "#BA98DD" })
hl(0, "Repeat", { fg = "#BA98DD" })
hl(0, "Label", { fg = "#BA98DD" })
hl(0, "Operator", { fg = "#BCBCBC" })
hl(0, "Keyword", { fg = "#BA98DD" })
hl(0, "Exception", { fg = "#BA98DD" })
hl(0, "PreProc", { fg = "#DADB75" })
hl(0, "Include", { fg = "#BA98DD" })
hl(0, "Define", { fg = "#DADB75" })
hl(0, "Macro", { fg = "#DADB75" })
hl(0, "PreCondit", { fg = "#DADB75" })
hl(0, "Type", { fg = "#E28BB7" })
hl(0, "StorageClass", { fg = "#BA98DD" })
hl(0, "Structure", { fg = "#E28BB7" })
hl(0, "Typedef", { fg = "#E28BB7" })
hl(0, "Special", { fg = "#DADB75" })
hl(0, "SpecialChar", { fg = "#DADB75" })
hl(0, "Tag", { fg = "#BA98DD" })
hl(0, "Delimiter", { fg = "#BCBCBC" })
hl(0, "SpecialComment", { fg = "#A7A7A7", bold = true })
hl(0, "Debug", { fg = "#E19090" })
hl(0, "Underlined", { fg = "#93AAAA", underline = true })
hl(0, "Ignore", { fg = "#868686" })
hl(0, "Error", { fg = "#E19090", bold = true })
hl(0, "Todo", { fg = "#2A2A2A", bg = "#CF9F3F", bold = true })
hl(0, "Added", { fg = "#56BB56" })
hl(0, "Changed", { fg = "#CF9F3F" })
hl(0, "Removed", { fg = "#E19090" })
hl(0, "DiffAdd", { bg = "#324432" })
hl(0, "DiffChange", { bg = "#3E382D" })
hl(0, "DiffDelete", { bg = "#4B3C3C" })
hl(0, "DiffText", { bg = "#5C4D30", bold = true })
hl(0, "DiagnosticError", { fg = "#E19090" })
hl(0, "DiagnosticWarn", { fg = "#CF9F3F" })
hl(0, "DiagnosticInfo", { fg = "#BA98DD" })
hl(0, "DiagnosticHint", { fg = "#A7A7A7" })
hl(0, "DiagnosticOk", { fg = "#56BB56" })
hl(0, "DiagnosticUnderlineError", { sp = "#E19090", undercurl = true })
hl(0, "DiagnosticUnderlineWarn", { sp = "#CF9F3F", undercurl = true })
hl(0, "DiagnosticUnderlineInfo", { sp = "#BA98DD", undercurl = true })
hl(0, "DiagnosticUnderlineHint", { sp = "#A7A7A7", undercurl = true })
hl(0, "DiagnosticUnderlineOk", { sp = "#56BB56", undercurl = true })
hl(0, "DiagnosticVirtualTextError", { fg = "#E19090", bg = "#403636" })
hl(0, "DiagnosticVirtualTextWarn", { fg = "#CF9F3F", bg = "#3E382D" })
hl(0, "DiagnosticVirtualTextInfo", { fg = "#BA98DD", bg = "#3B373F" })
hl(0, "DiagnosticVirtualTextHint", { fg = "#A7A7A7", bg = "#393939" })
hl(0, "@variable", { fg = "#E0E0E0" })
hl(0, "@variable.builtin", { fg = "#DADB75", italic = true })
hl(0, "@variable.parameter", { fg = "#E0E0E0" })
hl(0, "@variable.member", { fg = "#E0E0E0" })
hl(0, "@constant", { fg = "#CF9F3F" })
hl(0, "@constant.builtin", { fg = "#DADB75" })
hl(0, "@constant.macro", { fg = "#DADB75" })
hl(0, "@module", { fg = "#E28BB7" })
hl(0, "@label", { fg = "#BA98DD" })
hl(0, "@string", { fg = "#56BB56" })
hl(0, "@string.documentation", { fg = "#A7A7A7" })
hl(0, "@string.escape", { fg = "#DADB75" })
hl(0, "@string.regexp", { fg = "#DADB75" })
hl(0, "@string.special", { fg = "#DADB75" })
hl(0, "@character", { fg = "#56BB56" })
hl(0, "@character.special", { fg = "#DADB75" })
hl(0, "@boolean", { fg = "#CF9F3F" })
hl(0, "@number", { fg = "#CF9F3F" })
hl(0, "@number.float", { fg = "#CF9F3F" })
hl(0, "@type", { fg = "#E28BB7" })
hl(0, "@type.builtin", { fg = "#E28BB7", italic = true })
hl(0, "@type.definition", { fg = "#E28BB7" })
hl(0, "@attribute", { fg = "#DADB75" })
hl(0, "@attribute.builtin", { fg = "#DADB75" })
hl(0, "@property", { fg = "#E0E0E0" })
hl(0, "@function", { fg = "#93AAAA" })
hl(0, "@function.builtin", { fg = "#DADB75" })
hl(0, "@function.macro", { fg = "#DADB75" })
hl(0, "@function.method", { fg = "#93AAAA" })
hl(0, "@constructor", { fg = "#E28BB7" })
hl(0, "@operator", { fg = "#BCBCBC" })
hl(0, "@keyword", { fg = "#BA98DD" })
hl(0, "@keyword.function", { fg = "#BA98DD" })
hl(0, "@keyword.operator", { fg = "#BA98DD" })
hl(0, "@keyword.import", { fg = "#BA98DD" })
hl(0, "@keyword.return", { fg = "#BA98DD" })
hl(0, "@keyword.exception", { fg = "#BA98DD" })
hl(0, "@punctuation.delimiter", { fg = "#BCBCBC" })
hl(0, "@punctuation.bracket", { fg = "#BCBCBC" })
hl(0, "@punctuation.special", { fg = "#DADB75" })
hl(0, "@comment", { fg = "#A7A7A7", italic = true })
hl(0, "@comment.documentation", { fg = "#A7A7A7", italic = true })
hl(0, "@comment.error", { fg = "#2A2A2A", bg = "#E19090", bold = true })
hl(0, "@comment.warning", { fg = "#2A2A2A", bg = "#CF9F3F", bold = true })
hl(0, "@comment.todo", { link = "Todo" })
hl(0, "@comment.note", { fg = "#2A2A2A", bg = "#BA98DD", bold = true })
hl(0, "@tag", { fg = "#BA98DD" })
hl(0, "@tag.builtin", { fg = "#BA98DD" })
hl(0, "@tag.attribute", { fg = "#93AAAA", italic = true })
hl(0, "@tag.delimiter", { fg = "#BCBCBC" })
hl(0, "@markup.strong", { fg = "#E0E0E0", bold = true })
hl(0, "@markup.italic", { fg = "#E0E0E0", italic = true })
hl(0, "@markup.strikethrough", { fg = "#A8A8A8", strikethrough = true })
hl(0, "@markup.underline", { fg = "#E0E0E0", underline = true })
hl(0, "@markup.quote", { fg = "#A8A8A8", italic = true })
hl(0, "@markup.math", { fg = "#CF9F3F" })
hl(0, "@markup.link", { fg = "#93AAAA" })
hl(0, "@markup.link.label", { fg = "#BA98DD" })
hl(0, "@markup.link.url", { fg = "#93AAAA", underline = true })
hl(0, "@markup.raw", { fg = "#56BB56" })
hl(0, "@markup.list", { fg = "#BA98DD" })
hl(0, "@markup.list.checked", { fg = "#56BB56" })
hl(0, "@markup.list.unchecked", { fg = "#A8A8A8" })
hl(0, "@diff.plus", { fg = "#56BB56" })
hl(0, "@diff.minus", { fg = "#E19090" })
hl(0, "@diff.delta", { fg = "#CF9F3F" })
hl(0, "@lsp.type.namespace", { link = "@module" })
hl(0, "@lsp.type.class", { link = "@type" })
hl(0, "@lsp.type.enum", { link = "@type" })
hl(0, "@lsp.type.interface", { link = "@type" })
hl(0, "@lsp.type.struct", { link = "@type" })
hl(0, "@lsp.type.parameter", { link = "@variable.parameter" })
hl(0, "@lsp.type.property", { link = "@property" })
hl(0, "@lsp.type.enumMember", { link = "@constant" })
hl(0, "@lsp.type.method", { link = "@function.method" })
hl(0, "MiniIconsAzure", { fg = "#93AAAA" })
hl(0, "MiniIconsBlue", { fg = "#BA98DD" })
hl(0, "MiniIconsCyan", { fg = "#E28BB7" })
hl(0, "MiniIconsGreen", { fg = "#56BB56" })
hl(0, "MiniIconsGrey", { fg = "#A8A8A8" })
hl(0, "MiniIconsOrange", { fg = "#CF9F3F" })
hl(0, "MiniIconsPurple", { fg = "#DADB75" })
hl(0, "MiniIconsRed", { fg = "#E19090" })
hl(0, "MiniIconsYellow", { fg = "#CF9F3F" })
hl(0, "MiniFilesTitleFocused", { fg = "#BA98DD", bg = "#3C3C3C", bold = true })
hl(0, "MiniFilesDirectory", { fg = "#93AAAA" })
hl(0, "MiniFilesFile", { fg = "#E0E0E0" })
hl(0, "MiniFilesCursorLine", { bg = "#4B4B4B" })
hl(0, "MiniPickMatchCurrent", { bg = "#4B4B4B", bold = true })
hl(0, "MiniPickMatchRanges", { fg = "#BA98DD", bold = true })
hl(0, "MiniPickPrompt", { fg = "#BA98DD", bold = true })
hl(0, "MiniPickBorderText", { fg = "#BA98DD" })
hl(0, "MiniClueDescGroup", { fg = "#E28BB7" })
hl(0, "MiniClueDescSingle", { fg = "#E0E0E0" })
hl(0, "MiniClueNextKey", { fg = "#BA98DD", bold = true })
hl(0, "MiniClueTitle", { fg = "#BA98DD", bg = "#3C3C3C", bold = true })
hl(0, "RenderMarkdownCode", { bg = "#3C3C3C" })
hl(0, "RenderMarkdownCodeInline", { fg = "#56BB56", bg = "#3C3C3C" })
hl(0, "RenderMarkdownBullet", { fg = "#BA98DD" })
hl(0, "RenderMarkdownQuote", { fg = "#A8A8A8" })
hl(0, "RenderMarkdownDash", { fg = "#868686" })
hl(0, "RenderMarkdownTableHead", { fg = "#E28BB7", bold = true })
hl(0, "RenderMarkdownTableRow", { fg = "#A8A8A8" })
hl(0, "RenderMarkdownLink", { fg = "#93AAAA" })
hl(0, "RenderMarkdownChecked", { fg = "#56BB56" })
hl(0, "RenderMarkdownUnchecked", { fg = "#A8A8A8" })
hl(0, "@markup.heading.1", { fg = "#BA98DD", bold = true })
hl(0, "RenderMarkdownH1", { fg = "#BA98DD", bold = true })
hl(0, "RenderMarkdownH1Bg", { fg = "#BA98DD", bg = "#403B45", bold = true })
hl(0, "@markup.heading.2", { fg = "#93AAAA", bold = true })
hl(0, "RenderMarkdownH2", { fg = "#93AAAA", bold = true })
hl(0, "RenderMarkdownH2Bg", { fg = "#93AAAA", bg = "#3A3D3D", bold = true })
hl(0, "@markup.heading.3", { fg = "#56BB56", bold = true })
hl(0, "RenderMarkdownH3", { fg = "#56BB56", bold = true })
hl(0, "RenderMarkdownH3Bg", { fg = "#56BB56", bg = "#314031", bold = true })
hl(0, "@markup.heading.4", { fg = "#CF9F3F", bold = true })
hl(0, "RenderMarkdownH4", { fg = "#CF9F3F", bold = true })
hl(0, "RenderMarkdownH4Bg", { fg = "#CF9F3F", bg = "#433C2D", bold = true })
hl(0, "@markup.heading.5", { fg = "#E28BB7", bold = true })
hl(0, "RenderMarkdownH5", { fg = "#E28BB7", bold = true })
hl(0, "RenderMarkdownH5Bg", { fg = "#E28BB7", bg = "#46393F", bold = true })
hl(0, "@markup.heading.6", { fg = "#DADB75", bold = true })
hl(0, "RenderMarkdownH6", { fg = "#DADB75", bold = true })
hl(0, "RenderMarkdownH6Bg", { fg = "#DADB75", bg = "#444535", bold = true })

vim.g.terminal_color_0 = "#585858"
vim.g.terminal_color_1 = "#E19090"
vim.g.terminal_color_2 = "#56BB56"
vim.g.terminal_color_3 = "#CF9F3F"
vim.g.terminal_color_4 = "#BA98DD"
vim.g.terminal_color_5 = "#DADB75"
vim.g.terminal_color_6 = "#BA98DD"
vim.g.terminal_color_7 = "#A8A8A8"
vim.g.terminal_color_8 = "#7C7C7C"
vim.g.terminal_color_9 = "#E7A6A6"
vim.g.terminal_color_10 = "#78C978"
vim.g.terminal_color_11 = "#D9B265"
vim.g.terminal_color_12 = "#C8ADE4"
vim.g.terminal_color_13 = "#E1E291"
vim.g.terminal_color_14 = "#C8ADE4"
vim.g.terminal_color_15 = "#E0E0E0"
