-- retro-bebox - erzeugt von retro-coding-themes, nicht von Hand aendern.
-- Quelle: src/retro_coding_themes/data/bebox.json, Ableitung in derive.py.

vim.cmd("highlight clear")
if vim.fn.exists("syntax_on") == 1 then
  vim.cmd("syntax reset")
end

vim.o.background = "dark"
vim.g.colors_name = "retro-bebox"

local hl = vim.api.nvim_set_hl

hl(0, "Normal", { fg = "#E8E8E8", bg = "#3A3A4A" })
hl(0, "NormalNC", { link = "Normal" })
hl(0, "NormalFloat", { fg = "#E8E8E8", bg = "#4B4B5A" })
hl(0, "FloatBorder", { fg = "#9999A1", bg = "#4B4B5A" })
hl(0, "FloatTitle", { fg = "#FFD800", bg = "#4B4B5A", bold = true })
hl(0, "ColorColumn", { bg = "#464655" })
hl(0, "Conceal", { fg = "#9B9BA2" })
hl(0, "Cursor", { fg = "#3A3A4A", bg = "#E8E8E8" })
hl(0, "lCursor", { link = "Cursor" })
hl(0, "TermCursor", { link = "Cursor" })
hl(0, "CursorLine", { bg = "#464655" })
hl(0, "CursorColumn", { link = "CursorLine" })
hl(0, "CursorLineNr", { fg = "#FFD800", bold = true })
hl(0, "LineNr", { fg = "#9B9BA2" })
hl(0, "SignColumn", { bg = "#3A3A4A" })
hl(0, "FoldColumn", { fg = "#9B9BA2" })
hl(0, "Folded", { fg = "#BEBEC2", bg = "#4B4B5A" })
hl(0, "EndOfBuffer", { fg = "#3A3A4A" })
hl(0, "NonText", { fg = "#9B9BA2" })
hl(0, "Whitespace", { fg = "#666672" })
hl(0, "SpecialKey", { fg = "#9B9BA2" })
hl(0, "Visual", { bg = "#716635" })
hl(0, "VisualNOS", { link = "Visual" })
hl(0, "MatchParen", { fg = "#FFD800", bg = "#595966", bold = true })
hl(0, "Pmenu", { fg = "#E8E8E8", bg = "#4B4B5A" })
hl(0, "PmenuSel", { fg = "#E8E8E8", bg = "#595966", bold = true })
hl(0, "PmenuSbar", { bg = "#4B4B5A" })
hl(0, "PmenuThumb", { bg = "#9999A1" })
hl(0, "PmenuKind", { fg = "#F5DF68" })
hl(0, "PmenuKindSel", { fg = "#F5DF68", bg = "#595966" })
hl(0, "PmenuExtra", { fg = "#9B9BA2" })
hl(0, "PmenuExtraSel", { fg = "#9B9BA2", bg = "#595966" })
hl(0, "WildMenu", { link = "PmenuSel" })
hl(0, "StatusLine", { fg = "#000000", bg = "#FFD800", bold = true })
hl(0, "StatusLineNC", { fg = "#BEBEC2", bg = "#4B4B5A" })
hl(0, "WinBar", { fg = "#BEBEC2", bg = "#3A3A4A" })
hl(0, "WinBarNC", { fg = "#9B9BA2", bg = "#3A3A4A" })
hl(0, "WinSeparator", { fg = "#9999A1" })
hl(0, "TabLine", { fg = "#BEBEC2", bg = "#4B4B5A" })
hl(0, "TabLineFill", { bg = "#3A3A4A" })
hl(0, "TabLineSel", { fg = "#000000", bg = "#FFD800", bold = true })
hl(0, "Search", { fg = "#E8E8E8", bg = "#7F6240" })
hl(0, "IncSearch", { fg = "#3A3A4A", bg = "#FFAB2E", bold = true })
hl(0, "CurSearch", { link = "IncSearch" })
hl(0, "Substitute", { fg = "#3A3A4A", bg = "#F1ADAD" })
hl(0, "QuickFixLine", { bg = "#595966", bold = true })
hl(0, "Directory", { fg = "#9CCF1B" })
hl(0, "Title", { fg = "#FFD800", bold = true })
hl(0, "Question", { fg = "#61D461" })
hl(0, "MoreMsg", { fg = "#61D461" })
hl(0, "ModeMsg", { fg = "#E8E8E8", bold = true })
hl(0, "MsgArea", { fg = "#E8E8E8", bg = "#3A3A4A" })
hl(0, "MsgSeparator", { fg = "#9999A1" })
hl(0, "WarningMsg", { fg = "#FFAB2E" })
hl(0, "ErrorMsg", { fg = "#F1ADAD" })
hl(0, "SpellBad", { sp = "#F1ADAD", undercurl = true })
hl(0, "SpellCap", { sp = "#FFAB2E", undercurl = true })
hl(0, "SpellLocal", { sp = "#FFD800", undercurl = true })
hl(0, "SpellRare", { sp = "#BDBDBD", undercurl = true })
hl(0, "Comment", { fg = "#BCBCBC", italic = true })
hl(0, "Constant", { fg = "#FFAB2E" })
hl(0, "String", { fg = "#61D461" })
hl(0, "Character", { fg = "#61D461" })
hl(0, "Number", { fg = "#FFAB2E" })
hl(0, "Boolean", { fg = "#FFAB2E" })
hl(0, "Float", { fg = "#FFAB2E" })
hl(0, "Identifier", { fg = "#E8E8E8" })
hl(0, "Function", { fg = "#9CCF1B" })
hl(0, "Statement", { fg = "#FFD800" })
hl(0, "Conditional", { fg = "#FFD800" })
hl(0, "Repeat", { fg = "#FFD800" })
hl(0, "Label", { fg = "#FFD800" })
hl(0, "Operator", { fg = "#C5C5C8" })
hl(0, "Keyword", { fg = "#FFD800" })
hl(0, "Exception", { fg = "#FFD800" })
hl(0, "PreProc", { fg = "#F6AC82" })
hl(0, "Include", { fg = "#FFD800" })
hl(0, "Define", { fg = "#F6AC82" })
hl(0, "Macro", { fg = "#F6AC82" })
hl(0, "PreCondit", { fg = "#F6AC82" })
hl(0, "Type", { fg = "#F5DF68" })
hl(0, "StorageClass", { fg = "#FFD800" })
hl(0, "Structure", { fg = "#F5DF68" })
hl(0, "Typedef", { fg = "#F5DF68" })
hl(0, "Special", { fg = "#F6AC82" })
hl(0, "SpecialChar", { fg = "#F6AC82" })
hl(0, "Tag", { fg = "#FFD800" })
hl(0, "Delimiter", { fg = "#C5C5C8" })
hl(0, "SpecialComment", { fg = "#BCBCBC", bold = true })
hl(0, "Debug", { fg = "#F1ADAD" })
hl(0, "Underlined", { fg = "#9CCF1B", underline = true })
hl(0, "Ignore", { fg = "#9B9BA2" })
hl(0, "Error", { fg = "#F1ADAD", bold = true })
hl(0, "Todo", { fg = "#3A3A4A", bg = "#FFAB2E", bold = true })
hl(0, "Added", { fg = "#61D461" })
hl(0, "Changed", { fg = "#FFAB2E" })
hl(0, "Removed", { fg = "#F1ADAD" })
hl(0, "DiffAdd", { bg = "#41564E" })
hl(0, "DiffChange", { bg = "#524847" })
hl(0, "DiffDelete", { bg = "#5B4F5C" })
hl(0, "DiffText", { bg = "#755C42", bold = true })
hl(0, "DiagnosticError", { fg = "#F1ADAD" })
hl(0, "DiagnosticWarn", { fg = "#FFAB2E" })
hl(0, "DiagnosticInfo", { fg = "#FFD800" })
hl(0, "DiagnosticHint", { fg = "#BDBDBD" })
hl(0, "DiagnosticOk", { fg = "#61D461" })
hl(0, "DiagnosticUnderlineError", { sp = "#F1ADAD", undercurl = true })
hl(0, "DiagnosticUnderlineWarn", { sp = "#FFAB2E", undercurl = true })
hl(0, "DiagnosticUnderlineInfo", { sp = "#FFD800", undercurl = true })
hl(0, "DiagnosticUnderlineHint", { sp = "#BDBDBD", undercurl = true })
hl(0, "DiagnosticUnderlineOk", { sp = "#61D461", undercurl = true })
hl(0, "DiagnosticVirtualTextError", { fg = "#F1ADAD", bg = "#504856" })
hl(0, "DiagnosticVirtualTextWarn", { fg = "#FFAB2E", bg = "#524847" })
hl(0, "DiagnosticVirtualTextInfo", { fg = "#FFD800", bg = "#524D41" })
hl(0, "DiagnosticVirtualTextHint", { fg = "#BDBDBD", bg = "#4A4A58" })
hl(0, "@variable", { fg = "#E8E8E8" })
hl(0, "@variable.builtin", { fg = "#F6AC82", italic = true })
hl(0, "@variable.parameter", { fg = "#E8E8E8" })
hl(0, "@variable.member", { fg = "#E8E8E8" })
hl(0, "@constant", { fg = "#FFAB2E" })
hl(0, "@constant.builtin", { fg = "#F6AC82" })
hl(0, "@constant.macro", { fg = "#F6AC82" })
hl(0, "@module", { fg = "#F5DF68" })
hl(0, "@label", { fg = "#FFD800" })
hl(0, "@string", { fg = "#61D461" })
hl(0, "@string.documentation", { fg = "#BCBCBC" })
hl(0, "@string.escape", { fg = "#F6AC82" })
hl(0, "@string.regexp", { fg = "#F6AC82" })
hl(0, "@string.special", { fg = "#F6AC82" })
hl(0, "@character", { fg = "#61D461" })
hl(0, "@character.special", { fg = "#F6AC82" })
hl(0, "@boolean", { fg = "#FFAB2E" })
hl(0, "@number", { fg = "#FFAB2E" })
hl(0, "@number.float", { fg = "#FFAB2E" })
hl(0, "@type", { fg = "#F5DF68" })
hl(0, "@type.builtin", { fg = "#F5DF68", italic = true })
hl(0, "@type.definition", { fg = "#F5DF68" })
hl(0, "@attribute", { fg = "#F6AC82" })
hl(0, "@attribute.builtin", { fg = "#F6AC82" })
hl(0, "@property", { fg = "#E8E8E8" })
hl(0, "@function", { fg = "#9CCF1B" })
hl(0, "@function.builtin", { fg = "#F6AC82" })
hl(0, "@function.macro", { fg = "#F6AC82" })
hl(0, "@function.method", { fg = "#9CCF1B" })
hl(0, "@constructor", { fg = "#F5DF68" })
hl(0, "@operator", { fg = "#C5C5C8" })
hl(0, "@keyword", { fg = "#FFD800" })
hl(0, "@keyword.function", { fg = "#FFD800" })
hl(0, "@keyword.operator", { fg = "#FFD800" })
hl(0, "@keyword.import", { fg = "#FFD800" })
hl(0, "@keyword.return", { fg = "#FFD800" })
hl(0, "@keyword.exception", { fg = "#FFD800" })
hl(0, "@punctuation.delimiter", { fg = "#C5C5C8" })
hl(0, "@punctuation.bracket", { fg = "#C5C5C8" })
hl(0, "@punctuation.special", { fg = "#F6AC82" })
hl(0, "@comment", { fg = "#BCBCBC", italic = true })
hl(0, "@comment.documentation", { fg = "#BCBCBC", italic = true })
hl(0, "@comment.error", { fg = "#3A3A4A", bg = "#F1ADAD", bold = true })
hl(0, "@comment.warning", { fg = "#3A3A4A", bg = "#FFAB2E", bold = true })
hl(0, "@comment.todo", { link = "Todo" })
hl(0, "@comment.note", { fg = "#3A3A4A", bg = "#FFD800", bold = true })
hl(0, "@tag", { fg = "#FFD800" })
hl(0, "@tag.builtin", { fg = "#FFD800" })
hl(0, "@tag.attribute", { fg = "#9CCF1B", italic = true })
hl(0, "@tag.delimiter", { fg = "#C5C5C8" })
hl(0, "@markup.strong", { fg = "#E8E8E8", bold = true })
hl(0, "@markup.italic", { fg = "#E8E8E8", italic = true })
hl(0, "@markup.strikethrough", { fg = "#BEBEC2", strikethrough = true })
hl(0, "@markup.underline", { fg = "#E8E8E8", underline = true })
hl(0, "@markup.quote", { fg = "#BEBEC2", italic = true })
hl(0, "@markup.math", { fg = "#FFAB2E" })
hl(0, "@markup.link", { fg = "#9CCF1B" })
hl(0, "@markup.link.label", { fg = "#FFD800" })
hl(0, "@markup.link.url", { fg = "#9CCF1B", underline = true })
hl(0, "@markup.raw", { fg = "#61D461" })
hl(0, "@markup.list", { fg = "#FFD800" })
hl(0, "@markup.list.checked", { fg = "#61D461" })
hl(0, "@markup.list.unchecked", { fg = "#BEBEC2" })
hl(0, "@diff.plus", { fg = "#61D461" })
hl(0, "@diff.minus", { fg = "#F1ADAD" })
hl(0, "@diff.delta", { fg = "#FFAB2E" })
hl(0, "@lsp.type.namespace", { link = "@module" })
hl(0, "@lsp.type.class", { link = "@type" })
hl(0, "@lsp.type.enum", { link = "@type" })
hl(0, "@lsp.type.interface", { link = "@type" })
hl(0, "@lsp.type.struct", { link = "@type" })
hl(0, "@lsp.type.parameter", { link = "@variable.parameter" })
hl(0, "@lsp.type.property", { link = "@property" })
hl(0, "@lsp.type.enumMember", { link = "@constant" })
hl(0, "@lsp.type.method", { link = "@function.method" })
hl(0, "MiniIconsAzure", { fg = "#9CCF1B" })
hl(0, "MiniIconsBlue", { fg = "#FFD800" })
hl(0, "MiniIconsCyan", { fg = "#F5DF68" })
hl(0, "MiniIconsGreen", { fg = "#61D461" })
hl(0, "MiniIconsGrey", { fg = "#BEBEC2" })
hl(0, "MiniIconsOrange", { fg = "#FFAB2E" })
hl(0, "MiniIconsPurple", { fg = "#F6AC82" })
hl(0, "MiniIconsRed", { fg = "#F1ADAD" })
hl(0, "MiniIconsYellow", { fg = "#FFAB2E" })
hl(0, "MiniFilesTitleFocused", { fg = "#FFD800", bg = "#4B4B5A", bold = true })
hl(0, "MiniFilesDirectory", { fg = "#9CCF1B" })
hl(0, "MiniFilesFile", { fg = "#E8E8E8" })
hl(0, "MiniFilesCursorLine", { bg = "#595966" })
hl(0, "MiniPickMatchCurrent", { bg = "#595966", bold = true })
hl(0, "MiniPickMatchRanges", { fg = "#FFD800", bold = true })
hl(0, "MiniPickPrompt", { fg = "#FFD800", bold = true })
hl(0, "MiniPickBorderText", { fg = "#FFD800" })
hl(0, "MiniClueDescGroup", { fg = "#F5DF68" })
hl(0, "MiniClueDescSingle", { fg = "#E8E8E8" })
hl(0, "MiniClueNextKey", { fg = "#FFD800", bold = true })
hl(0, "MiniClueTitle", { fg = "#FFD800", bg = "#4B4B5A", bold = true })
hl(0, "RenderMarkdownCode", { bg = "#4B4B5A" })
hl(0, "RenderMarkdownCodeInline", { fg = "#61D461", bg = "#4B4B5A" })
hl(0, "RenderMarkdownBullet", { fg = "#FFD800" })
hl(0, "RenderMarkdownQuote", { fg = "#BEBEC2" })
hl(0, "RenderMarkdownDash", { fg = "#9999A1" })
hl(0, "RenderMarkdownTableHead", { fg = "#F5DF68", bold = true })
hl(0, "RenderMarkdownTableRow", { fg = "#BEBEC2" })
hl(0, "RenderMarkdownLink", { fg = "#9CCF1B" })
hl(0, "RenderMarkdownChecked", { fg = "#61D461" })
hl(0, "RenderMarkdownUnchecked", { fg = "#BEBEC2" })
hl(0, "@markup.heading.1", { fg = "#FFD800", bold = true })
hl(0, "RenderMarkdownH1", { fg = "#FFD800", bold = true })
hl(0, "RenderMarkdownH1Bg", { fg = "#FFD800", bg = "#58523F", bold = true })
hl(0, "@markup.heading.2", { fg = "#9CCF1B", bold = true })
hl(0, "RenderMarkdownH2", { fg = "#9CCF1B", bold = true })
hl(0, "RenderMarkdownH2Bg", { fg = "#9CCF1B", bg = "#495043", bold = true })
hl(0, "@markup.heading.3", { fg = "#61D461", bold = true })
hl(0, "RenderMarkdownH3", { fg = "#61D461", bold = true })
hl(0, "RenderMarkdownH3Bg", { fg = "#61D461", bg = "#40514D", bold = true })
hl(0, "@markup.heading.4", { fg = "#FFAB2E", bold = true })
hl(0, "RenderMarkdownH4", { fg = "#FFAB2E", bold = true })
hl(0, "RenderMarkdownH4Bg", { fg = "#FFAB2E", bg = "#584B46", bold = true })
hl(0, "@markup.heading.5", { fg = "#F5DF68", bold = true })
hl(0, "RenderMarkdownH5", { fg = "#F5DF68", bold = true })
hl(0, "RenderMarkdownH5Bg", { fg = "#F5DF68", bg = "#56534E", bold = true })
hl(0, "@markup.heading.6", { fg = "#F6AC82", bold = true })
hl(0, "RenderMarkdownH6", { fg = "#F6AC82", bold = true })
hl(0, "RenderMarkdownH6Bg", { fg = "#F6AC82", bg = "#564B52", bold = true })

vim.g.terminal_color_0 = "#666672"
vim.g.terminal_color_1 = "#F1ADAD"
vim.g.terminal_color_2 = "#61D461"
vim.g.terminal_color_3 = "#FFAB2E"
vim.g.terminal_color_4 = "#FFD800"
vim.g.terminal_color_5 = "#F6AC82"
vim.g.terminal_color_6 = "#FFD800"
vim.g.terminal_color_7 = "#BEBEC2"
vim.g.terminal_color_8 = "#888891"
vim.g.terminal_color_9 = "#F4BDBD"
vim.g.terminal_color_10 = "#81DD81"
vim.g.terminal_color_11 = "#FFBC58"
vim.g.terminal_color_12 = "#FFE033"
vim.g.terminal_color_13 = "#F8BD9B"
vim.g.terminal_color_14 = "#FFE033"
vim.g.terminal_color_15 = "#E8E8E8"
