-- retro-miami - erzeugt von retro-coding-themes, nicht von Hand aendern.
-- Quelle: src/retro_coding_themes/data/miami.json, Ableitung in derive.py.

vim.cmd("highlight clear")
if vim.fn.exists("syntax_on") == 1 then
  vim.cmd("syntax reset")
end

vim.o.background = "dark"
vim.g.colors_name = "retro-miami"

local hl = vim.api.nvim_set_hl

hl(0, "Normal", { fg = "#FFE8E0", bg = "#0B2F3F" })
hl(0, "NormalNC", { link = "Normal" })
hl(0, "NormalFloat", { fg = "#FFE8E0", bg = "#23424F" })
hl(0, "FloatBorder", { fg = "#7B8D94", bg = "#23424F" })
hl(0, "FloatTitle", { fg = "#FFA06A", bg = "#23424F", bold = true })
hl(0, "ColorColumn", { bg = "#1C3C4A" })
hl(0, "Conceal", { fg = "#818A8E" })
hl(0, "Cursor", { fg = "#0B2F3F", bg = "#FFE8E0" })
hl(0, "lCursor", { link = "Cursor" })
hl(0, "TermCursor", { link = "Cursor" })
hl(0, "CursorLine", { bg = "#1C3C4A" })
hl(0, "CursorColumn", { link = "CursorLine" })
hl(0, "CursorLineNr", { fg = "#FFA06A", bold = true })
hl(0, "LineNr", { fg = "#818A8E" })
hl(0, "SignColumn", { bg = "#0B2F3F" })
hl(0, "FoldColumn", { fg = "#818A8E" })
hl(0, "Folded", { fg = "#ADAAAB", bg = "#23424F" })
hl(0, "EndOfBuffer", { fg = "#0B2F3F" })
hl(0, "NonText", { fg = "#818A8E" })
hl(0, "Whitespace", { fg = "#485D67" })
hl(0, "SpecialKey", { fg = "#818A8E" })
hl(0, "Visual", { bg = "#60574E" })
hl(0, "VisualNOS", { link = "Visual" })
hl(0, "MatchParen", { fg = "#FFA06A", bg = "#37505C", bold = true })
hl(0, "Pmenu", { fg = "#FFE8E0", bg = "#23424F" })
hl(0, "PmenuSel", { fg = "#FFE8E0", bg = "#37505C", bold = true })
hl(0, "PmenuSbar", { bg = "#23424F" })
hl(0, "PmenuThumb", { bg = "#7B8D94" })
hl(0, "PmenuKind", { fg = "#20BCC0" })
hl(0, "PmenuKindSel", { fg = "#20BCC0", bg = "#37505C" })
hl(0, "PmenuExtra", { fg = "#818A8E" })
hl(0, "PmenuExtraSel", { fg = "#818A8E", bg = "#37505C" })
hl(0, "WildMenu", { link = "PmenuSel" })
hl(0, "StatusLine", { fg = "#000000", bg = "#FF6FAB", bold = true })
hl(0, "StatusLineNC", { fg = "#ADAAAB", bg = "#23424F" })
hl(0, "WinBar", { fg = "#ADAAAB", bg = "#0B2F3F" })
hl(0, "WinBarNC", { fg = "#818A8E", bg = "#0B2F3F" })
hl(0, "WinSeparator", { fg = "#7B8D94" })
hl(0, "TabLine", { fg = "#ADAAAB", bg = "#23424F" })
hl(0, "TabLineFill", { bg = "#0B2F3F" })
hl(0, "TabLineSel", { fg = "#000000", bg = "#FF6FAB", bold = true })
hl(0, "Search", { fg = "#FFE8E0", bg = "#606A4E" })
hl(0, "IncSearch", { fg = "#0B2F3F", bg = "#FFD76B", bold = true })
hl(0, "CurSearch", { link = "IncSearch" })
hl(0, "Substitute", { fg = "#0B2F3F", bg = "#F08BAB" })
hl(0, "QuickFixLine", { bg = "#37505C", bold = true })
hl(0, "Directory", { fg = "#FF7EB4" })
hl(0, "Title", { fg = "#FFA06A", bold = true })
hl(0, "Question", { fg = "#4ECDA8" })
hl(0, "MoreMsg", { fg = "#4ECDA8" })
hl(0, "ModeMsg", { fg = "#FFE8E0", bold = true })
hl(0, "MsgArea", { fg = "#FFE8E0", bg = "#0B2F3F" })
hl(0, "MsgSeparator", { fg = "#7B8D94" })
hl(0, "WarningMsg", { fg = "#FFD76B" })
hl(0, "ErrorMsg", { fg = "#F08BAB" })
hl(0, "SpellBad", { sp = "#F08BAB", undercurl = true })
hl(0, "SpellCap", { sp = "#FFD76B", undercurl = true })
hl(0, "SpellLocal", { sp = "#FF7EB4", undercurl = true })
hl(0, "SpellRare", { sp = "#6DC9C9", undercurl = true })
hl(0, "Comment", { fg = "#8FD0CE", italic = true })
hl(0, "Constant", { fg = "#FFD76B" })
hl(0, "String", { fg = "#4ECDA8" })
hl(0, "Character", { fg = "#4ECDA8" })
hl(0, "Number", { fg = "#FFD76B" })
hl(0, "Boolean", { fg = "#FFD76B" })
hl(0, "Float", { fg = "#FFD76B" })
hl(0, "Identifier", { fg = "#FFE8E0" })
hl(0, "Function", { fg = "#FF7EB4" })
hl(0, "Statement", { fg = "#FFA06A" })
hl(0, "Conditional", { fg = "#FFA06A" })
hl(0, "Repeat", { fg = "#FFA06A" })
hl(0, "Label", { fg = "#FFA06A" })
hl(0, "Operator", { fg = "#CEC3C0" })
hl(0, "Keyword", { fg = "#FFA06A" })
hl(0, "Exception", { fg = "#FFA06A" })
hl(0, "PreProc", { fg = "#FF888A" })
hl(0, "Include", { fg = "#FFA06A" })
hl(0, "Define", { fg = "#FF888A" })
hl(0, "Macro", { fg = "#FF888A" })
hl(0, "PreCondit", { fg = "#FF888A" })
hl(0, "Type", { fg = "#20BCC0" })
hl(0, "StorageClass", { fg = "#FFA06A" })
hl(0, "Structure", { fg = "#20BCC0" })
hl(0, "Typedef", { fg = "#20BCC0" })
hl(0, "Special", { fg = "#FF888A" })
hl(0, "SpecialChar", { fg = "#FF888A" })
hl(0, "Tag", { fg = "#FFA06A" })
hl(0, "Delimiter", { fg = "#CEC3C0" })
hl(0, "SpecialComment", { fg = "#8FD0CE", bold = true })
hl(0, "Debug", { fg = "#F08BAB" })
hl(0, "Underlined", { fg = "#FF7EB4", underline = true })
hl(0, "Ignore", { fg = "#818A8E" })
hl(0, "Error", { fg = "#F08BAB", bold = true })
hl(0, "Todo", { fg = "#0B2F3F", bg = "#FFD76B", bold = true })
hl(0, "Added", { fg = "#4ECDA8" })
hl(0, "Changed", { fg = "#FFD76B" })
hl(0, "Removed", { fg = "#F08BAB" })
hl(0, "DiffAdd", { bg = "#174B52" })
hl(0, "DiffChange", { bg = "#284344" })
hl(0, "DiffDelete", { bg = "#344052" })
hl(0, "DiffText", { bg = "#54614C", bold = true })
hl(0, "DiagnosticError", { fg = "#F08BAB" })
hl(0, "DiagnosticWarn", { fg = "#FFD76B" })
hl(0, "DiagnosticInfo", { fg = "#FF7EB4" })
hl(0, "DiagnosticHint", { fg = "#6DC9C9" })
hl(0, "DiagnosticOk", { fg = "#4ECDA8" })
hl(0, "DiagnosticUnderlineError", { sp = "#F08BAB", undercurl = true })
hl(0, "DiagnosticUnderlineWarn", { sp = "#FFD76B", undercurl = true })
hl(0, "DiagnosticUnderlineInfo", { sp = "#FF7EB4", undercurl = true })
hl(0, "DiagnosticUnderlineHint", { sp = "#6DC9C9", undercurl = true })
hl(0, "DiagnosticUnderlineOk", { sp = "#4ECDA8", undercurl = true })
hl(0, "DiagnosticVirtualTextError", { fg = "#F08BAB", bg = "#263A4C" })
hl(0, "DiagnosticVirtualTextWarn", { fg = "#FFD76B", bg = "#284344" })
hl(0, "DiagnosticVirtualTextInfo", { fg = "#FF7EB4", bg = "#28384D" })
hl(0, "DiagnosticVirtualTextHint", { fg = "#6DC9C9", bg = "#174150" })
hl(0, "@variable", { fg = "#FFE8E0" })
hl(0, "@variable.builtin", { fg = "#FF888A", italic = true })
hl(0, "@variable.parameter", { fg = "#FFE8E0" })
hl(0, "@variable.member", { fg = "#FFE8E0" })
hl(0, "@constant", { fg = "#FFD76B" })
hl(0, "@constant.builtin", { fg = "#FF888A" })
hl(0, "@constant.macro", { fg = "#FF888A" })
hl(0, "@module", { fg = "#20BCC0" })
hl(0, "@label", { fg = "#FFA06A" })
hl(0, "@string", { fg = "#4ECDA8" })
hl(0, "@string.documentation", { fg = "#8FD0CE" })
hl(0, "@string.escape", { fg = "#FF888A" })
hl(0, "@string.regexp", { fg = "#FF888A" })
hl(0, "@string.special", { fg = "#FF888A" })
hl(0, "@character", { fg = "#4ECDA8" })
hl(0, "@character.special", { fg = "#FF888A" })
hl(0, "@boolean", { fg = "#FFD76B" })
hl(0, "@number", { fg = "#FFD76B" })
hl(0, "@number.float", { fg = "#FFD76B" })
hl(0, "@type", { fg = "#20BCC0" })
hl(0, "@type.builtin", { fg = "#20BCC0", italic = true })
hl(0, "@type.definition", { fg = "#20BCC0" })
hl(0, "@attribute", { fg = "#FF888A" })
hl(0, "@attribute.builtin", { fg = "#FF888A" })
hl(0, "@property", { fg = "#FFE8E0" })
hl(0, "@function", { fg = "#FF7EB4" })
hl(0, "@function.builtin", { fg = "#FF888A" })
hl(0, "@function.macro", { fg = "#FF888A" })
hl(0, "@function.method", { fg = "#FF7EB4" })
hl(0, "@constructor", { fg = "#20BCC0" })
hl(0, "@operator", { fg = "#CEC3C0" })
hl(0, "@keyword", { fg = "#FFA06A" })
hl(0, "@keyword.function", { fg = "#FFA06A" })
hl(0, "@keyword.operator", { fg = "#FFA06A" })
hl(0, "@keyword.import", { fg = "#FFA06A" })
hl(0, "@keyword.return", { fg = "#FFA06A" })
hl(0, "@keyword.exception", { fg = "#FFA06A" })
hl(0, "@punctuation.delimiter", { fg = "#CEC3C0" })
hl(0, "@punctuation.bracket", { fg = "#CEC3C0" })
hl(0, "@punctuation.special", { fg = "#FF888A" })
hl(0, "@comment", { fg = "#8FD0CE", italic = true })
hl(0, "@comment.documentation", { fg = "#8FD0CE", italic = true })
hl(0, "@comment.error", { fg = "#0B2F3F", bg = "#F08BAB", bold = true })
hl(0, "@comment.warning", { fg = "#0B2F3F", bg = "#FFD76B", bold = true })
hl(0, "@comment.todo", { link = "Todo" })
hl(0, "@comment.note", { fg = "#0B2F3F", bg = "#FF7EB4", bold = true })
hl(0, "@tag", { fg = "#FFA06A" })
hl(0, "@tag.builtin", { fg = "#FFA06A" })
hl(0, "@tag.attribute", { fg = "#FF7EB4", italic = true })
hl(0, "@tag.delimiter", { fg = "#CEC3C0" })
hl(0, "@markup.strong", { fg = "#FFE8E0", bold = true })
hl(0, "@markup.italic", { fg = "#FFE8E0", italic = true })
hl(0, "@markup.strikethrough", { fg = "#ADAAAB", strikethrough = true })
hl(0, "@markup.underline", { fg = "#FFE8E0", underline = true })
hl(0, "@markup.quote", { fg = "#ADAAAB", italic = true })
hl(0, "@markup.math", { fg = "#FFD76B" })
hl(0, "@markup.link", { fg = "#FF7EB4" })
hl(0, "@markup.link.label", { fg = "#FFA06A" })
hl(0, "@markup.link.url", { fg = "#FF7EB4", underline = true })
hl(0, "@markup.raw", { fg = "#4ECDA8" })
hl(0, "@markup.list", { fg = "#FFA06A" })
hl(0, "@markup.list.checked", { fg = "#4ECDA8" })
hl(0, "@markup.list.unchecked", { fg = "#ADAAAB" })
hl(0, "@diff.plus", { fg = "#4ECDA8" })
hl(0, "@diff.minus", { fg = "#F08BAB" })
hl(0, "@diff.delta", { fg = "#FFD76B" })
hl(0, "@lsp.type.namespace", { link = "@module" })
hl(0, "@lsp.type.class", { link = "@type" })
hl(0, "@lsp.type.enum", { link = "@type" })
hl(0, "@lsp.type.interface", { link = "@type" })
hl(0, "@lsp.type.struct", { link = "@type" })
hl(0, "@lsp.type.parameter", { link = "@variable.parameter" })
hl(0, "@lsp.type.property", { link = "@property" })
hl(0, "@lsp.type.enumMember", { link = "@constant" })
hl(0, "@lsp.type.method", { link = "@function.method" })
hl(0, "MiniIconsAzure", { fg = "#FF7EB4" })
hl(0, "MiniIconsBlue", { fg = "#FF7EB4" })
hl(0, "MiniIconsCyan", { fg = "#20BCC0" })
hl(0, "MiniIconsGreen", { fg = "#4ECDA8" })
hl(0, "MiniIconsGrey", { fg = "#ADAAAB" })
hl(0, "MiniIconsOrange", { fg = "#FFD76B" })
hl(0, "MiniIconsPurple", { fg = "#FF888A" })
hl(0, "MiniIconsRed", { fg = "#F08BAB" })
hl(0, "MiniIconsYellow", { fg = "#FFD76B" })
hl(0, "MiniFilesTitleFocused", { fg = "#FFA06A", bg = "#23424F", bold = true })
hl(0, "MiniFilesDirectory", { fg = "#FF7EB4" })
hl(0, "MiniFilesFile", { fg = "#FFE8E0" })
hl(0, "MiniFilesCursorLine", { bg = "#37505C" })
hl(0, "MiniPickMatchCurrent", { bg = "#37505C", bold = true })
hl(0, "MiniPickMatchRanges", { fg = "#FFA06A", bold = true })
hl(0, "MiniPickPrompt", { fg = "#FFA06A", bold = true })
hl(0, "MiniPickBorderText", { fg = "#FFA06A" })
hl(0, "MiniClueDescGroup", { fg = "#20BCC0" })
hl(0, "MiniClueDescSingle", { fg = "#FFE8E0" })
hl(0, "MiniClueNextKey", { fg = "#FFA06A", bold = true })
hl(0, "MiniClueTitle", { fg = "#FFA06A", bg = "#23424F", bold = true })
hl(0, "RenderMarkdownCode", { bg = "#23424F" })
hl(0, "RenderMarkdownCodeInline", { fg = "#4ECDA8", bg = "#23424F" })
hl(0, "RenderMarkdownBullet", { fg = "#FFA06A" })
hl(0, "RenderMarkdownQuote", { fg = "#ADAAAB" })
hl(0, "RenderMarkdownDash", { fg = "#7B8D94" })
hl(0, "RenderMarkdownTableHead", { fg = "#20BCC0", bold = true })
hl(0, "RenderMarkdownTableRow", { fg = "#ADAAAB" })
hl(0, "RenderMarkdownLink", { fg = "#FF7EB4" })
hl(0, "RenderMarkdownChecked", { fg = "#4ECDA8" })
hl(0, "RenderMarkdownUnchecked", { fg = "#ADAAAB" })
hl(0, "@markup.heading.1", { fg = "#FFA06A", bold = true })
hl(0, "RenderMarkdownH1", { fg = "#FFA06A", bold = true })
hl(0, "RenderMarkdownH1Bg", { fg = "#FFA06A", bg = "#304045", bold = true })
hl(0, "@markup.heading.2", { fg = "#FF7EB4", bold = true })
hl(0, "RenderMarkdownH2", { fg = "#FF7EB4", bold = true })
hl(0, "RenderMarkdownH2Bg", { fg = "#FF7EB4", bg = "#303B51", bold = true })
hl(0, "@markup.heading.3", { fg = "#4ECDA8", bold = true })
hl(0, "RenderMarkdownH3", { fg = "#4ECDA8", bold = true })
hl(0, "RenderMarkdownH3Bg", { fg = "#4ECDA8", bg = "#15474F", bold = true })
hl(0, "@markup.heading.4", { fg = "#FFD76B", bold = true })
hl(0, "RenderMarkdownH4", { fg = "#FFD76B", bold = true })
hl(0, "RenderMarkdownH4Bg", { fg = "#FFD76B", bg = "#304846", bold = true })
hl(0, "@markup.heading.5", { fg = "#20BCC0", bold = true })
hl(0, "RenderMarkdownH5", { fg = "#20BCC0", bold = true })
hl(0, "RenderMarkdownH5Bg", { fg = "#20BCC0", bg = "#0E4452", bold = true })
hl(0, "@markup.heading.6", { fg = "#FF888A", bold = true })
hl(0, "RenderMarkdownH6", { fg = "#FF888A", bold = true })
hl(0, "RenderMarkdownH6Bg", { fg = "#FF888A", bg = "#303C4A", bold = true })

vim.g.terminal_color_0 = "#485D67"
vim.g.terminal_color_1 = "#F08BAB"
vim.g.terminal_color_2 = "#4ECDA8"
vim.g.terminal_color_3 = "#FFD76B"
vim.g.terminal_color_4 = "#FF7EB4"
vim.g.terminal_color_5 = "#FF888A"
vim.g.terminal_color_6 = "#FFA06A"
vim.g.terminal_color_7 = "#ADAAAB"
vim.g.terminal_color_8 = "#798287"
vim.g.terminal_color_9 = "#F3A2BC"
vim.g.terminal_color_10 = "#71D7B9"
vim.g.terminal_color_11 = "#FFDF89"
vim.g.terminal_color_12 = "#FF98C3"
vim.g.terminal_color_13 = "#FFA0A1"
vim.g.terminal_color_14 = "#FFB388"
vim.g.terminal_color_15 = "#FFE8E0"
