-- retro-motif - erzeugt von retro-coding-themes, nicht von Hand aendern.
-- Quelle: src/retro_coding_themes/data/motif.json, Ableitung in derive.py.

vim.cmd("highlight clear")
if vim.fn.exists("syntax_on") == 1 then
  vim.cmd("syntax reset")
end

vim.o.background = "dark"
vim.g.colors_name = "retro-motif"

local hl = vim.api.nvim_set_hl

hl(0, "Normal", { fg = "#D8D0C8", bg = "#2A3641" })
hl(0, "NormalNC", { link = "Normal" })
hl(0, "NormalFloat", { fg = "#D8D0C8", bg = "#3B454E" })
hl(0, "FloatBorder", { fg = "#8B9094", bg = "#3B454E" })
hl(0, "FloatTitle", { fg = "#D4A87D", bg = "#3B454E", bold = true })
hl(0, "ColorColumn", { bg = "#36414A" })
hl(0, "Conceal", { fg = "#8D8F92" })
hl(0, "Cursor", { fg = "#2A3641", bg = "#D8D0C8" })
hl(0, "lCursor", { link = "Cursor" })
hl(0, "TermCursor", { link = "Cursor" })
hl(0, "CursorLine", { bg = "#36414A" })
hl(0, "CursorColumn", { link = "CursorLine" })
hl(0, "CursorLineNr", { fg = "#D4A87D", bold = true })
hl(0, "LineNr", { fg = "#8D8F92" })
hl(0, "SignColumn", { bg = "#2A3641" })
hl(0, "FoldColumn", { fg = "#8D8F92" })
hl(0, "Folded", { fg = "#B2B1B0", bg = "#3B454E" })
hl(0, "EndOfBuffer", { fg = "#2A3641" })
hl(0, "NonText", { fg = "#8D8F92" })
hl(0, "Whitespace", { fg = "#565C63" })
hl(0, "SpecialKey", { fg = "#8D8F92" })
hl(0, "Visual", { bg = "#58524B" })
hl(0, "VisualNOS", { link = "Visual" })
hl(0, "MatchParen", { fg = "#D4A87D", bg = "#495259", bold = true })
hl(0, "Pmenu", { fg = "#D8D0C8", bg = "#3B454E" })
hl(0, "PmenuSel", { fg = "#D8D0C8", bg = "#495259", bold = true })
hl(0, "PmenuSbar", { bg = "#3B454E" })
hl(0, "PmenuThumb", { bg = "#8B9094" })
hl(0, "PmenuKind", { fg = "#E69CC1" })
hl(0, "PmenuKindSel", { fg = "#E69CC1", bg = "#495259" })
hl(0, "PmenuExtra", { fg = "#8D8F92" })
hl(0, "PmenuExtraSel", { fg = "#8D8F92", bg = "#495259" })
hl(0, "WildMenu", { link = "PmenuSel" })
hl(0, "StatusLine", { fg = "#000000", bg = "#CC9966", bold = true })
hl(0, "StatusLineNC", { fg = "#B2B1B0", bg = "#3B454E" })
hl(0, "WinBar", { fg = "#B2B1B0", bg = "#2A3641" })
hl(0, "WinBarNC", { fg = "#8D8F92", bg = "#2A3641" })
hl(0, "WinSeparator", { fg = "#8B9094" })
hl(0, "TabLine", { fg = "#B2B1B0", bg = "#3B454E" })
hl(0, "TabLineFill", { bg = "#2A3641" })
hl(0, "TabLineSel", { fg = "#000000", bg = "#CC9966", bold = true })
hl(0, "Search", { fg = "#D8D0C8", bg = "#606F51" })
hl(0, "IncSearch", { fg = "#2A3641", bg = "#C4D870", bold = true })
hl(0, "CurSearch", { link = "IncSearch" })
hl(0, "Substitute", { fg = "#2A3641", bg = "#E3A298" })
hl(0, "QuickFixLine", { bg = "#495259", bold = true })
hl(0, "Directory", { fg = "#A9B789" })
hl(0, "Title", { fg = "#D4A87D", bold = true })
hl(0, "Question", { fg = "#81C08E" })
hl(0, "MoreMsg", { fg = "#81C08E" })
hl(0, "ModeMsg", { fg = "#D8D0C8", bold = true })
hl(0, "MsgArea", { fg = "#D8D0C8", bg = "#2A3641" })
hl(0, "MsgSeparator", { fg = "#8B9094" })
hl(0, "WarningMsg", { fg = "#CEAE4C" })
hl(0, "ErrorMsg", { fg = "#E3A298" })
hl(0, "SpellBad", { sp = "#E3A298", undercurl = true })
hl(0, "SpellCap", { sp = "#CEAE4C", undercurl = true })
hl(0, "SpellLocal", { sp = "#D4A87D", undercurl = true })
hl(0, "SpellRare", { sp = "#A8B4B9", undercurl = true })
hl(0, "Comment", { fg = "#AAB2B5", italic = true })
hl(0, "Constant", { fg = "#C4D870" })
hl(0, "String", { fg = "#CEAE4C" })
hl(0, "Character", { fg = "#CEAE4C" })
hl(0, "Number", { fg = "#C4D870" })
hl(0, "Boolean", { fg = "#C4D870" })
hl(0, "Float", { fg = "#C4D870" })
hl(0, "Identifier", { fg = "#D8D0C8" })
hl(0, "Function", { fg = "#A9B789" })
hl(0, "Statement", { fg = "#DCA873" })
hl(0, "Conditional", { fg = "#DCA873" })
hl(0, "Repeat", { fg = "#DCA873" })
hl(0, "Label", { fg = "#DCA873" })
hl(0, "Operator", { fg = "#B5B1AD" })
hl(0, "Keyword", { fg = "#DCA873" })
hl(0, "Exception", { fg = "#DCA873" })
hl(0, "PreProc", { fg = "#7DD47D" })
hl(0, "Include", { fg = "#DCA873" })
hl(0, "Define", { fg = "#7DD47D" })
hl(0, "Macro", { fg = "#7DD47D" })
hl(0, "PreCondit", { fg = "#7DD47D" })
hl(0, "Type", { fg = "#E69CC1" })
hl(0, "StorageClass", { fg = "#DCA873" })
hl(0, "Structure", { fg = "#E69CC1" })
hl(0, "Typedef", { fg = "#E69CC1" })
hl(0, "Special", { fg = "#7DD47D" })
hl(0, "SpecialChar", { fg = "#7DD47D" })
hl(0, "Tag", { fg = "#DCA873" })
hl(0, "Delimiter", { fg = "#B5B1AD" })
hl(0, "SpecialComment", { fg = "#AAB2B5", bold = true })
hl(0, "Debug", { fg = "#E3A298" })
hl(0, "Underlined", { fg = "#A9B789", underline = true })
hl(0, "Ignore", { fg = "#8D8F92" })
hl(0, "Error", { fg = "#E3A298", bold = true })
hl(0, "Todo", { fg = "#2A3641", bg = "#C4D870", bold = true })
hl(0, "Added", { fg = "#81C08E" })
hl(0, "Changed", { fg = "#CEAE4C" })
hl(0, "Removed", { fg = "#E3A298" })
hl(0, "DiffAdd", { bg = "#3A4F4F" })
hl(0, "DiffChange", { bg = "#3E4442" })
hl(0, "DiffDelete", { bg = "#4B4951" })
hl(0, "DiffText", { bg = "#5B5A44", bold = true })
hl(0, "DiagnosticError", { fg = "#E3A298" })
hl(0, "DiagnosticWarn", { fg = "#CEAE4C" })
hl(0, "DiagnosticInfo", { fg = "#D4A87D" })
hl(0, "DiagnosticHint", { fg = "#A8B4B9" })
hl(0, "DiagnosticOk", { fg = "#81C08E" })
hl(0, "DiagnosticUnderlineError", { sp = "#E3A298", undercurl = true })
hl(0, "DiagnosticUnderlineWarn", { sp = "#CEAE4C", undercurl = true })
hl(0, "DiagnosticUnderlineInfo", { sp = "#D4A87D", undercurl = true })
hl(0, "DiagnosticUnderlineHint", { sp = "#A8B4B9", undercurl = true })
hl(0, "DiagnosticUnderlineOk", { sp = "#81C08E", undercurl = true })
hl(0, "DiagnosticVirtualTextError", { fg = "#E3A298", bg = "#40434B" })
hl(0, "DiagnosticVirtualTextWarn", { fg = "#CEAE4C", bg = "#3E4442" })
hl(0, "DiagnosticVirtualTextInfo", { fg = "#D4A87D", bg = "#3E4448" })
hl(0, "DiagnosticVirtualTextHint", { fg = "#A8B4B9", bg = "#39454F" })
hl(0, "@variable", { fg = "#D8D0C8" })
hl(0, "@variable.builtin", { fg = "#7DD47D", italic = true })
hl(0, "@variable.parameter", { fg = "#D8D0C8" })
hl(0, "@variable.member", { fg = "#D8D0C8" })
hl(0, "@constant", { fg = "#C4D870" })
hl(0, "@constant.builtin", { fg = "#7DD47D" })
hl(0, "@constant.macro", { fg = "#7DD47D" })
hl(0, "@module", { fg = "#E69CC1" })
hl(0, "@label", { fg = "#DCA873" })
hl(0, "@string", { fg = "#CEAE4C" })
hl(0, "@string.documentation", { fg = "#AAB2B5" })
hl(0, "@string.escape", { fg = "#7DD47D" })
hl(0, "@string.regexp", { fg = "#7DD47D" })
hl(0, "@string.special", { fg = "#7DD47D" })
hl(0, "@character", { fg = "#CEAE4C" })
hl(0, "@character.special", { fg = "#7DD47D" })
hl(0, "@boolean", { fg = "#C4D870" })
hl(0, "@number", { fg = "#C4D870" })
hl(0, "@number.float", { fg = "#C4D870" })
hl(0, "@type", { fg = "#E69CC1" })
hl(0, "@type.builtin", { fg = "#E69CC1", italic = true })
hl(0, "@type.definition", { fg = "#E69CC1" })
hl(0, "@attribute", { fg = "#7DD47D" })
hl(0, "@attribute.builtin", { fg = "#7DD47D" })
hl(0, "@property", { fg = "#D8D0C8" })
hl(0, "@function", { fg = "#A9B789" })
hl(0, "@function.builtin", { fg = "#7DD47D" })
hl(0, "@function.macro", { fg = "#7DD47D" })
hl(0, "@function.method", { fg = "#A9B789" })
hl(0, "@constructor", { fg = "#E69CC1" })
hl(0, "@operator", { fg = "#B5B1AD" })
hl(0, "@keyword", { fg = "#DCA873" })
hl(0, "@keyword.function", { fg = "#DCA873" })
hl(0, "@keyword.operator", { fg = "#DCA873" })
hl(0, "@keyword.import", { fg = "#DCA873" })
hl(0, "@keyword.return", { fg = "#DCA873" })
hl(0, "@keyword.exception", { fg = "#DCA873" })
hl(0, "@punctuation.delimiter", { fg = "#B5B1AD" })
hl(0, "@punctuation.bracket", { fg = "#B5B1AD" })
hl(0, "@punctuation.special", { fg = "#7DD47D" })
hl(0, "@comment", { fg = "#AAB2B5", italic = true })
hl(0, "@comment.documentation", { fg = "#AAB2B5", italic = true })
hl(0, "@comment.error", { fg = "#2A3641", bg = "#E3A298", bold = true })
hl(0, "@comment.warning", { fg = "#2A3641", bg = "#CEAE4C", bold = true })
hl(0, "@comment.todo", { link = "Todo" })
hl(0, "@comment.note", { fg = "#2A3641", bg = "#D4A87D", bold = true })
hl(0, "@tag", { fg = "#DCA873" })
hl(0, "@tag.builtin", { fg = "#DCA873" })
hl(0, "@tag.attribute", { fg = "#A9B789", italic = true })
hl(0, "@tag.delimiter", { fg = "#B5B1AD" })
hl(0, "@markup.strong", { fg = "#D8D0C8", bold = true })
hl(0, "@markup.italic", { fg = "#D8D0C8", italic = true })
hl(0, "@markup.strikethrough", { fg = "#B2B1B0", strikethrough = true })
hl(0, "@markup.underline", { fg = "#D8D0C8", underline = true })
hl(0, "@markup.quote", { fg = "#B2B1B0", italic = true })
hl(0, "@markup.math", { fg = "#C4D870" })
hl(0, "@markup.link", { fg = "#A9B789" })
hl(0, "@markup.link.label", { fg = "#D4A87D" })
hl(0, "@markup.link.url", { fg = "#A9B789", underline = true })
hl(0, "@markup.raw", { fg = "#CEAE4C" })
hl(0, "@markup.list", { fg = "#D4A87D" })
hl(0, "@markup.list.checked", { fg = "#81C08E" })
hl(0, "@markup.list.unchecked", { fg = "#B2B1B0" })
hl(0, "@diff.plus", { fg = "#81C08E" })
hl(0, "@diff.minus", { fg = "#E3A298" })
hl(0, "@diff.delta", { fg = "#CEAE4C" })
hl(0, "@lsp.type.namespace", { link = "@module" })
hl(0, "@lsp.type.class", { link = "@type" })
hl(0, "@lsp.type.enum", { link = "@type" })
hl(0, "@lsp.type.interface", { link = "@type" })
hl(0, "@lsp.type.struct", { link = "@type" })
hl(0, "@lsp.type.parameter", { link = "@variable.parameter" })
hl(0, "@lsp.type.property", { link = "@property" })
hl(0, "@lsp.type.enumMember", { link = "@constant" })
hl(0, "@lsp.type.method", { link = "@function.method" })
hl(0, "MiniIconsAzure", { fg = "#A9B789" })
hl(0, "MiniIconsBlue", { fg = "#D4A87D" })
hl(0, "MiniIconsCyan", { fg = "#E69CC1" })
hl(0, "MiniIconsGreen", { fg = "#81C08E" })
hl(0, "MiniIconsGrey", { fg = "#B2B1B0" })
hl(0, "MiniIconsOrange", { fg = "#C4D870" })
hl(0, "MiniIconsPurple", { fg = "#7DD47D" })
hl(0, "MiniIconsRed", { fg = "#E3A298" })
hl(0, "MiniIconsYellow", { fg = "#CEAE4C" })
hl(0, "MiniFilesTitleFocused", { fg = "#D4A87D", bg = "#3B454E", bold = true })
hl(0, "MiniFilesDirectory", { fg = "#A9B789" })
hl(0, "MiniFilesFile", { fg = "#D8D0C8" })
hl(0, "MiniFilesCursorLine", { bg = "#495259" })
hl(0, "MiniPickMatchCurrent", { bg = "#495259", bold = true })
hl(0, "MiniPickMatchRanges", { fg = "#D4A87D", bold = true })
hl(0, "MiniPickPrompt", { fg = "#D4A87D", bold = true })
hl(0, "MiniPickBorderText", { fg = "#D4A87D" })
hl(0, "MiniClueDescGroup", { fg = "#E69CC1" })
hl(0, "MiniClueDescSingle", { fg = "#D8D0C8" })
hl(0, "MiniClueNextKey", { fg = "#D4A87D", bold = true })
hl(0, "MiniClueTitle", { fg = "#D4A87D", bg = "#3B454E", bold = true })
hl(0, "RenderMarkdownCode", { bg = "#3B454E" })
hl(0, "RenderMarkdownCodeInline", { fg = "#CEAE4C", bg = "#3B454E" })
hl(0, "RenderMarkdownBullet", { fg = "#D4A87D" })
hl(0, "RenderMarkdownQuote", { fg = "#B2B1B0" })
hl(0, "RenderMarkdownDash", { fg = "#8B9094" })
hl(0, "RenderMarkdownTableHead", { fg = "#E69CC1", bold = true })
hl(0, "RenderMarkdownTableRow", { fg = "#B2B1B0" })
hl(0, "RenderMarkdownLink", { fg = "#A9B789" })
hl(0, "RenderMarkdownChecked", { fg = "#81C08E" })
hl(0, "RenderMarkdownUnchecked", { fg = "#B2B1B0" })
hl(0, "@markup.heading.1", { fg = "#DCA873", bold = true })
hl(0, "RenderMarkdownH1", { fg = "#DCA873", bold = true })
hl(0, "RenderMarkdownH1Bg", { fg = "#DCA873", bg = "#454748", bold = true })
hl(0, "@markup.heading.2", { fg = "#A9B789", bold = true })
hl(0, "RenderMarkdownH2", { fg = "#A9B789", bold = true })
hl(0, "RenderMarkdownH2Bg", { fg = "#A9B789", bg = "#3D494C", bold = true })
hl(0, "@markup.heading.3", { fg = "#CEAE4C", bold = true })
hl(0, "RenderMarkdownH3", { fg = "#CEAE4C", bold = true })
hl(0, "RenderMarkdownH3Bg", { fg = "#CEAE4C", bg = "#434843", bold = true })
hl(0, "@markup.heading.4", { fg = "#C4D870", bold = true })
hl(0, "RenderMarkdownH4", { fg = "#C4D870", bold = true })
hl(0, "RenderMarkdownH4Bg", { fg = "#C4D870", bg = "#414E48", bold = true })
hl(0, "@markup.heading.5", { fg = "#E69CC1", bold = true })
hl(0, "RenderMarkdownH5", { fg = "#E69CC1", bold = true })
hl(0, "RenderMarkdownH5Bg", { fg = "#E69CC1", bg = "#464554", bold = true })
hl(0, "@markup.heading.6", { fg = "#7DD47D", bold = true })
hl(0, "RenderMarkdownH6", { fg = "#7DD47D", bold = true })
hl(0, "RenderMarkdownH6Bg", { fg = "#7DD47D", bg = "#364E4A", bold = true })

vim.g.terminal_color_0 = "#565C63"
vim.g.terminal_color_1 = "#E3A298"
vim.g.terminal_color_2 = "#81C08E"
vim.g.terminal_color_3 = "#CEAE4C"
vim.g.terminal_color_4 = "#D4A87D"
vim.g.terminal_color_5 = "#7DD47D"
vim.g.terminal_color_6 = "#DCA873"
vim.g.terminal_color_7 = "#B2B1B0"
vim.g.terminal_color_8 = "#787B7E"
vim.g.terminal_color_9 = "#E9B5AD"
vim.g.terminal_color_10 = "#9ACDA5"
vim.g.terminal_color_11 = "#D8BE70"
vim.g.terminal_color_12 = "#DDB997"
vim.g.terminal_color_13 = "#97DD97"
vim.g.terminal_color_14 = "#E3B98F"
vim.g.terminal_color_15 = "#D8D0C8"
