-- retro-synthwave - erzeugt von retro-coding-themes, nicht von Hand aendern.
-- Quelle: src/retro_coding_themes/data/synthwave.json, Ableitung in derive.py.

vim.cmd("highlight clear")
if vim.fn.exists("syntax_on") == 1 then
  vim.cmd("syntax reset")
end

vim.o.background = "dark"
vim.g.colors_name = "retro-synthwave"

local hl = vim.api.nvim_set_hl

hl(0, "Normal", { fg = "#F5E9FF", bg = "#1A0B3D" })
hl(0, "NormalNC", { link = "Normal" })
hl(0, "NormalFloat", { fg = "#F5E9FF", bg = "#302150" })
hl(0, "FloatBorder", { fg = "#7D6D9B", bg = "#302150" })
hl(0, "FloatTitle", { fg = "#05D9E8", bg = "#302150", bold = true })
hl(0, "ColorColumn", { bg = "#291B4B" })
hl(0, "Conceal", { fg = "#7D6F94" })
hl(0, "Cursor", { fg = "#1A0B3D", bg = "#F5E9FF" })
hl(0, "lCursor", { link = "Cursor" })
hl(0, "TermCursor", { link = "Cursor" })
hl(0, "CursorLine", { bg = "#291B4B" })
hl(0, "CursorColumn", { link = "CursorLine" })
hl(0, "CursorLineNr", { fg = "#05D9E8", bold = true })
hl(0, "LineNr", { fg = "#7D6F94" })
hl(0, "SignColumn", { bg = "#1A0B3D" })
hl(0, "FoldColumn", { fg = "#7D6F94" })
hl(0, "Folded", { fg = "#A89BBB", bg = "#302150" })
hl(0, "EndOfBuffer", { fg = "#1A0B3D" })
hl(0, "NonText", { fg = "#7D6F94" })
hl(0, "Whitespace", { fg = "#51426E" })
hl(0, "SpecialKey", { fg = "#7D6F94" })
hl(0, "Visual", { bg = "#135379" })
hl(0, "VisualNOS", { link = "Visual" })
hl(0, "MatchParen", { fg = "#05D9E8", bg = "#413360", bold = true })
hl(0, "Pmenu", { fg = "#F5E9FF", bg = "#302150" })
hl(0, "PmenuSel", { fg = "#F5E9FF", bg = "#413360", bold = true })
hl(0, "PmenuSbar", { bg = "#302150" })
hl(0, "PmenuThumb", { bg = "#7D6D9B" })
hl(0, "PmenuKind", { fg = "#C072D2" })
hl(0, "PmenuKindSel", { fg = "#C072D2", bg = "#413360" })
hl(0, "PmenuExtra", { fg = "#7D6F94" })
hl(0, "PmenuExtraSel", { fg = "#7D6F94", bg = "#413360" })
hl(0, "WildMenu", { link = "PmenuSel" })
hl(0, "StatusLine", { fg = "#000000", bg = "#FF2E93", bold = true })
hl(0, "StatusLineNC", { fg = "#A89BBB", bg = "#302150" })
hl(0, "WinBar", { fg = "#A89BBB", bg = "#1A0B3D" })
hl(0, "WinBarNC", { fg = "#7D6F94", bg = "#1A0B3D" })
hl(0, "WinSeparator", { fg = "#7D6D9B" })
hl(0, "TabLine", { fg = "#A89BBB", bg = "#302150" })
hl(0, "TabLineFill", { bg = "#1A0B3D" })
hl(0, "TabLineSel", { fg = "#000000", bg = "#FF2E93", bold = true })
hl(0, "Search", { fg = "#F5E9FF", bg = "#6A5130" })
hl(0, "IncSearch", { fg = "#1A0B3D", bg = "#FFD319", bold = true })
hl(0, "CurSearch", { link = "IncSearch" })
hl(0, "Substitute", { fg = "#1A0B3D", bg = "#FF5274" })
hl(0, "QuickFixLine", { bg = "#413360", bold = true })
hl(0, "Directory", { fg = "#FF48A0" })
hl(0, "Title", { fg = "#05D9E8", bold = true })
hl(0, "Question", { fg = "#39FF14" })
hl(0, "MoreMsg", { fg = "#39FF14" })
hl(0, "ModeMsg", { fg = "#F5E9FF", bold = true })
hl(0, "MsgArea", { fg = "#F5E9FF", bg = "#1A0B3D" })
hl(0, "MsgSeparator", { fg = "#7D6D9B" })
hl(0, "WarningMsg", { fg = "#FFD319" })
hl(0, "ErrorMsg", { fg = "#FF5274" })
hl(0, "SpellBad", { sp = "#FF5274", undercurl = true })
hl(0, "SpellCap", { sp = "#FFD319", undercurl = true })
hl(0, "SpellLocal", { sp = "#FF48A0", undercurl = true })
hl(0, "SpellRare", { sp = "#B080BF", undercurl = true })
hl(0, "Comment", { fg = "#B88BC6", italic = true })
hl(0, "Constant", { fg = "#FFD319" })
hl(0, "String", { fg = "#39FF14" })
hl(0, "Character", { fg = "#39FF14" })
hl(0, "Number", { fg = "#FFD319" })
hl(0, "Boolean", { fg = "#FFD319" })
hl(0, "Float", { fg = "#FFD319" })
hl(0, "Identifier", { fg = "#F5E9FF" })
hl(0, "Function", { fg = "#FF48A0" })
hl(0, "Statement", { fg = "#05D9E8" })
hl(0, "Conditional", { fg = "#05D9E8" })
hl(0, "Repeat", { fg = "#05D9E8" })
hl(0, "Label", { fg = "#05D9E8" })
hl(0, "Operator", { fg = "#C9BDD8" })
hl(0, "Keyword", { fg = "#05D9E8" })
hl(0, "Exception", { fg = "#05D9E8" })
hl(0, "PreProc", { fg = "#FF853C" })
hl(0, "Include", { fg = "#05D9E8" })
hl(0, "Define", { fg = "#FF853C" })
hl(0, "Macro", { fg = "#FF853C" })
hl(0, "PreCondit", { fg = "#FF853C" })
hl(0, "Type", { fg = "#C072D2" })
hl(0, "StorageClass", { fg = "#05D9E8" })
hl(0, "Structure", { fg = "#C072D2" })
hl(0, "Typedef", { fg = "#C072D2" })
hl(0, "Special", { fg = "#FF853C" })
hl(0, "SpecialChar", { fg = "#FF853C" })
hl(0, "Tag", { fg = "#05D9E8" })
hl(0, "Delimiter", { fg = "#C9BDD8" })
hl(0, "SpecialComment", { fg = "#B88BC6", bold = true })
hl(0, "Debug", { fg = "#FF5274" })
hl(0, "Underlined", { fg = "#FF48A0", underline = true })
hl(0, "Ignore", { fg = "#7D6F94" })
hl(0, "Error", { fg = "#FF5274", bold = true })
hl(0, "Todo", { fg = "#1A0B3D", bg = "#FFD319", bold = true })
hl(0, "Added", { fg = "#39FF14" })
hl(0, "Changed", { fg = "#FFD319" })
hl(0, "Removed", { fg = "#FF5274" })
hl(0, "DiffAdd", { bg = "#203736" })
hl(0, "DiffChange", { bg = "#352339" })
hl(0, "DiffDelete", { bg = "#431847" })
hl(0, "DiffText", { bg = "#5F4732", bold = true })
hl(0, "DiagnosticError", { fg = "#FF5274" })
hl(0, "DiagnosticWarn", { fg = "#FFD319" })
hl(0, "DiagnosticInfo", { fg = "#FF48A0" })
hl(0, "DiagnosticHint", { fg = "#B080BF" })
hl(0, "DiagnosticOk", { fg = "#39FF14" })
hl(0, "DiagnosticUnderlineError", { sp = "#FF5274", undercurl = true })
hl(0, "DiagnosticUnderlineWarn", { sp = "#FFD319", undercurl = true })
hl(0, "DiagnosticUnderlineInfo", { sp = "#FF48A0", undercurl = true })
hl(0, "DiagnosticUnderlineHint", { sp = "#B080BF", undercurl = true })
hl(0, "DiagnosticUnderlineOk", { sp = "#39FF14", undercurl = true })
hl(0, "DiagnosticVirtualTextError", { fg = "#FF5274", bg = "#351444" })
hl(0, "DiagnosticVirtualTextWarn", { fg = "#FFD319", bg = "#352339" })
hl(0, "DiagnosticVirtualTextInfo", { fg = "#FF48A0", bg = "#351249" })
hl(0, "DiagnosticVirtualTextHint", { fg = "#B080BF", bg = "#2C194D" })
hl(0, "@variable", { fg = "#F5E9FF" })
hl(0, "@variable.builtin", { fg = "#FF853C", italic = true })
hl(0, "@variable.parameter", { fg = "#F5E9FF" })
hl(0, "@variable.member", { fg = "#F5E9FF" })
hl(0, "@constant", { fg = "#FFD319" })
hl(0, "@constant.builtin", { fg = "#FF853C" })
hl(0, "@constant.macro", { fg = "#FF853C" })
hl(0, "@module", { fg = "#C072D2" })
hl(0, "@label", { fg = "#05D9E8" })
hl(0, "@string", { fg = "#39FF14" })
hl(0, "@string.documentation", { fg = "#B88BC6" })
hl(0, "@string.escape", { fg = "#FF853C" })
hl(0, "@string.regexp", { fg = "#FF853C" })
hl(0, "@string.special", { fg = "#FF853C" })
hl(0, "@character", { fg = "#39FF14" })
hl(0, "@character.special", { fg = "#FF853C" })
hl(0, "@boolean", { fg = "#FFD319" })
hl(0, "@number", { fg = "#FFD319" })
hl(0, "@number.float", { fg = "#FFD319" })
hl(0, "@type", { fg = "#C072D2" })
hl(0, "@type.builtin", { fg = "#C072D2", italic = true })
hl(0, "@type.definition", { fg = "#C072D2" })
hl(0, "@attribute", { fg = "#FF853C" })
hl(0, "@attribute.builtin", { fg = "#FF853C" })
hl(0, "@property", { fg = "#F5E9FF" })
hl(0, "@function", { fg = "#FF48A0" })
hl(0, "@function.builtin", { fg = "#FF853C" })
hl(0, "@function.macro", { fg = "#FF853C" })
hl(0, "@function.method", { fg = "#FF48A0" })
hl(0, "@constructor", { fg = "#C072D2" })
hl(0, "@operator", { fg = "#C9BDD8" })
hl(0, "@keyword", { fg = "#05D9E8" })
hl(0, "@keyword.function", { fg = "#05D9E8" })
hl(0, "@keyword.operator", { fg = "#05D9E8" })
hl(0, "@keyword.import", { fg = "#05D9E8" })
hl(0, "@keyword.return", { fg = "#05D9E8" })
hl(0, "@keyword.exception", { fg = "#05D9E8" })
hl(0, "@punctuation.delimiter", { fg = "#C9BDD8" })
hl(0, "@punctuation.bracket", { fg = "#C9BDD8" })
hl(0, "@punctuation.special", { fg = "#FF853C" })
hl(0, "@comment", { fg = "#B88BC6", italic = true })
hl(0, "@comment.documentation", { fg = "#B88BC6", italic = true })
hl(0, "@comment.error", { fg = "#1A0B3D", bg = "#FF5274", bold = true })
hl(0, "@comment.warning", { fg = "#1A0B3D", bg = "#FFD319", bold = true })
hl(0, "@comment.todo", { link = "Todo" })
hl(0, "@comment.note", { fg = "#1A0B3D", bg = "#FF48A0", bold = true })
hl(0, "@tag", { fg = "#05D9E8" })
hl(0, "@tag.builtin", { fg = "#05D9E8" })
hl(0, "@tag.attribute", { fg = "#FF48A0", italic = true })
hl(0, "@tag.delimiter", { fg = "#C9BDD8" })
hl(0, "@markup.strong", { fg = "#F5E9FF", bold = true })
hl(0, "@markup.italic", { fg = "#F5E9FF", italic = true })
hl(0, "@markup.strikethrough", { fg = "#A89BBB", strikethrough = true })
hl(0, "@markup.underline", { fg = "#F5E9FF", underline = true })
hl(0, "@markup.quote", { fg = "#A89BBB", italic = true })
hl(0, "@markup.math", { fg = "#FFD319" })
hl(0, "@markup.link", { fg = "#FF48A0" })
hl(0, "@markup.link.label", { fg = "#05D9E8" })
hl(0, "@markup.link.url", { fg = "#FF48A0", underline = true })
hl(0, "@markup.raw", { fg = "#39FF14" })
hl(0, "@markup.list", { fg = "#05D9E8" })
hl(0, "@markup.list.checked", { fg = "#39FF14" })
hl(0, "@markup.list.unchecked", { fg = "#A89BBB" })
hl(0, "@diff.plus", { fg = "#39FF14" })
hl(0, "@diff.minus", { fg = "#FF5274" })
hl(0, "@diff.delta", { fg = "#FFD319" })
hl(0, "@lsp.type.namespace", { link = "@module" })
hl(0, "@lsp.type.class", { link = "@type" })
hl(0, "@lsp.type.enum", { link = "@type" })
hl(0, "@lsp.type.interface", { link = "@type" })
hl(0, "@lsp.type.struct", { link = "@type" })
hl(0, "@lsp.type.parameter", { link = "@variable.parameter" })
hl(0, "@lsp.type.property", { link = "@property" })
hl(0, "@lsp.type.enumMember", { link = "@constant" })
hl(0, "@lsp.type.method", { link = "@function.method" })
hl(0, "MiniIconsAzure", { fg = "#FF48A0" })
hl(0, "MiniIconsBlue", { fg = "#FF48A0" })
hl(0, "MiniIconsCyan", { fg = "#C072D2" })
hl(0, "MiniIconsGreen", { fg = "#39FF14" })
hl(0, "MiniIconsGrey", { fg = "#A89BBB" })
hl(0, "MiniIconsOrange", { fg = "#FFD319" })
hl(0, "MiniIconsPurple", { fg = "#FF853C" })
hl(0, "MiniIconsRed", { fg = "#FF5274" })
hl(0, "MiniIconsYellow", { fg = "#FFD319" })
hl(0, "MiniFilesTitleFocused", { fg = "#05D9E8", bg = "#302150", bold = true })
hl(0, "MiniFilesDirectory", { fg = "#FF48A0" })
hl(0, "MiniFilesFile", { fg = "#F5E9FF" })
hl(0, "MiniFilesCursorLine", { bg = "#413360" })
hl(0, "MiniPickMatchCurrent", { bg = "#413360", bold = true })
hl(0, "MiniPickMatchRanges", { fg = "#05D9E8", bold = true })
hl(0, "MiniPickPrompt", { fg = "#05D9E8", bold = true })
hl(0, "MiniPickBorderText", { fg = "#05D9E8" })
hl(0, "MiniClueDescGroup", { fg = "#C072D2" })
hl(0, "MiniClueDescSingle", { fg = "#F5E9FF" })
hl(0, "MiniClueNextKey", { fg = "#05D9E8", bold = true })
hl(0, "MiniClueTitle", { fg = "#05D9E8", bg = "#302150", bold = true })
hl(0, "RenderMarkdownCode", { bg = "#302150" })
hl(0, "RenderMarkdownCodeInline", { fg = "#39FF14", bg = "#302150" })
hl(0, "RenderMarkdownBullet", { fg = "#05D9E8" })
hl(0, "RenderMarkdownQuote", { fg = "#A89BBB" })
hl(0, "RenderMarkdownDash", { fg = "#7D6D9B" })
hl(0, "RenderMarkdownTableHead", { fg = "#C072D2", bold = true })
hl(0, "RenderMarkdownTableRow", { fg = "#A89BBB" })
hl(0, "RenderMarkdownLink", { fg = "#FF48A0" })
hl(0, "RenderMarkdownChecked", { fg = "#39FF14" })
hl(0, "RenderMarkdownUnchecked", { fg = "#A89BBB" })
hl(0, "@markup.heading.1", { fg = "#05D9E8", bold = true })
hl(0, "RenderMarkdownH1", { fg = "#05D9E8", bold = true })
hl(0, "RenderMarkdownH1Bg", { fg = "#05D9E8", bg = "#172A57", bold = true })
hl(0, "@markup.heading.2", { fg = "#FF48A0", bold = true })
hl(0, "RenderMarkdownH2", { fg = "#FF48A0", bold = true })
hl(0, "RenderMarkdownH2Bg", { fg = "#FF48A0", bg = "#3C144C", bold = true })
hl(0, "@markup.heading.3", { fg = "#39FF14", bold = true })
hl(0, "RenderMarkdownH3", { fg = "#39FF14", bold = true })
hl(0, "RenderMarkdownH3Bg", { fg = "#39FF14", bg = "#1F3037", bold = true })
hl(0, "@markup.heading.4", { fg = "#FFD319", bold = true })
hl(0, "RenderMarkdownH4", { fg = "#FFD319", bold = true })
hl(0, "RenderMarkdownH4Bg", { fg = "#FFD319", bg = "#3C2938", bold = true })
hl(0, "@markup.heading.5", { fg = "#C072D2", bold = true })
hl(0, "RenderMarkdownH5", { fg = "#C072D2", bold = true })
hl(0, "RenderMarkdownH5Bg", { fg = "#C072D2", bg = "#331A53", bold = true })
hl(0, "@markup.heading.6", { fg = "#FF853C", bold = true })
hl(0, "RenderMarkdownH6", { fg = "#FF853C", bold = true })
hl(0, "RenderMarkdownH6Bg", { fg = "#FF853C", bg = "#3C1D3D", bold = true })

vim.g.terminal_color_0 = "#51426E"
vim.g.terminal_color_1 = "#FF5274"
vim.g.terminal_color_2 = "#39FF14"
vim.g.terminal_color_3 = "#FFD319"
vim.g.terminal_color_4 = "#FF48A0"
vim.g.terminal_color_5 = "#FF853C"
vim.g.terminal_color_6 = "#05D9E8"
vim.g.terminal_color_7 = "#A89BBB"
vim.g.terminal_color_8 = "#7D6F94"
vim.g.terminal_color_9 = "#FF7590"
vim.g.terminal_color_10 = "#61FF43"
vim.g.terminal_color_11 = "#FFDC47"
vim.g.terminal_color_12 = "#FF6DB3"
vim.g.terminal_color_13 = "#FF9D63"
vim.g.terminal_color_14 = "#37E1ED"
vim.g.terminal_color_15 = "#F5E9FF"
