-- retro-clipper - erzeugt von retro-coding-themes, nicht von Hand aendern.
-- Quelle: src/retro_coding_themes/data/clipper.json, Ableitung in derive.py.

vim.cmd("highlight clear")
if vim.fn.exists("syntax_on") == 1 then
  vim.cmd("syntax reset")
end

vim.o.background = "light"
vim.g.colors_name = "retro-clipper"

local hl = vim.api.nvim_set_hl

hl(0, "Normal", { fg = "#1A1A1A", bg = "#F6F3E8" })
hl(0, "NormalNC", { link = "Normal" })
hl(0, "NormalFloat", { fg = "#1A1A1A", bg = "#E0DDD3" })
hl(0, "FloatBorder", { fg = "#7F7C73", bg = "#E0DDD3" })
hl(0, "FloatTitle", { fg = "#BE1E2A", bg = "#E0DDD3", bold = true })
hl(0, "ColorColumn", { bg = "#E7E4DA" })
hl(0, "Conceal", { fg = "#7F7D76" })
hl(0, "Cursor", { fg = "#F6F3E8", bg = "#1A1A1A" })
hl(0, "lCursor", { link = "Cursor" })
hl(0, "TermCursor", { link = "Cursor" })
hl(0, "CursorLine", { bg = "#E7E4DA" })
hl(0, "CursorColumn", { link = "CursorLine" })
hl(0, "CursorLineNr", { fg = "#BE1E2A", bold = true })
hl(0, "LineNr", { fg = "#7F7D76" })
hl(0, "SignColumn", { bg = "#F6F3E8" })
hl(0, "FoldColumn", { fg = "#7F7D76" })
hl(0, "Folded", { fg = "#62615D", bg = "#E0DDD3" })
hl(0, "EndOfBuffer", { fg = "#F6F3E8" })
hl(0, "NonText", { fg = "#7F7D76" })
hl(0, "Whitespace", { fg = "#BFBDB4" })
hl(0, "SpecialKey", { fg = "#7F7D76" })
hl(0, "Visual", { bg = "#EAAAA7" })
hl(0, "VisualNOS", { link = "Visual" })
hl(0, "MatchParen", { fg = "#BE1E2A", bg = "#CECCC3", bold = true })
hl(0, "Pmenu", { fg = "#1A1A1A", bg = "#E0DDD3" })
hl(0, "PmenuSel", { fg = "#1A1A1A", bg = "#CECCC3", bold = true })
hl(0, "PmenuSbar", { bg = "#E0DDD3" })
hl(0, "PmenuThumb", { bg = "#7F7C73" })
hl(0, "PmenuKind", { fg = "#23696A" })
hl(0, "PmenuKindSel", { fg = "#23696A", bg = "#CECCC3" })
hl(0, "PmenuExtra", { fg = "#7F7D76" })
hl(0, "PmenuExtraSel", { fg = "#7F7D76", bg = "#CECCC3" })
hl(0, "WildMenu", { link = "PmenuSel" })
hl(0, "StatusLine", { fg = "#FFFFFF", bg = "#1A4FA0", bold = true })
hl(0, "StatusLineNC", { fg = "#62615D", bg = "#E0DDD3" })
hl(0, "WinBar", { fg = "#62615D", bg = "#F6F3E8" })
hl(0, "WinBarNC", { fg = "#7F7D76", bg = "#F6F3E8" })
hl(0, "WinSeparator", { fg = "#7F7C73" })
hl(0, "TabLine", { fg = "#62615D", bg = "#E0DDD3" })
hl(0, "TabLineFill", { bg = "#F6F3E8" })
hl(0, "TabLineSel", { fg = "#FFFFFF", bg = "#1A4FA0", bold = true })
hl(0, "Search", { fg = "#1A1A1A", bg = "#CDBD9E" })
hl(0, "IncSearch", { fg = "#F6F3E8", bg = "#825915", bold = true })
hl(0, "CurSearch", { link = "IncSearch" })
hl(0, "Substitute", { fg = "#F6F3E8", bg = "#BD1E2A" })
hl(0, "QuickFixLine", { bg = "#CECCC3", bold = true })
hl(0, "Directory", { fg = "#1A4FA0" })
hl(0, "Title", { fg = "#BE1E2A", bold = true })
hl(0, "Question", { fg = "#246C30" })
hl(0, "MoreMsg", { fg = "#246C30" })
hl(0, "ModeMsg", { fg = "#1A1A1A", bold = true })
hl(0, "MsgArea", { fg = "#1A1A1A", bg = "#F6F3E8" })
hl(0, "MsgSeparator", { fg = "#7F7C73" })
hl(0, "WarningMsg", { fg = "#825915" })
hl(0, "ErrorMsg", { fg = "#BD1E2A" })
hl(0, "SpellBad", { sp = "#BD1E2A", undercurl = true })
hl(0, "SpellCap", { sp = "#825915", undercurl = true })
hl(0, "SpellLocal", { sp = "#1A4FA0", undercurl = true })
hl(0, "SpellRare", { sp = "#8A1D26", undercurl = true })
hl(0, "Comment", { fg = "#701C23", italic = true })
hl(0, "Constant", { fg = "#825915" })
hl(0, "String", { fg = "#246C30" })
hl(0, "Character", { fg = "#246C30" })
hl(0, "Number", { fg = "#825915" })
hl(0, "Boolean", { fg = "#825915" })
hl(0, "Float", { fg = "#825915" })
hl(0, "Identifier", { fg = "#1A1A1A" })
hl(0, "Function", { fg = "#1A4FA0" })
hl(0, "Statement", { fg = "#BE1E2A" })
hl(0, "Conditional", { fg = "#BE1E2A" })
hl(0, "Repeat", { fg = "#BE1E2A" })
hl(0, "Label", { fg = "#BE1E2A" })
hl(0, "Operator", { fg = "#464543" })
hl(0, "Keyword", { fg = "#BE1E2A" })
hl(0, "Exception", { fg = "#BE1E2A" })
hl(0, "PreProc", { fg = "#A0441F" })
hl(0, "Include", { fg = "#BE1E2A" })
hl(0, "Define", { fg = "#A0441F" })
hl(0, "Macro", { fg = "#A0441F" })
hl(0, "PreCondit", { fg = "#A0441F" })
hl(0, "Type", { fg = "#23696A" })
hl(0, "StorageClass", { fg = "#BE1E2A" })
hl(0, "Structure", { fg = "#23696A" })
hl(0, "Typedef", { fg = "#23696A" })
hl(0, "Special", { fg = "#A0441F" })
hl(0, "SpecialChar", { fg = "#A0441F" })
hl(0, "Tag", { fg = "#BE1E2A" })
hl(0, "Delimiter", { fg = "#464543" })
hl(0, "SpecialComment", { fg = "#701C23", bold = true })
hl(0, "Debug", { fg = "#BD1E2A" })
hl(0, "Underlined", { fg = "#1A4FA0", underline = true })
hl(0, "Ignore", { fg = "#7F7D76" })
hl(0, "Error", { fg = "#BD1E2A", bold = true })
hl(0, "Todo", { fg = "#F6F3E8", bg = "#825915", bold = true })
hl(0, "Added", { fg = "#246C30" })
hl(0, "Changed", { fg = "#825915" })
hl(0, "Removed", { fg = "#BD1E2A" })
hl(0, "DiffAdd", { bg = "#D0DBC7" })
hl(0, "DiffChange", { bg = "#E8E1CF" })
hl(0, "DiffDelete", { bg = "#ECCDC6" })
hl(0, "DiffText", { bg = "#D3C5A9", bold = true })
hl(0, "DiagnosticError", { fg = "#BD1E2A" })
hl(0, "DiagnosticWarn", { fg = "#825915" })
hl(0, "DiagnosticInfo", { fg = "#1A4FA0" })
hl(0, "DiagnosticHint", { fg = "#8A1D26" })
hl(0, "DiagnosticOk", { fg = "#246C30" })
hl(0, "DiagnosticUnderlineError", { sp = "#BD1E2A", undercurl = true })
hl(0, "DiagnosticUnderlineWarn", { sp = "#825915", undercurl = true })
hl(0, "DiagnosticUnderlineInfo", { sp = "#1A4FA0", undercurl = true })
hl(0, "DiagnosticUnderlineHint", { sp = "#8A1D26", undercurl = true })
hl(0, "DiagnosticUnderlineOk", { sp = "#246C30", undercurl = true })
hl(0, "DiagnosticVirtualTextError", { fg = "#BD1E2A", bg = "#EFD9D1" })
hl(0, "DiagnosticVirtualTextWarn", { fg = "#825915", bg = "#E8E1CF" })
hl(0, "DiagnosticVirtualTextInfo", { fg = "#1A4FA0", bg = "#DCDFDF" })
hl(0, "DiagnosticVirtualTextHint", { fg = "#8A1D26", bg = "#E9D9D1" })
hl(0, "@variable", { fg = "#1A1A1A" })
hl(0, "@variable.builtin", { fg = "#A0441F", italic = true })
hl(0, "@variable.parameter", { fg = "#1A1A1A" })
hl(0, "@variable.member", { fg = "#1A1A1A" })
hl(0, "@constant", { fg = "#825915" })
hl(0, "@constant.builtin", { fg = "#A0441F" })
hl(0, "@constant.macro", { fg = "#A0441F" })
hl(0, "@module", { fg = "#23696A" })
hl(0, "@label", { fg = "#BE1E2A" })
hl(0, "@string", { fg = "#246C30" })
hl(0, "@string.documentation", { fg = "#701C23" })
hl(0, "@string.escape", { fg = "#A0441F" })
hl(0, "@string.regexp", { fg = "#A0441F" })
hl(0, "@string.special", { fg = "#A0441F" })
hl(0, "@character", { fg = "#246C30" })
hl(0, "@character.special", { fg = "#A0441F" })
hl(0, "@boolean", { fg = "#825915" })
hl(0, "@number", { fg = "#825915" })
hl(0, "@number.float", { fg = "#825915" })
hl(0, "@type", { fg = "#23696A" })
hl(0, "@type.builtin", { fg = "#23696A", italic = true })
hl(0, "@type.definition", { fg = "#23696A" })
hl(0, "@attribute", { fg = "#A0441F" })
hl(0, "@attribute.builtin", { fg = "#A0441F" })
hl(0, "@property", { fg = "#1A1A1A" })
hl(0, "@function", { fg = "#1A4FA0" })
hl(0, "@function.builtin", { fg = "#A0441F" })
hl(0, "@function.macro", { fg = "#A0441F" })
hl(0, "@function.method", { fg = "#1A4FA0" })
hl(0, "@constructor", { fg = "#23696A" })
hl(0, "@operator", { fg = "#464543" })
hl(0, "@keyword", { fg = "#BE1E2A" })
hl(0, "@keyword.function", { fg = "#BE1E2A" })
hl(0, "@keyword.operator", { fg = "#BE1E2A" })
hl(0, "@keyword.import", { fg = "#BE1E2A" })
hl(0, "@keyword.return", { fg = "#BE1E2A" })
hl(0, "@keyword.exception", { fg = "#BE1E2A" })
hl(0, "@punctuation.delimiter", { fg = "#464543" })
hl(0, "@punctuation.bracket", { fg = "#464543" })
hl(0, "@punctuation.special", { fg = "#A0441F" })
hl(0, "@comment", { fg = "#701C23", italic = true })
hl(0, "@comment.documentation", { fg = "#701C23", italic = true })
hl(0, "@comment.error", { fg = "#F6F3E8", bg = "#BD1E2A", bold = true })
hl(0, "@comment.warning", { fg = "#F6F3E8", bg = "#825915", bold = true })
hl(0, "@comment.todo", { link = "Todo" })
hl(0, "@comment.note", { fg = "#F6F3E8", bg = "#1A4FA0", bold = true })
hl(0, "@tag", { fg = "#BE1E2A" })
hl(0, "@tag.builtin", { fg = "#BE1E2A" })
hl(0, "@tag.attribute", { fg = "#1A4FA0", italic = true })
hl(0, "@tag.delimiter", { fg = "#464543" })
hl(0, "@markup.strong", { fg = "#1A1A1A", bold = true })
hl(0, "@markup.italic", { fg = "#1A1A1A", italic = true })
hl(0, "@markup.strikethrough", { fg = "#62615D", strikethrough = true })
hl(0, "@markup.underline", { fg = "#1A1A1A", underline = true })
hl(0, "@markup.quote", { fg = "#62615D", italic = true })
hl(0, "@markup.math", { fg = "#825915" })
hl(0, "@markup.link", { fg = "#1A4FA0" })
hl(0, "@markup.link.label", { fg = "#BE1E2A" })
hl(0, "@markup.link.url", { fg = "#1A4FA0", underline = true })
hl(0, "@markup.raw", { fg = "#246C30" })
hl(0, "@markup.list", { fg = "#BE1E2A" })
hl(0, "@markup.list.checked", { fg = "#246C30" })
hl(0, "@markup.list.unchecked", { fg = "#62615D" })
hl(0, "@diff.plus", { fg = "#246C30" })
hl(0, "@diff.minus", { fg = "#BD1E2A" })
hl(0, "@diff.delta", { fg = "#825915" })
hl(0, "@lsp.type.namespace", { link = "@module" })
hl(0, "@lsp.type.class", { link = "@type" })
hl(0, "@lsp.type.enum", { link = "@type" })
hl(0, "@lsp.type.interface", { link = "@type" })
hl(0, "@lsp.type.struct", { link = "@type" })
hl(0, "@lsp.type.parameter", { link = "@variable.parameter" })
hl(0, "@lsp.type.property", { link = "@property" })
hl(0, "@lsp.type.enumMember", { link = "@constant" })
hl(0, "@lsp.type.method", { link = "@function.method" })
hl(0, "MiniIconsAzure", { fg = "#1A4FA0" })
hl(0, "MiniIconsBlue", { fg = "#1A4FA0" })
hl(0, "MiniIconsCyan", { fg = "#23696A" })
hl(0, "MiniIconsGreen", { fg = "#246C30" })
hl(0, "MiniIconsGrey", { fg = "#62615D" })
hl(0, "MiniIconsOrange", { fg = "#825915" })
hl(0, "MiniIconsPurple", { fg = "#A0441F" })
hl(0, "MiniIconsRed", { fg = "#BD1E2A" })
hl(0, "MiniIconsYellow", { fg = "#825915" })
hl(0, "MiniFilesTitleFocused", { fg = "#BE1E2A", bg = "#E0DDD3", bold = true })
hl(0, "MiniFilesDirectory", { fg = "#1A4FA0" })
hl(0, "MiniFilesFile", { fg = "#1A1A1A" })
hl(0, "MiniFilesCursorLine", { bg = "#CECCC3" })
hl(0, "MiniPickMatchCurrent", { bg = "#CECCC3", bold = true })
hl(0, "MiniPickMatchRanges", { fg = "#BE1E2A", bold = true })
hl(0, "MiniPickPrompt", { fg = "#BE1E2A", bold = true })
hl(0, "MiniPickBorderText", { fg = "#BE1E2A" })
hl(0, "MiniClueDescGroup", { fg = "#23696A" })
hl(0, "MiniClueDescSingle", { fg = "#1A1A1A" })
hl(0, "MiniClueNextKey", { fg = "#BE1E2A", bold = true })
hl(0, "MiniClueTitle", { fg = "#BE1E2A", bg = "#E0DDD3", bold = true })
hl(0, "RenderMarkdownCode", { bg = "#E0DDD3" })
hl(0, "RenderMarkdownCodeInline", { fg = "#246C30", bg = "#E0DDD3" })
hl(0, "RenderMarkdownBullet", { fg = "#BE1E2A" })
hl(0, "RenderMarkdownQuote", { fg = "#62615D" })
hl(0, "RenderMarkdownDash", { fg = "#7F7C73" })
hl(0, "RenderMarkdownTableHead", { fg = "#23696A", bold = true })
hl(0, "RenderMarkdownTableRow", { fg = "#62615D" })
hl(0, "RenderMarkdownLink", { fg = "#1A4FA0" })
hl(0, "RenderMarkdownChecked", { fg = "#246C30" })
hl(0, "RenderMarkdownUnchecked", { fg = "#62615D" })
hl(0, "@markup.heading.1", { fg = "#BE1E2A", bold = true })
hl(0, "RenderMarkdownH1", { fg = "#BE1E2A", bold = true })
hl(0, "RenderMarkdownH1Bg", { fg = "#BE1E2A", bg = "#EED3CB", bold = true })
hl(0, "@markup.heading.2", { fg = "#1A4FA0", bold = true })
hl(0, "RenderMarkdownH2", { fg = "#1A4FA0", bold = true })
hl(0, "RenderMarkdownH2Bg", { fg = "#1A4FA0", bg = "#D5DADD", bold = true })
hl(0, "@markup.heading.3", { fg = "#246C30", bold = true })
hl(0, "RenderMarkdownH3", { fg = "#246C30", bold = true })
hl(0, "RenderMarkdownH3Bg", { fg = "#246C30", bg = "#D6DFCC", bold = true })
hl(0, "@markup.heading.4", { fg = "#825915", bold = true })
hl(0, "RenderMarkdownH4", { fg = "#825915", bold = true })
hl(0, "RenderMarkdownH4Bg", { fg = "#825915", bg = "#E5DCC8", bold = true })
hl(0, "@markup.heading.5", { fg = "#23696A", bold = true })
hl(0, "RenderMarkdownH5", { fg = "#23696A", bold = true })
hl(0, "RenderMarkdownH5Bg", { fg = "#23696A", bg = "#D6DED5", bold = true })
hl(0, "@markup.heading.6", { fg = "#A0441F", bold = true })
hl(0, "RenderMarkdownH6", { fg = "#A0441F", bold = true })
hl(0, "RenderMarkdownH6Bg", { fg = "#A0441F", bg = "#E9D9CA", bold = true })

vim.g.terminal_color_0 = "#30302F"
vim.g.terminal_color_1 = "#BD1E2A"
vim.g.terminal_color_2 = "#246C30"
vim.g.terminal_color_3 = "#825915"
vim.g.terminal_color_4 = "#1A4FA0"
vim.g.terminal_color_5 = "#A0441F"
vim.g.terminal_color_6 = "#BE1E2A"
vim.g.terminal_color_7 = "#62615D"
vim.g.terminal_color_8 = "#72716C"
vim.g.terminal_color_9 = "#971822"
vim.g.terminal_color_10 = "#1D5626"
vim.g.terminal_color_11 = "#684711"
vim.g.terminal_color_12 = "#153F80"
vim.g.terminal_color_13 = "#803619"
vim.g.terminal_color_14 = "#981822"
vim.g.terminal_color_15 = "#1A1A1A"
