-- retro-hulkula - erzeugt von retro-coding-themes, nicht von Hand aendern.
-- Quelle: src/retro_coding_themes/data/hulkula.json, Ableitung in derive.py.

vim.cmd("highlight clear")
if vim.fn.exists("syntax_on") == 1 then
  vim.cmd("syntax reset")
end

vim.o.background = "dark"
vim.g.colors_name = "retro-hulkula"

local hl = vim.api.nvim_set_hl

hl(0, "Normal", { fg = "#F0F2EE", bg = "#083C14" })
hl(0, "NormalNC", { link = "Normal" })
hl(0, "NormalFloat", { fg = "#F0F2EE", bg = "#1F4E2A" })
hl(0, "FloatBorder", { fg = "#739A7B", bg = "#1F4E2A" })
hl(0, "FloatTitle", { fg = "#4DC962", bg = "#1F4E2A", bold = true })
hl(0, "ColorColumn", { bg = "#184923" })
hl(0, "Conceal", { fg = "#7B9781" })
hl(0, "Cursor", { fg = "#083C14", bg = "#F0F2EE" })
hl(0, "lCursor", { link = "Cursor" })
hl(0, "TermCursor", { link = "Cursor" })
hl(0, "CursorLine", { bg = "#184923" })
hl(0, "CursorColumn", { link = "CursorLine" })
hl(0, "CursorLineNr", { fg = "#4DC962", bold = true })
hl(0, "LineNr", { fg = "#7B9781" })
hl(0, "SignColumn", { bg = "#083C14" })
hl(0, "FoldColumn", { fg = "#7B9781" })
hl(0, "Folded", { fg = "#A5B7A7", bg = "#1F4E2A" })
hl(0, "EndOfBuffer", { fg = "#083C14" })
hl(0, "NonText", { fg = "#7B9781" })
hl(0, "Whitespace", { fg = "#426A4A" })
hl(0, "SpecialKey", { fg = "#7B9781" })
hl(0, "Visual", { bg = "#206D2F" })
hl(0, "VisualNOS", { link = "Visual" })
hl(0, "MatchParen", { fg = "#4DC962", bg = "#325D3B", bold = true })
hl(0, "Pmenu", { fg = "#F0F2EE", bg = "#1F4E2A" })
hl(0, "PmenuSel", { fg = "#F0F2EE", bg = "#325D3B", bold = true })
hl(0, "PmenuSbar", { bg = "#1F4E2A" })
hl(0, "PmenuThumb", { bg = "#739A7B" })
hl(0, "PmenuKind", { fg = "#96DBA1" })
hl(0, "PmenuKindSel", { fg = "#96DBA1", bg = "#325D3B" })
hl(0, "PmenuExtra", { fg = "#7B9781" })
hl(0, "PmenuExtraSel", { fg = "#7B9781", bg = "#325D3B" })
hl(0, "WildMenu", { link = "PmenuSel" })
hl(0, "StatusLine", { fg = "#000000", bg = "#2BA841", bold = true })
hl(0, "StatusLineNC", { fg = "#A5B7A7", bg = "#1F4E2A" })
hl(0, "WinBar", { fg = "#A5B7A7", bg = "#083C14" })
hl(0, "WinBarNC", { fg = "#7B9781", bg = "#083C14" })
hl(0, "WinSeparator", { fg = "#739A7B" })
hl(0, "TabLine", { fg = "#A5B7A7", bg = "#1F4E2A" })
hl(0, "TabLineFill", { bg = "#083C14" })
hl(0, "TabLineSel", { fg = "#000000", bg = "#2BA841", bold = true })
hl(0, "Search", { fg = "#F0F2EE", bg = "#576B47" })
hl(0, "IncSearch", { fg = "#083C14", bg = "#EBC2A6", bold = true })
hl(0, "CurSearch", { link = "IncSearch" })
hl(0, "Substitute", { fg = "#083C14", bg = "#EF9D9D" })
hl(0, "QuickFixLine", { bg = "#325D3B", bold = true })
hl(0, "Directory", { fg = "#ABB5BC" })
hl(0, "Title", { fg = "#4DC962", bold = true })
hl(0, "Question", { fg = "#4DC962" })
hl(0, "MoreMsg", { fg = "#4DC962" })
hl(0, "ModeMsg", { fg = "#F0F2EE", bold = true })
hl(0, "MsgArea", { fg = "#F0F2EE", bg = "#083C14" })
hl(0, "MsgSeparator", { fg = "#739A7B" })
hl(0, "WarningMsg", { fg = "#D9AA55" })
hl(0, "ErrorMsg", { fg = "#EF9D9D" })
hl(0, "SpellBad", { sp = "#EF9D9D", undercurl = true })
hl(0, "SpellCap", { sp = "#D9AA55", undercurl = true })
hl(0, "SpellLocal", { sp = "#3ACC53", undercurl = true })
hl(0, "SpellRare", { sp = "#CED4D7", undercurl = true })
hl(0, "Comment", { fg = "#D6DBDC", italic = true })
hl(0, "Constant", { fg = "#EBC2A6" })
hl(0, "String", { fg = "#D9AA55" })
hl(0, "Character", { fg = "#D9AA55" })
hl(0, "Number", { fg = "#EBC2A6" })
hl(0, "Boolean", { fg = "#EBC2A6" })
hl(0, "Float", { fg = "#EBC2A6" })
hl(0, "Identifier", { fg = "#F0F2EE" })
hl(0, "Function", { fg = "#ABB5BC" })
hl(0, "Statement", { fg = "#4DC962" })
hl(0, "Conditional", { fg = "#4DC962" })
hl(0, "Repeat", { fg = "#4DC962" })
hl(0, "Label", { fg = "#4DC962" })
hl(0, "Operator", { fg = "#C2CEC2" })
hl(0, "Keyword", { fg = "#4DC962" })
hl(0, "Exception", { fg = "#4DC962" })
hl(0, "PreProc", { fg = "#E4E188" })
hl(0, "Include", { fg = "#4DC962" })
hl(0, "Define", { fg = "#E4E188" })
hl(0, "Macro", { fg = "#E4E188" })
hl(0, "PreCondit", { fg = "#E4E188" })
hl(0, "Type", { fg = "#96DBA1" })
hl(0, "StorageClass", { fg = "#4DC962" })
hl(0, "Structure", { fg = "#96DBA1" })
hl(0, "Typedef", { fg = "#96DBA1" })
hl(0, "Special", { fg = "#E4E188" })
hl(0, "SpecialChar", { fg = "#E4E188" })
hl(0, "Tag", { fg = "#4DC962" })
hl(0, "Delimiter", { fg = "#C2CEC2" })
hl(0, "SpecialComment", { fg = "#D6DBDC", bold = true })
hl(0, "Debug", { fg = "#EF9D9D" })
hl(0, "Underlined", { fg = "#ABB5BC", underline = true })
hl(0, "Ignore", { fg = "#7B9781" })
hl(0, "Error", { fg = "#EF9D9D", bold = true })
hl(0, "Todo", { fg = "#083C14", bg = "#EBC2A6", bold = true })
hl(0, "Added", { fg = "#4DC962" })
hl(0, "Changed", { fg = "#D9AA55" })
hl(0, "Removed", { fg = "#EF9D9D" })
hl(0, "DiffAdd", { bg = "#145522" })
hl(0, "DiffChange", { bg = "#21491C" })
hl(0, "DiffDelete", { bg = "#324D2D" })
hl(0, "DiffText", { bg = "#475D28", bold = true })
hl(0, "DiagnosticError", { fg = "#EF9D9D" })
hl(0, "DiagnosticWarn", { fg = "#D9AA55" })
hl(0, "DiagnosticInfo", { fg = "#3ACC53" })
hl(0, "DiagnosticHint", { fg = "#CED4D7" })
hl(0, "DiagnosticOk", { fg = "#4DC962" })
hl(0, "DiagnosticUnderlineError", { sp = "#EF9D9D", undercurl = true })
hl(0, "DiagnosticUnderlineWarn", { sp = "#D9AA55", undercurl = true })
hl(0, "DiagnosticUnderlineInfo", { sp = "#3ACC53", undercurl = true })
hl(0, "DiagnosticUnderlineHint", { sp = "#CED4D7", undercurl = true })
hl(0, "DiagnosticUnderlineOk", { sp = "#4DC962", undercurl = true })
hl(0, "DiagnosticVirtualTextError", { fg = "#EF9D9D", bg = "#244824" })
hl(0, "DiagnosticVirtualTextWarn", { fg = "#D9AA55", bg = "#21491C" })
hl(0, "DiagnosticVirtualTextInfo", { fg = "#3ACC53", bg = "#0E4D1C" })
hl(0, "DiagnosticVirtualTextHint", { fg = "#CED4D7", bg = "#204E2B" })
hl(0, "@variable", { fg = "#F0F2EE" })
hl(0, "@variable.builtin", { fg = "#E4E188", italic = true })
hl(0, "@variable.parameter", { fg = "#F0F2EE" })
hl(0, "@variable.member", { fg = "#F0F2EE" })
hl(0, "@constant", { fg = "#EBC2A6" })
hl(0, "@constant.builtin", { fg = "#E4E188" })
hl(0, "@constant.macro", { fg = "#E4E188" })
hl(0, "@module", { fg = "#96DBA1" })
hl(0, "@label", { fg = "#4DC962" })
hl(0, "@string", { fg = "#D9AA55" })
hl(0, "@string.documentation", { fg = "#D6DBDC" })
hl(0, "@string.escape", { fg = "#E4E188" })
hl(0, "@string.regexp", { fg = "#E4E188" })
hl(0, "@string.special", { fg = "#E4E188" })
hl(0, "@character", { fg = "#D9AA55" })
hl(0, "@character.special", { fg = "#E4E188" })
hl(0, "@boolean", { fg = "#EBC2A6" })
hl(0, "@number", { fg = "#EBC2A6" })
hl(0, "@number.float", { fg = "#EBC2A6" })
hl(0, "@type", { fg = "#96DBA1" })
hl(0, "@type.builtin", { fg = "#96DBA1", italic = true })
hl(0, "@type.definition", { fg = "#96DBA1" })
hl(0, "@attribute", { fg = "#E4E188" })
hl(0, "@attribute.builtin", { fg = "#E4E188" })
hl(0, "@property", { fg = "#F0F2EE" })
hl(0, "@function", { fg = "#ABB5BC" })
hl(0, "@function.builtin", { fg = "#E4E188" })
hl(0, "@function.macro", { fg = "#E4E188" })
hl(0, "@function.method", { fg = "#ABB5BC" })
hl(0, "@constructor", { fg = "#96DBA1" })
hl(0, "@operator", { fg = "#C2CEC2" })
hl(0, "@keyword", { fg = "#4DC962" })
hl(0, "@keyword.function", { fg = "#4DC962" })
hl(0, "@keyword.operator", { fg = "#4DC962" })
hl(0, "@keyword.import", { fg = "#4DC962" })
hl(0, "@keyword.return", { fg = "#4DC962" })
hl(0, "@keyword.exception", { fg = "#4DC962" })
hl(0, "@punctuation.delimiter", { fg = "#C2CEC2" })
hl(0, "@punctuation.bracket", { fg = "#C2CEC2" })
hl(0, "@punctuation.special", { fg = "#E4E188" })
hl(0, "@comment", { fg = "#D6DBDC", italic = true })
hl(0, "@comment.documentation", { fg = "#D6DBDC", italic = true })
hl(0, "@comment.error", { fg = "#083C14", bg = "#EF9D9D", bold = true })
hl(0, "@comment.warning", { fg = "#083C14", bg = "#D9AA55", bold = true })
hl(0, "@comment.todo", { link = "Todo" })
hl(0, "@comment.note", { fg = "#083C14", bg = "#3ACC53", bold = true })
hl(0, "@tag", { fg = "#4DC962" })
hl(0, "@tag.builtin", { fg = "#4DC962" })
hl(0, "@tag.attribute", { fg = "#ABB5BC", italic = true })
hl(0, "@tag.delimiter", { fg = "#C2CEC2" })
hl(0, "@markup.strong", { fg = "#F0F2EE", bold = true })
hl(0, "@markup.italic", { fg = "#F0F2EE", italic = true })
hl(0, "@markup.strikethrough", { fg = "#A5B7A7", strikethrough = true })
hl(0, "@markup.underline", { fg = "#F0F2EE", underline = true })
hl(0, "@markup.quote", { fg = "#A5B7A7", italic = true })
hl(0, "@markup.math", { fg = "#EBC2A6" })
hl(0, "@markup.link", { fg = "#ABB5BC" })
hl(0, "@markup.link.label", { fg = "#4DC962" })
hl(0, "@markup.link.url", { fg = "#ABB5BC", underline = true })
hl(0, "@markup.raw", { fg = "#D9AA55" })
hl(0, "@markup.list", { fg = "#4DC962" })
hl(0, "@markup.list.checked", { fg = "#4DC962" })
hl(0, "@markup.list.unchecked", { fg = "#A5B7A7" })
hl(0, "@diff.plus", { fg = "#4DC962" })
hl(0, "@diff.minus", { fg = "#EF9D9D" })
hl(0, "@diff.delta", { fg = "#D9AA55" })
hl(0, "@lsp.type.namespace", { link = "@module" })
hl(0, "@lsp.type.class", { link = "@type" })
hl(0, "@lsp.type.enum", { link = "@type" })
hl(0, "@lsp.type.interface", { link = "@type" })
hl(0, "@lsp.type.struct", { link = "@type" })
hl(0, "@lsp.type.parameter", { link = "@variable.parameter" })
hl(0, "@lsp.type.property", { link = "@property" })
hl(0, "@lsp.type.enumMember", { link = "@constant" })
hl(0, "@lsp.type.method", { link = "@function.method" })
hl(0, "MiniIconsAzure", { fg = "#ABB5BC" })
hl(0, "MiniIconsBlue", { fg = "#3ACC53" })
hl(0, "MiniIconsCyan", { fg = "#96DBA1" })
hl(0, "MiniIconsGreen", { fg = "#4DC962" })
hl(0, "MiniIconsGrey", { fg = "#A5B7A7" })
hl(0, "MiniIconsOrange", { fg = "#EBC2A6" })
hl(0, "MiniIconsPurple", { fg = "#E4E188" })
hl(0, "MiniIconsRed", { fg = "#EF9D9D" })
hl(0, "MiniIconsYellow", { fg = "#D9AA55" })
hl(0, "MiniFilesTitleFocused", { fg = "#4DC962", bg = "#1F4E2A", bold = true })
hl(0, "MiniFilesDirectory", { fg = "#ABB5BC" })
hl(0, "MiniFilesFile", { fg = "#F0F2EE" })
hl(0, "MiniFilesCursorLine", { bg = "#325D3B" })
hl(0, "MiniPickMatchCurrent", { bg = "#325D3B", bold = true })
hl(0, "MiniPickMatchRanges", { fg = "#4DC962", bold = true })
hl(0, "MiniPickPrompt", { fg = "#4DC962", bold = true })
hl(0, "MiniPickBorderText", { fg = "#4DC962" })
hl(0, "MiniClueDescGroup", { fg = "#96DBA1" })
hl(0, "MiniClueDescSingle", { fg = "#F0F2EE" })
hl(0, "MiniClueNextKey", { fg = "#4DC962", bold = true })
hl(0, "MiniClueTitle", { fg = "#4DC962", bg = "#1F4E2A", bold = true })
hl(0, "RenderMarkdownCode", { bg = "#1F4E2A" })
hl(0, "RenderMarkdownCodeInline", { fg = "#D9AA55", bg = "#1F4E2A" })
hl(0, "RenderMarkdownBullet", { fg = "#4DC962" })
hl(0, "RenderMarkdownQuote", { fg = "#A5B7A7" })
hl(0, "RenderMarkdownDash", { fg = "#739A7B" })
hl(0, "RenderMarkdownTableHead", { fg = "#96DBA1", bold = true })
hl(0, "RenderMarkdownTableRow", { fg = "#A5B7A7" })
hl(0, "RenderMarkdownLink", { fg = "#ABB5BC" })
hl(0, "RenderMarkdownChecked", { fg = "#4DC962" })
hl(0, "RenderMarkdownUnchecked", { fg = "#A5B7A7" })
hl(0, "@markup.heading.1", { fg = "#4DC962", bold = true })
hl(0, "RenderMarkdownH1", { fg = "#4DC962", bold = true })
hl(0, "RenderMarkdownH1Bg", { fg = "#4DC962", bg = "#125120", bold = true })
hl(0, "@markup.heading.2", { fg = "#ABB5BC", bold = true })
hl(0, "RenderMarkdownH2", { fg = "#ABB5BC", bold = true })
hl(0, "RenderMarkdownH2Bg", { fg = "#ABB5BC", bg = "#204E2D", bold = true })
hl(0, "@markup.heading.3", { fg = "#D9AA55", bold = true })
hl(0, "RenderMarkdownH3", { fg = "#D9AA55", bold = true })
hl(0, "RenderMarkdownH3Bg", { fg = "#D9AA55", bg = "#274C1E", bold = true })
hl(0, "@markup.heading.4", { fg = "#EBC2A6", bold = true })
hl(0, "RenderMarkdownH4", { fg = "#EBC2A6", bold = true })
hl(0, "RenderMarkdownH4Bg", { fg = "#EBC2A6", bg = "#2A502A", bold = true })
hl(0, "@markup.heading.5", { fg = "#96DBA1", bold = true })
hl(0, "RenderMarkdownH5", { fg = "#96DBA1", bold = true })
hl(0, "RenderMarkdownH5Bg", { fg = "#96DBA1", bg = "#1D5429", bold = true })
hl(0, "@markup.heading.6", { fg = "#E4E188", bold = true })
hl(0, "RenderMarkdownH6", { fg = "#E4E188", bold = true })
hl(0, "RenderMarkdownH6Bg", { fg = "#E4E188", bg = "#295525", bold = true })

vim.g.terminal_color_0 = "#426A4A"
vim.g.terminal_color_1 = "#EF9D9D"
vim.g.terminal_color_2 = "#4DC962"
vim.g.terminal_color_3 = "#D9AA55"
vim.g.terminal_color_4 = "#3ACC53"
vim.g.terminal_color_5 = "#E4E188"
vim.g.terminal_color_6 = "#4DC962"
vim.g.terminal_color_7 = "#A5B7A7"
vim.g.terminal_color_8 = "#708E76"
vim.g.terminal_color_9 = "#F2B1B1"
vim.g.terminal_color_10 = "#71D481"
vim.g.terminal_color_11 = "#E1BB77"
vim.g.terminal_color_12 = "#61D675"
vim.g.terminal_color_13 = "#E9E7A0"
vim.g.terminal_color_14 = "#71D481"
vim.g.terminal_color_15 = "#F0F2EE"
