-- retro-ascot - erzeugt von retro-coding-themes, nicht von Hand aendern.
-- Quelle: src/retro_coding_themes/data/ascot.json, Ableitung in derive.py.

vim.cmd("highlight clear")
if vim.fn.exists("syntax_on") == 1 then
  vim.cmd("syntax reset")
end

vim.o.background = "dark"
vim.g.colors_name = "retro-ascot"

local hl = vim.api.nvim_set_hl

hl(0, "Normal", { fg = "#F5EBD2", bg = "#173E2D" })
hl(0, "NormalNC", { link = "Normal" })
hl(0, "NormalFloat", { fg = "#F5EBD2", bg = "#2D4F3E" })
hl(0, "FloatBorder", { fg = "#849A86", bg = "#2D4F3E" })
hl(0, "FloatTitle", { fg = "#F2C200", bg = "#2D4F3E", bold = true })
hl(0, "ColorColumn", { bg = "#274A39" })
hl(0, "Conceal", { fg = "#8B9A88" })
hl(0, "Cursor", { fg = "#173E2D", bg = "#F5EBD2" })
hl(0, "lCursor", { link = "Cursor" })
hl(0, "TermCursor", { link = "Cursor" })
hl(0, "CursorLine", { bg = "#274A39" })
hl(0, "CursorColumn", { link = "CursorLine" })
hl(0, "CursorLineNr", { fg = "#F2C200", bold = true })
hl(0, "LineNr", { fg = "#8B9A88" })
hl(0, "SignColumn", { bg = "#173E2D" })
hl(0, "FoldColumn", { fg = "#8B9A88" })
hl(0, "Folded", { fg = "#B3B9A6", bg = "#2D4F3E" })
hl(0, "EndOfBuffer", { fg = "#173E2D" })
hl(0, "NonText", { fg = "#8B9A88" })
hl(0, "Whitespace", { fg = "#4E6956" })
hl(0, "SpecialKey", { fg = "#8B9A88" })
hl(0, "Visual", { bg = "#646C1D" })
hl(0, "VisualNOS", { link = "Visual" })
hl(0, "MatchParen", { fg = "#F2C200", bg = "#3F5D4B", bold = true })
hl(0, "Pmenu", { fg = "#F5EBD2", bg = "#2D4F3E" })
hl(0, "PmenuSel", { fg = "#F5EBD2", bg = "#3F5D4B", bold = true })
hl(0, "PmenuSbar", { bg = "#2D4F3E" })
hl(0, "PmenuThumb", { bg = "#849A86" })
hl(0, "PmenuKind", { fg = "#ADC031" })
hl(0, "PmenuKindSel", { fg = "#ADC031", bg = "#3F5D4B" })
hl(0, "PmenuExtra", { fg = "#8B9A88" })
hl(0, "PmenuExtraSel", { fg = "#8B9A88", bg = "#3F5D4B" })
hl(0, "WildMenu", { link = "PmenuSel" })
hl(0, "StatusLine", { fg = "#000000", bg = "#F2C200", bold = true })
hl(0, "StatusLineNC", { fg = "#B3B9A6", bg = "#2D4F3E" })
hl(0, "WinBar", { fg = "#B3B9A6", bg = "#173E2D" })
hl(0, "WinBarNC", { fg = "#8B9A88", bg = "#173E2D" })
hl(0, "WinSeparator", { fg = "#849A86" })
hl(0, "TabLine", { fg = "#B3B9A6", bg = "#2D4F3E" })
hl(0, "TabLineFill", { bg = "#173E2D" })
hl(0, "TabLineSel", { fg = "#000000", bg = "#F2C200", bold = true })
hl(0, "Search", { fg = "#F5EBD2", bg = "#646334" })
hl(0, "IncSearch", { fg = "#173E2D", bg = "#F2A742", bold = true })
hl(0, "CurSearch", { link = "IncSearch" })
hl(0, "Substitute", { fg = "#173E2D", bg = "#F1A2A8" })
hl(0, "QuickFixLine", { bg = "#3F5D4B", bold = true })
hl(0, "Directory", { fg = "#C0C5CC" })
hl(0, "Title", { fg = "#F2C200", bold = true })
hl(0, "Question", { fg = "#6CC996" })
hl(0, "MoreMsg", { fg = "#6CC996" })
hl(0, "ModeMsg", { fg = "#F5EBD2", bold = true })
hl(0, "MsgArea", { fg = "#F5EBD2", bg = "#173E2D" })
hl(0, "MsgSeparator", { fg = "#849A86" })
hl(0, "WarningMsg", { fg = "#F2C200" })
hl(0, "ErrorMsg", { fg = "#F1A2A8" })
hl(0, "SpellBad", { sp = "#F1A2A8", undercurl = true })
hl(0, "SpellCap", { sp = "#F2C200", undercurl = true })
hl(0, "SpellLocal", { sp = "#F2C200", undercurl = true })
hl(0, "SpellRare", { sp = "#D3D2CE", undercurl = true })
hl(0, "Comment", { fg = "#DBD8CF", italic = true })
hl(0, "Constant", { fg = "#F2A742" })
hl(0, "String", { fg = "#6CC996" })
hl(0, "Character", { fg = "#6CC996" })
hl(0, "Number", { fg = "#F2A742" })
hl(0, "Boolean", { fg = "#F2A742" })
hl(0, "Float", { fg = "#F2A742" })
hl(0, "Identifier", { fg = "#F5EBD2" })
hl(0, "Function", { fg = "#C0C5CC" })
hl(0, "Statement", { fg = "#F2C200" })
hl(0, "Conditional", { fg = "#F2C200" })
hl(0, "Repeat", { fg = "#F2C200" })
hl(0, "Label", { fg = "#F2C200" })
hl(0, "Operator", { fg = "#C9C8B1" })
hl(0, "Keyword", { fg = "#F2C200" })
hl(0, "Exception", { fg = "#F2C200" })
hl(0, "PreProc", { fg = "#F3B17A" })
hl(0, "Include", { fg = "#F2C200" })
hl(0, "Define", { fg = "#F3B17A" })
hl(0, "Macro", { fg = "#F3B17A" })
hl(0, "PreCondit", { fg = "#F3B17A" })
hl(0, "Type", { fg = "#ADC031" })
hl(0, "StorageClass", { fg = "#F2C200" })
hl(0, "Structure", { fg = "#ADC031" })
hl(0, "Typedef", { fg = "#ADC031" })
hl(0, "Special", { fg = "#F3B17A" })
hl(0, "SpecialChar", { fg = "#F3B17A" })
hl(0, "Tag", { fg = "#F2C200" })
hl(0, "Delimiter", { fg = "#C9C8B1" })
hl(0, "SpecialComment", { fg = "#DBD8CF", bold = true })
hl(0, "Debug", { fg = "#F1A2A8" })
hl(0, "Underlined", { fg = "#C0C5CC", underline = true })
hl(0, "Ignore", { fg = "#8B9A88" })
hl(0, "Error", { fg = "#F1A2A8", bold = true })
hl(0, "Todo", { fg = "#173E2D", bg = "#F2A742", bold = true })
hl(0, "Added", { fg = "#6CC996" })
hl(0, "Changed", { fg = "#F2C200" })
hl(0, "Removed", { fg = "#F1A2A8" })
hl(0, "DiffAdd", { bg = "#265740" })
hl(0, "DiffChange", { bg = "#314E28" })
hl(0, "DiffDelete", { bg = "#3E5043" })
hl(0, "DiffText", { bg = "#596620", bold = true })
hl(0, "DiagnosticError", { fg = "#F1A2A8" })
hl(0, "DiagnosticWarn", { fg = "#F2C200" })
hl(0, "DiagnosticInfo", { fg = "#F2C200" })
hl(0, "DiagnosticHint", { fg = "#D3D2CE" })
hl(0, "DiagnosticOk", { fg = "#6CC996" })
hl(0, "DiagnosticUnderlineError", { sp = "#F1A2A8", undercurl = true })
hl(0, "DiagnosticUnderlineWarn", { sp = "#F2C200", undercurl = true })
hl(0, "DiagnosticUnderlineInfo", { sp = "#F2C200", undercurl = true })
hl(0, "DiagnosticUnderlineHint", { sp = "#D3D2CE", undercurl = true })
hl(0, "DiagnosticUnderlineOk", { sp = "#6CC996", undercurl = true })
hl(0, "DiagnosticVirtualTextError", { fg = "#F1A2A8", bg = "#314A3C" })
hl(0, "DiagnosticVirtualTextWarn", { fg = "#F2C200", bg = "#314E28" })
hl(0, "DiagnosticVirtualTextInfo", { fg = "#F2C200", bg = "#314E28" })
hl(0, "DiagnosticVirtualTextHint", { fg = "#D3D2CE", bg = "#2E5040" })
hl(0, "@variable", { fg = "#F5EBD2" })
hl(0, "@variable.builtin", { fg = "#F3B17A", italic = true })
hl(0, "@variable.parameter", { fg = "#F5EBD2" })
hl(0, "@variable.member", { fg = "#F5EBD2" })
hl(0, "@constant", { fg = "#F2A742" })
hl(0, "@constant.builtin", { fg = "#F3B17A" })
hl(0, "@constant.macro", { fg = "#F3B17A" })
hl(0, "@module", { fg = "#ADC031" })
hl(0, "@label", { fg = "#F2C200" })
hl(0, "@string", { fg = "#6CC996" })
hl(0, "@string.documentation", { fg = "#DBD8CF" })
hl(0, "@string.escape", { fg = "#F3B17A" })
hl(0, "@string.regexp", { fg = "#F3B17A" })
hl(0, "@string.special", { fg = "#F3B17A" })
hl(0, "@character", { fg = "#6CC996" })
hl(0, "@character.special", { fg = "#F3B17A" })
hl(0, "@boolean", { fg = "#F2A742" })
hl(0, "@number", { fg = "#F2A742" })
hl(0, "@number.float", { fg = "#F2A742" })
hl(0, "@type", { fg = "#ADC031" })
hl(0, "@type.builtin", { fg = "#ADC031", italic = true })
hl(0, "@type.definition", { fg = "#ADC031" })
hl(0, "@attribute", { fg = "#F3B17A" })
hl(0, "@attribute.builtin", { fg = "#F3B17A" })
hl(0, "@property", { fg = "#F5EBD2" })
hl(0, "@function", { fg = "#C0C5CC" })
hl(0, "@function.builtin", { fg = "#F3B17A" })
hl(0, "@function.macro", { fg = "#F3B17A" })
hl(0, "@function.method", { fg = "#C0C5CC" })
hl(0, "@constructor", { fg = "#ADC031" })
hl(0, "@operator", { fg = "#C9C8B1" })
hl(0, "@keyword", { fg = "#F2C200" })
hl(0, "@keyword.function", { fg = "#F2C200" })
hl(0, "@keyword.operator", { fg = "#F2C200" })
hl(0, "@keyword.import", { fg = "#F2C200" })
hl(0, "@keyword.return", { fg = "#F2C200" })
hl(0, "@keyword.exception", { fg = "#F2C200" })
hl(0, "@punctuation.delimiter", { fg = "#C9C8B1" })
hl(0, "@punctuation.bracket", { fg = "#C9C8B1" })
hl(0, "@punctuation.special", { fg = "#F3B17A" })
hl(0, "@comment", { fg = "#DBD8CF", italic = true })
hl(0, "@comment.documentation", { fg = "#DBD8CF", italic = true })
hl(0, "@comment.error", { fg = "#173E2D", bg = "#F1A2A8", bold = true })
hl(0, "@comment.warning", { fg = "#173E2D", bg = "#F2C200", bold = true })
hl(0, "@comment.todo", { link = "Todo" })
hl(0, "@comment.note", { fg = "#173E2D", bg = "#F2C200", bold = true })
hl(0, "@tag", { fg = "#F2C200" })
hl(0, "@tag.builtin", { fg = "#F2C200" })
hl(0, "@tag.attribute", { fg = "#C0C5CC", italic = true })
hl(0, "@tag.delimiter", { fg = "#C9C8B1" })
hl(0, "@markup.strong", { fg = "#F5EBD2", bold = true })
hl(0, "@markup.italic", { fg = "#F5EBD2", italic = true })
hl(0, "@markup.strikethrough", { fg = "#B3B9A6", strikethrough = true })
hl(0, "@markup.underline", { fg = "#F5EBD2", underline = true })
hl(0, "@markup.quote", { fg = "#B3B9A6", italic = true })
hl(0, "@markup.math", { fg = "#F2A742" })
hl(0, "@markup.link", { fg = "#C0C5CC" })
hl(0, "@markup.link.label", { fg = "#F2C200" })
hl(0, "@markup.link.url", { fg = "#C0C5CC", underline = true })
hl(0, "@markup.raw", { fg = "#6CC996" })
hl(0, "@markup.list", { fg = "#F2C200" })
hl(0, "@markup.list.checked", { fg = "#6CC996" })
hl(0, "@markup.list.unchecked", { fg = "#B3B9A6" })
hl(0, "@diff.plus", { fg = "#6CC996" })
hl(0, "@diff.minus", { fg = "#F1A2A8" })
hl(0, "@diff.delta", { fg = "#F2C200" })
hl(0, "@lsp.type.namespace", { link = "@module" })
hl(0, "@lsp.type.class", { link = "@type" })
hl(0, "@lsp.type.enum", { link = "@type" })
hl(0, "@lsp.type.interface", { link = "@type" })
hl(0, "@lsp.type.struct", { link = "@type" })
hl(0, "@lsp.type.parameter", { link = "@variable.parameter" })
hl(0, "@lsp.type.property", { link = "@property" })
hl(0, "@lsp.type.enumMember", { link = "@constant" })
hl(0, "@lsp.type.method", { link = "@function.method" })
hl(0, "MiniIconsAzure", { fg = "#C0C5CC" })
hl(0, "MiniIconsBlue", { fg = "#F2C200" })
hl(0, "MiniIconsCyan", { fg = "#ADC031" })
hl(0, "MiniIconsGreen", { fg = "#6CC996" })
hl(0, "MiniIconsGrey", { fg = "#B3B9A6" })
hl(0, "MiniIconsOrange", { fg = "#F2A742" })
hl(0, "MiniIconsPurple", { fg = "#F3B17A" })
hl(0, "MiniIconsRed", { fg = "#F1A2A8" })
hl(0, "MiniIconsYellow", { fg = "#F2C200" })
hl(0, "MiniFilesTitleFocused", { fg = "#F2C200", bg = "#2D4F3E", bold = true })
hl(0, "MiniFilesDirectory", { fg = "#C0C5CC" })
hl(0, "MiniFilesFile", { fg = "#F5EBD2" })
hl(0, "MiniFilesCursorLine", { bg = "#3F5D4B" })
hl(0, "MiniPickMatchCurrent", { bg = "#3F5D4B", bold = true })
hl(0, "MiniPickMatchRanges", { fg = "#F2C200", bold = true })
hl(0, "MiniPickPrompt", { fg = "#F2C200", bold = true })
hl(0, "MiniPickBorderText", { fg = "#F2C200" })
hl(0, "MiniClueDescGroup", { fg = "#ADC031" })
hl(0, "MiniClueDescSingle", { fg = "#F5EBD2" })
hl(0, "MiniClueNextKey", { fg = "#F2C200", bold = true })
hl(0, "MiniClueTitle", { fg = "#F2C200", bg = "#2D4F3E", bold = true })
hl(0, "RenderMarkdownCode", { bg = "#2D4F3E" })
hl(0, "RenderMarkdownCodeInline", { fg = "#6CC996", bg = "#2D4F3E" })
hl(0, "RenderMarkdownBullet", { fg = "#F2C200" })
hl(0, "RenderMarkdownQuote", { fg = "#B3B9A6" })
hl(0, "RenderMarkdownDash", { fg = "#849A86" })
hl(0, "RenderMarkdownTableHead", { fg = "#ADC031", bold = true })
hl(0, "RenderMarkdownTableRow", { fg = "#B3B9A6" })
hl(0, "RenderMarkdownLink", { fg = "#C0C5CC" })
hl(0, "RenderMarkdownChecked", { fg = "#6CC996" })
hl(0, "RenderMarkdownUnchecked", { fg = "#B3B9A6" })
hl(0, "@markup.heading.1", { fg = "#F2C200", bold = true })
hl(0, "RenderMarkdownH1", { fg = "#F2C200", bold = true })
hl(0, "RenderMarkdownH1Bg", { fg = "#F2C200", bg = "#385226", bold = true })
hl(0, "@markup.heading.2", { fg = "#C0C5CC", bold = true })
hl(0, "RenderMarkdownH2", { fg = "#C0C5CC", bold = true })
hl(0, "RenderMarkdownH2Bg", { fg = "#C0C5CC", bg = "#305245", bold = true })
hl(0, "@markup.heading.3", { fg = "#6CC996", bold = true })
hl(0, "RenderMarkdownH3", { fg = "#6CC996", bold = true })
hl(0, "RenderMarkdownH3Bg", { fg = "#6CC996", bg = "#24533D", bold = true })
hl(0, "@markup.heading.4", { fg = "#F2A742", bold = true })
hl(0, "RenderMarkdownH4", { fg = "#F2A742", bold = true })
hl(0, "RenderMarkdownH4Bg", { fg = "#F2A742", bg = "#384E30", bold = true })
hl(0, "@markup.heading.5", { fg = "#ADC031", bold = true })
hl(0, "RenderMarkdownH5", { fg = "#ADC031", bold = true })
hl(0, "RenderMarkdownH5Bg", { fg = "#ADC031", bg = "#2E522E", bold = true })
hl(0, "@markup.heading.6", { fg = "#F3B17A", bold = true })
hl(0, "RenderMarkdownH6", { fg = "#F3B17A", bold = true })
hl(0, "RenderMarkdownH6Bg", { fg = "#F3B17A", bg = "#384F39", bold = true })

vim.g.terminal_color_0 = "#4E6956"
vim.g.terminal_color_1 = "#F1A2A8"
vim.g.terminal_color_2 = "#6CC996"
vim.g.terminal_color_3 = "#F2C200"
vim.g.terminal_color_4 = "#F2C200"
vim.g.terminal_color_5 = "#F3B17A"
vim.g.terminal_color_6 = "#F2C200"
vim.g.terminal_color_7 = "#B3B9A6"
vim.g.terminal_color_8 = "#7B8C77"
vim.g.terminal_color_9 = "#F4B5B9"
vim.g.terminal_color_10 = "#89D4AB"
vim.g.terminal_color_11 = "#F5CE33"
vim.g.terminal_color_12 = "#F5CE33"
vim.g.terminal_color_13 = "#F5C195"
vim.g.terminal_color_14 = "#F5CE33"
vim.g.terminal_color_15 = "#F5EBD2"
