-- retro-brotkasten - erzeugt von retro-coding-themes, nicht von Hand aendern.
-- Quelle: src/retro_coding_themes/data/brotkasten.json, Ableitung in derive.py.

vim.cmd("highlight clear")
if vim.fn.exists("syntax_on") == 1 then
  vim.cmd("syntax reset")
end

vim.o.background = "dark"
vim.g.colors_name = "retro-brotkasten"

local hl = vim.api.nvim_set_hl

hl(0, "Normal", { fg = "#D0CCFF", bg = "#33267A" })
hl(0, "NormalNC", { link = "Normal" })
hl(0, "NormalFloat", { fg = "#D0CCFF", bg = "#433787" })
hl(0, "FloatBorder", { fg = "#8F88BE", bg = "#433787" })
hl(0, "FloatTitle", { fg = "#EDF171", bg = "#433787", bold = true })
hl(0, "ColorColumn", { bg = "#3E3283" })
hl(0, "Conceal", { fg = "#9089C2" })
hl(0, "Cursor", { fg = "#33267A", bg = "#D0CCFF" })
hl(0, "lCursor", { link = "Cursor" })
hl(0, "TermCursor", { link = "Cursor" })
hl(0, "CursorLine", { bg = "#3E3283" })
hl(0, "CursorColumn", { link = "CursorLine" })
hl(0, "CursorLineNr", { fg = "#EDF171", bold = true })
hl(0, "LineNr", { fg = "#9089C2" })
hl(0, "SignColumn", { bg = "#33267A" })
hl(0, "FoldColumn", { fg = "#9089C2" })
hl(0, "Folded", { fg = "#B0ABDB", bg = "#433787" })
hl(0, "EndOfBuffer", { fg = "#33267A" })
hl(0, "NonText", { fg = "#9089C2" })
hl(0, "Whitespace", { fg = "#5A509B" })
hl(0, "SpecialKey", { fg = "#9089C2" })
hl(0, "Visual", { bg = "#5D5478" })
hl(0, "VisualNOS", { link = "Visual" })
hl(0, "MatchParen", { fg = "#EDF171", bg = "#4F4492", bold = true })
hl(0, "Pmenu", { fg = "#D0CCFF", bg = "#433787" })
hl(0, "PmenuSel", { fg = "#D0CCFF", bg = "#4F4492", bold = true })
hl(0, "PmenuSbar", { bg = "#433787" })
hl(0, "PmenuThumb", { bg = "#8F88BE" })
hl(0, "PmenuKind", { fg = "#92B8BC" })
hl(0, "PmenuKindSel", { fg = "#92B8BC", bg = "#4F4492" })
hl(0, "PmenuExtra", { fg = "#9089C2" })
hl(0, "PmenuExtraSel", { fg = "#9089C2", bg = "#4F4492" })
hl(0, "WildMenu", { link = "PmenuSel" })
hl(0, "StatusLine", { fg = "#000000", bg = "#7C70DA", bold = true })
hl(0, "StatusLineNC", { fg = "#B0ABDB", bg = "#433787" })
hl(0, "WinBar", { fg = "#B0ABDB", bg = "#33267A" })
hl(0, "WinBarNC", { fg = "#9089C2", bg = "#33267A" })
hl(0, "WinSeparator", { fg = "#8F88BE" })
hl(0, "TabLine", { fg = "#B0ABDB", bg = "#433787" })
hl(0, "TabLineFill", { bg = "#33267A" })
hl(0, "TabLineSel", { fg = "#000000", bg = "#7C70DA", bold = true })
hl(0, "Search", { fg = "#D0CCFF", bg = "#6F5D77" })
hl(0, "IncSearch", { fg = "#33267A", bg = "#DFC271", bold = true })
hl(0, "CurSearch", { link = "IncSearch" })
hl(0, "Substitute", { fg = "#33267A", bg = "#DAA3A6" })
hl(0, "QuickFixLine", { bg = "#4F4492", bold = true })
hl(0, "Directory", { fg = "#FFFFFF" })
hl(0, "Title", { fg = "#EDF171", bold = true })
hl(0, "Question", { fg = "#A9FF9F" })
hl(0, "MoreMsg", { fg = "#A9FF9F" })
hl(0, "ModeMsg", { fg = "#D0CCFF", bold = true })
hl(0, "MsgArea", { fg = "#D0CCFF", bg = "#33267A" })
hl(0, "MsgSeparator", { fg = "#8F88BE" })
hl(0, "WarningMsg", { fg = "#EDF171" })
hl(0, "ErrorMsg", { fg = "#DAA3A6" })
hl(0, "SpellBad", { sp = "#DAA3A6", undercurl = true })
hl(0, "SpellCap", { sp = "#EDF171", undercurl = true })
hl(0, "SpellLocal", { sp = "#B0A9E9", undercurl = true })
hl(0, "SpellRare", { sp = "#B1ABD6", undercurl = true })
hl(0, "Comment", { fg = "#B3ADDA", italic = true })
hl(0, "Constant", { fg = "#DFC271" })
hl(0, "String", { fg = "#A9FF9F" })
hl(0, "Character", { fg = "#A9FF9F" })
hl(0, "Number", { fg = "#DFC271" })
hl(0, "Boolean", { fg = "#DFC271" })
hl(0, "Float", { fg = "#DFC271" })
hl(0, "Identifier", { fg = "#D0CCFF" })
hl(0, "Function", { fg = "#FFFFFF" })
hl(0, "Statement", { fg = "#EDF171" })
hl(0, "Conditional", { fg = "#EDF171" })
hl(0, "Repeat", { fg = "#EDF171" })
hl(0, "Label", { fg = "#EDF171" })
hl(0, "Operator", { fg = "#B1ABE4" })
hl(0, "Keyword", { fg = "#EDF171" })
hl(0, "Exception", { fg = "#EDF171" })
hl(0, "PreProc", { fg = "#9FFFD5" })
hl(0, "Include", { fg = "#EDF171" })
hl(0, "Define", { fg = "#9FFFD5" })
hl(0, "Macro", { fg = "#9FFFD5" })
hl(0, "PreCondit", { fg = "#9FFFD5" })
hl(0, "Type", { fg = "#92B8BC" })
hl(0, "StorageClass", { fg = "#EDF171" })
hl(0, "Structure", { fg = "#92B8BC" })
hl(0, "Typedef", { fg = "#92B8BC" })
hl(0, "Special", { fg = "#9FFFD5" })
hl(0, "SpecialChar", { fg = "#9FFFD5" })
hl(0, "Tag", { fg = "#EDF171" })
hl(0, "Delimiter", { fg = "#B1ABE4" })
hl(0, "SpecialComment", { fg = "#B3ADDA", bold = true })
hl(0, "Debug", { fg = "#DAA3A6" })
hl(0, "Underlined", { fg = "#FFFFFF", underline = true })
hl(0, "Ignore", { fg = "#9089C2" })
hl(0, "Error", { fg = "#DAA3A6", bold = true })
hl(0, "Todo", { fg = "#33267A", bg = "#DFC271", bold = true })
hl(0, "Added", { fg = "#A9FF9F" })
hl(0, "Changed", { fg = "#EDF171" })
hl(0, "Removed", { fg = "#DAA3A6" })
hl(0, "DiffAdd", { bg = "#484D81" })
hl(0, "DiffChange", { bg = "#493E79" })
hl(0, "DiffDelete", { bg = "#513C82" })
hl(0, "DiffText", { bg = "#6B6377", bold = true })
hl(0, "DiagnosticError", { fg = "#DAA3A6" })
hl(0, "DiagnosticWarn", { fg = "#EDF171" })
hl(0, "DiagnosticInfo", { fg = "#B0A9E9" })
hl(0, "DiagnosticHint", { fg = "#B1ABD6" })
hl(0, "DiagnosticOk", { fg = "#A9FF9F" })
hl(0, "DiagnosticUnderlineError", { sp = "#DAA3A6", undercurl = true })
hl(0, "DiagnosticUnderlineWarn", { sp = "#EDF171", undercurl = true })
hl(0, "DiagnosticUnderlineInfo", { sp = "#B0A9E9", undercurl = true })
hl(0, "DiagnosticUnderlineHint", { sp = "#B1ABD6", undercurl = true })
hl(0, "DiagnosticUnderlineOk", { sp = "#A9FF9F", undercurl = true })
hl(0, "DiagnosticVirtualTextError", { fg = "#DAA3A6", bg = "#47357F" })
hl(0, "DiagnosticVirtualTextWarn", { fg = "#EDF171", bg = "#493E79" })
hl(0, "DiagnosticVirtualTextInfo", { fg = "#B0A9E9", bg = "#423687" })
hl(0, "DiagnosticVirtualTextHint", { fg = "#B1ABD6", bg = "#423685" })
hl(0, "@variable", { fg = "#D0CCFF" })
hl(0, "@variable.builtin", { fg = "#9FFFD5", italic = true })
hl(0, "@variable.parameter", { fg = "#D0CCFF" })
hl(0, "@variable.member", { fg = "#D0CCFF" })
hl(0, "@constant", { fg = "#DFC271" })
hl(0, "@constant.builtin", { fg = "#9FFFD5" })
hl(0, "@constant.macro", { fg = "#9FFFD5" })
hl(0, "@module", { fg = "#92B8BC" })
hl(0, "@label", { fg = "#EDF171" })
hl(0, "@string", { fg = "#A9FF9F" })
hl(0, "@string.documentation", { fg = "#B3ADDA" })
hl(0, "@string.escape", { fg = "#9FFFD5" })
hl(0, "@string.regexp", { fg = "#9FFFD5" })
hl(0, "@string.special", { fg = "#9FFFD5" })
hl(0, "@character", { fg = "#A9FF9F" })
hl(0, "@character.special", { fg = "#9FFFD5" })
hl(0, "@boolean", { fg = "#DFC271" })
hl(0, "@number", { fg = "#DFC271" })
hl(0, "@number.float", { fg = "#DFC271" })
hl(0, "@type", { fg = "#92B8BC" })
hl(0, "@type.builtin", { fg = "#92B8BC", italic = true })
hl(0, "@type.definition", { fg = "#92B8BC" })
hl(0, "@attribute", { fg = "#9FFFD5" })
hl(0, "@attribute.builtin", { fg = "#9FFFD5" })
hl(0, "@property", { fg = "#D0CCFF" })
hl(0, "@function", { fg = "#FFFFFF" })
hl(0, "@function.builtin", { fg = "#9FFFD5" })
hl(0, "@function.macro", { fg = "#9FFFD5" })
hl(0, "@function.method", { fg = "#FFFFFF" })
hl(0, "@constructor", { fg = "#92B8BC" })
hl(0, "@operator", { fg = "#B1ABE4" })
hl(0, "@keyword", { fg = "#EDF171" })
hl(0, "@keyword.function", { fg = "#EDF171" })
hl(0, "@keyword.operator", { fg = "#EDF171" })
hl(0, "@keyword.import", { fg = "#EDF171" })
hl(0, "@keyword.return", { fg = "#EDF171" })
hl(0, "@keyword.exception", { fg = "#EDF171" })
hl(0, "@punctuation.delimiter", { fg = "#B1ABE4" })
hl(0, "@punctuation.bracket", { fg = "#B1ABE4" })
hl(0, "@punctuation.special", { fg = "#9FFFD5" })
hl(0, "@comment", { fg = "#B3ADDA", italic = true })
hl(0, "@comment.documentation", { fg = "#B3ADDA", italic = true })
hl(0, "@comment.error", { fg = "#33267A", bg = "#DAA3A6", bold = true })
hl(0, "@comment.warning", { fg = "#33267A", bg = "#EDF171", bold = true })
hl(0, "@comment.todo", { link = "Todo" })
hl(0, "@comment.note", { fg = "#33267A", bg = "#B0A9E9", bold = true })
hl(0, "@tag", { fg = "#EDF171" })
hl(0, "@tag.builtin", { fg = "#EDF171" })
hl(0, "@tag.attribute", { fg = "#FFFFFF", italic = true })
hl(0, "@tag.delimiter", { fg = "#B1ABE4" })
hl(0, "@markup.strong", { fg = "#D0CCFF", bold = true })
hl(0, "@markup.italic", { fg = "#D0CCFF", italic = true })
hl(0, "@markup.strikethrough", { fg = "#B0ABDB", strikethrough = true })
hl(0, "@markup.underline", { fg = "#D0CCFF", underline = true })
hl(0, "@markup.quote", { fg = "#B0ABDB", italic = true })
hl(0, "@markup.math", { fg = "#DFC271" })
hl(0, "@markup.link", { fg = "#FFFFFF" })
hl(0, "@markup.link.label", { fg = "#EDF171" })
hl(0, "@markup.link.url", { fg = "#FFFFFF", underline = true })
hl(0, "@markup.raw", { fg = "#A9FF9F" })
hl(0, "@markup.list", { fg = "#EDF171" })
hl(0, "@markup.list.checked", { fg = "#A9FF9F" })
hl(0, "@markup.list.unchecked", { fg = "#B0ABDB" })
hl(0, "@diff.plus", { fg = "#A9FF9F" })
hl(0, "@diff.minus", { fg = "#DAA3A6" })
hl(0, "@diff.delta", { fg = "#EDF171" })
hl(0, "@lsp.type.namespace", { link = "@module" })
hl(0, "@lsp.type.class", { link = "@type" })
hl(0, "@lsp.type.enum", { link = "@type" })
hl(0, "@lsp.type.interface", { link = "@type" })
hl(0, "@lsp.type.struct", { link = "@type" })
hl(0, "@lsp.type.parameter", { link = "@variable.parameter" })
hl(0, "@lsp.type.property", { link = "@property" })
hl(0, "@lsp.type.enumMember", { link = "@constant" })
hl(0, "@lsp.type.method", { link = "@function.method" })
hl(0, "MiniIconsAzure", { fg = "#FFFFFF" })
hl(0, "MiniIconsBlue", { fg = "#B0A9E9" })
hl(0, "MiniIconsCyan", { fg = "#92B8BC" })
hl(0, "MiniIconsGreen", { fg = "#A9FF9F" })
hl(0, "MiniIconsGrey", { fg = "#B0ABDB" })
hl(0, "MiniIconsOrange", { fg = "#DFC271" })
hl(0, "MiniIconsPurple", { fg = "#9FFFD5" })
hl(0, "MiniIconsRed", { fg = "#DAA3A6" })
hl(0, "MiniIconsYellow", { fg = "#EDF171" })
hl(0, "MiniFilesTitleFocused", { fg = "#EDF171", bg = "#433787", bold = true })
hl(0, "MiniFilesDirectory", { fg = "#FFFFFF" })
hl(0, "MiniFilesFile", { fg = "#D0CCFF" })
hl(0, "MiniFilesCursorLine", { bg = "#4F4492" })
hl(0, "MiniPickMatchCurrent", { bg = "#4F4492", bold = true })
hl(0, "MiniPickMatchRanges", { fg = "#EDF171", bold = true })
hl(0, "MiniPickPrompt", { fg = "#EDF171", bold = true })
hl(0, "MiniPickBorderText", { fg = "#EDF171" })
hl(0, "MiniClueDescGroup", { fg = "#92B8BC" })
hl(0, "MiniClueDescSingle", { fg = "#D0CCFF" })
hl(0, "MiniClueNextKey", { fg = "#EDF171", bold = true })
hl(0, "MiniClueTitle", { fg = "#EDF171", bg = "#433787", bold = true })
hl(0, "RenderMarkdownCode", { bg = "#433787" })
hl(0, "RenderMarkdownCodeInline", { fg = "#A9FF9F", bg = "#433787" })
hl(0, "RenderMarkdownBullet", { fg = "#EDF171" })
hl(0, "RenderMarkdownQuote", { fg = "#B0ABDB" })
hl(0, "RenderMarkdownDash", { fg = "#8F88BE" })
hl(0, "RenderMarkdownTableHead", { fg = "#92B8BC", bold = true })
hl(0, "RenderMarkdownTableRow", { fg = "#B0ABDB" })
hl(0, "RenderMarkdownLink", { fg = "#FFFFFF" })
hl(0, "RenderMarkdownChecked", { fg = "#A9FF9F" })
hl(0, "RenderMarkdownUnchecked", { fg = "#B0ABDB" })
hl(0, "@markup.heading.1", { fg = "#EDF171", bold = true })
hl(0, "RenderMarkdownH1", { fg = "#EDF171", bold = true })
hl(0, "RenderMarkdownH1Bg", { fg = "#EDF171", bg = "#4F4479", bold = true })
hl(0, "@markup.heading.2", { fg = "#FFFFFF", bold = true })
hl(0, "RenderMarkdownH2", { fg = "#FFFFFF", bold = true })
hl(0, "RenderMarkdownH2Bg", { fg = "#FFFFFF", bg = "#52478E", bold = true })
hl(0, "@markup.heading.3", { fg = "#A9FF9F", bold = true })
hl(0, "RenderMarkdownH3", { fg = "#A9FF9F", bold = true })
hl(0, "RenderMarkdownH3Bg", { fg = "#A9FF9F", bg = "#454780", bold = true })
hl(0, "@markup.heading.4", { fg = "#DFC271", bold = true })
hl(0, "RenderMarkdownH4", { fg = "#DFC271", bold = true })
hl(0, "RenderMarkdownH4Bg", { fg = "#DFC271", bg = "#4D3D79", bold = true })
hl(0, "@markup.heading.5", { fg = "#92B8BC", bold = true })
hl(0, "RenderMarkdownH5", { fg = "#92B8BC", bold = true })
hl(0, "RenderMarkdownH5Bg", { fg = "#92B8BC", bg = "#413C84", bold = true })
hl(0, "@markup.heading.6", { fg = "#9FFFD5", bold = true })
hl(0, "RenderMarkdownH6", { fg = "#9FFFD5", bold = true })
hl(0, "RenderMarkdownH6Bg", { fg = "#9FFFD5", bg = "#434788", bold = true })

vim.g.terminal_color_0 = "#5A509B"
vim.g.terminal_color_1 = "#DAA3A6"
vim.g.terminal_color_2 = "#A9FF9F"
vim.g.terminal_color_3 = "#EDF171"
vim.g.terminal_color_4 = "#B0A9E9"
vim.g.terminal_color_5 = "#9FFFD5"
vim.g.terminal_color_6 = "#EDF171"
vim.g.terminal_color_7 = "#B0ABDB"
vim.g.terminal_color_8 = "#7A71B6"
vim.g.terminal_color_9 = "#E1B5B8"
vim.g.terminal_color_10 = "#BAFFB2"
vim.g.terminal_color_11 = "#F1F48D"
vim.g.terminal_color_12 = "#C0BAED"
vim.g.terminal_color_13 = "#B2FFDD"
vim.g.terminal_color_14 = "#F1F48D"
vim.g.terminal_color_15 = "#D0CCFF"
