-- retro-warp - erzeugt von retro-coding-themes, nicht von Hand aendern.
-- Quelle: src/retro_coding_themes/data/warp.json, Ableitung in derive.py.

vim.cmd("highlight clear")
if vim.fn.exists("syntax_on") == 1 then
  vim.cmd("syntax reset")
end

vim.o.background = "dark"
vim.g.colors_name = "retro-warp"

local hl = vim.api.nvim_set_hl

hl(0, "Normal", { fg = "#D0D0D0", bg = "#1A1A4E" })
hl(0, "NormalNC", { link = "Normal" })
hl(0, "NormalFloat", { fg = "#D0D0D0", bg = "#2C2C5B" })
hl(0, "FloatBorder", { fg = "#77779C", bg = "#2C2C5B" })
hl(0, "FloatTitle", { fg = "#00BBBB", bg = "#2C2C5B", bold = true })
hl(0, "ColorColumn", { bg = "#272757" })
hl(0, "Conceal", { fg = "#797995" })
hl(0, "Cursor", { fg = "#1A1A4E", bg = "#D0D0D0" })
hl(0, "lCursor", { link = "Cursor" })
hl(0, "TermCursor", { link = "Cursor" })
hl(0, "CursorLine", { bg = "#272757" })
hl(0, "CursorColumn", { link = "CursorLine" })
hl(0, "CursorLineNr", { fg = "#00BBBB", bold = true })
hl(0, "LineNr", { fg = "#797995" })
hl(0, "SignColumn", { bg = "#1A1A4E" })
hl(0, "FoldColumn", { fg = "#797995" })
hl(0, "Folded", { fg = "#9898A9", bg = "#2C2C5B" })
hl(0, "EndOfBuffer", { fg = "#1A1A4E" })
hl(0, "NonText", { fg = "#797995" })
hl(0, "Whitespace", { fg = "#48486E" })
hl(0, "SpecialKey", { fg = "#797995" })
hl(0, "Visual", { bg = "#115274" })
hl(0, "VisualNOS", { link = "Visual" })
hl(0, "MatchParen", { fg = "#00BBBB", bg = "#3B3B65", bold = true })
hl(0, "Pmenu", { fg = "#D0D0D0", bg = "#2C2C5B" })
hl(0, "PmenuSel", { fg = "#D0D0D0", bg = "#3B3B65", bold = true })
hl(0, "PmenuSbar", { bg = "#2C2C5B" })
hl(0, "PmenuThumb", { bg = "#77779C" })
hl(0, "PmenuKind", { fg = "#22BB90" })
hl(0, "PmenuKindSel", { fg = "#22BB90", bg = "#3B3B65" })
hl(0, "PmenuExtra", { fg = "#797995" })
hl(0, "PmenuExtraSel", { fg = "#797995", bg = "#3B3B65" })
hl(0, "WildMenu", { link = "PmenuSel" })
hl(0, "StatusLine", { fg = "#000000", bg = "#00BBBB", bold = true })
hl(0, "StatusLineNC", { fg = "#9898A9", bg = "#2C2C5B" })
hl(0, "WinBar", { fg = "#9898A9", bg = "#1A1A4E" })
hl(0, "WinBarNC", { fg = "#797995", bg = "#1A1A4E" })
hl(0, "WinSeparator", { fg = "#77779C" })
hl(0, "TabLine", { fg = "#9898A9", bg = "#2C2C5B" })
hl(0, "TabLineFill", { bg = "#1A1A4E" })
hl(0, "TabLineSel", { fg = "#000000", bg = "#00BBBB", bold = true })
hl(0, "Search", { fg = "#D0D0D0", bg = "#5E4C3F" })
hl(0, "IncSearch", { fg = "#1A1A4E", bg = "#DDAA22", bold = true })
hl(0, "CurSearch", { link = "IncSearch" })
hl(0, "Substitute", { fg = "#1A1A4E", bg = "#E67878" })
hl(0, "QuickFixLine", { bg = "#3B3B65", bold = true })
hl(0, "Directory", { fg = "#9292DE" })
hl(0, "Title", { fg = "#00BBBB", bold = true })
hl(0, "Question", { fg = "#44BB66" })
hl(0, "MoreMsg", { fg = "#44BB66" })
hl(0, "ModeMsg", { fg = "#D0D0D0", bold = true })
hl(0, "MsgArea", { fg = "#D0D0D0", bg = "#1A1A4E" })
hl(0, "MsgSeparator", { fg = "#77779C" })
hl(0, "WarningMsg", { fg = "#DDAA22" })
hl(0, "ErrorMsg", { fg = "#E67878" })
hl(0, "SpellBad", { sp = "#E67878", undercurl = true })
hl(0, "SpellCap", { sp = "#DDAA22", undercurl = true })
hl(0, "SpellLocal", { sp = "#00BBBB", undercurl = true })
hl(0, "SpellRare", { sp = "#9797CD", undercurl = true })
hl(0, "Comment", { fg = "#9696C8", italic = true })
hl(0, "Constant", { fg = "#DDAA22" })
hl(0, "String", { fg = "#44BB66" })
hl(0, "Character", { fg = "#44BB66" })
hl(0, "Number", { fg = "#DDAA22" })
hl(0, "Boolean", { fg = "#DDAA22" })
hl(0, "Float", { fg = "#DDAA22" })
hl(0, "Identifier", { fg = "#D0D0D0" })
hl(0, "Function", { fg = "#9292DE" })
hl(0, "Statement", { fg = "#00BBBB" })
hl(0, "Conditional", { fg = "#00BBBB" })
hl(0, "Repeat", { fg = "#00BBBB" })
hl(0, "Label", { fg = "#00BBBB" })
hl(0, "Operator", { fg = "#ACACB6" })
hl(0, "Keyword", { fg = "#00BBBB" })
hl(0, "Exception", { fg = "#00BBBB" })
hl(0, "PreProc", { fg = "#DF8040" })
hl(0, "Include", { fg = "#00BBBB" })
hl(0, "Define", { fg = "#DF8040" })
hl(0, "Macro", { fg = "#DF8040" })
hl(0, "PreCondit", { fg = "#DF8040" })
hl(0, "Type", { fg = "#22BB90" })
hl(0, "StorageClass", { fg = "#00BBBB" })
hl(0, "Structure", { fg = "#22BB90" })
hl(0, "Typedef", { fg = "#22BB90" })
hl(0, "Special", { fg = "#DF8040" })
hl(0, "SpecialChar", { fg = "#DF8040" })
hl(0, "Tag", { fg = "#00BBBB" })
hl(0, "Delimiter", { fg = "#ACACB6" })
hl(0, "SpecialComment", { fg = "#9696C8", bold = true })
hl(0, "Debug", { fg = "#E67878" })
hl(0, "Underlined", { fg = "#9292DE", underline = true })
hl(0, "Ignore", { fg = "#797995" })
hl(0, "Error", { fg = "#E67878", bold = true })
hl(0, "Todo", { fg = "#1A1A4E", bg = "#DDAA22", bold = true })
hl(0, "Added", { fg = "#44BB66" })
hl(0, "Changed", { fg = "#DDAA22" })
hl(0, "Removed", { fg = "#E67878" })
hl(0, "DiffAdd", { bg = "#223752" })
hl(0, "DiffChange", { bg = "#312B49" })
hl(0, "DiffDelete", { bg = "#3F2B56" })
hl(0, "DiffText", { bg = "#554541", bold = true })
hl(0, "DiagnosticError", { fg = "#E67878" })
hl(0, "DiagnosticWarn", { fg = "#DDAA22" })
hl(0, "DiagnosticInfo", { fg = "#00BBBB" })
hl(0, "DiagnosticHint", { fg = "#9797CD" })
hl(0, "DiagnosticOk", { fg = "#44BB66" })
hl(0, "DiagnosticUnderlineError", { sp = "#E67878", undercurl = true })
hl(0, "DiagnosticUnderlineWarn", { sp = "#DDAA22", undercurl = true })
hl(0, "DiagnosticUnderlineInfo", { sp = "#00BBBB", undercurl = true })
hl(0, "DiagnosticUnderlineHint", { sp = "#9797CD", undercurl = true })
hl(0, "DiagnosticUnderlineOk", { sp = "#44BB66", undercurl = true })
hl(0, "DiagnosticVirtualTextError", { fg = "#E67878", bg = "#322553" })
hl(0, "DiagnosticVirtualTextWarn", { fg = "#DDAA22", bg = "#312B49" })
hl(0, "DiagnosticVirtualTextInfo", { fg = "#00BBBB", bg = "#172D5B" })
hl(0, "DiagnosticVirtualTextHint", { fg = "#9797CD", bg = "#29295D" })
hl(0, "@variable", { fg = "#D0D0D0" })
hl(0, "@variable.builtin", { fg = "#DF8040", italic = true })
hl(0, "@variable.parameter", { fg = "#D0D0D0" })
hl(0, "@variable.member", { fg = "#D0D0D0" })
hl(0, "@constant", { fg = "#DDAA22" })
hl(0, "@constant.builtin", { fg = "#DF8040" })
hl(0, "@constant.macro", { fg = "#DF8040" })
hl(0, "@module", { fg = "#22BB90" })
hl(0, "@label", { fg = "#00BBBB" })
hl(0, "@string", { fg = "#44BB66" })
hl(0, "@string.documentation", { fg = "#9696C8" })
hl(0, "@string.escape", { fg = "#DF8040" })
hl(0, "@string.regexp", { fg = "#DF8040" })
hl(0, "@string.special", { fg = "#DF8040" })
hl(0, "@character", { fg = "#44BB66" })
hl(0, "@character.special", { fg = "#DF8040" })
hl(0, "@boolean", { fg = "#DDAA22" })
hl(0, "@number", { fg = "#DDAA22" })
hl(0, "@number.float", { fg = "#DDAA22" })
hl(0, "@type", { fg = "#22BB90" })
hl(0, "@type.builtin", { fg = "#22BB90", italic = true })
hl(0, "@type.definition", { fg = "#22BB90" })
hl(0, "@attribute", { fg = "#DF8040" })
hl(0, "@attribute.builtin", { fg = "#DF8040" })
hl(0, "@property", { fg = "#D0D0D0" })
hl(0, "@function", { fg = "#9292DE" })
hl(0, "@function.builtin", { fg = "#DF8040" })
hl(0, "@function.macro", { fg = "#DF8040" })
hl(0, "@function.method", { fg = "#9292DE" })
hl(0, "@constructor", { fg = "#22BB90" })
hl(0, "@operator", { fg = "#ACACB6" })
hl(0, "@keyword", { fg = "#00BBBB" })
hl(0, "@keyword.function", { fg = "#00BBBB" })
hl(0, "@keyword.operator", { fg = "#00BBBB" })
hl(0, "@keyword.import", { fg = "#00BBBB" })
hl(0, "@keyword.return", { fg = "#00BBBB" })
hl(0, "@keyword.exception", { fg = "#00BBBB" })
hl(0, "@punctuation.delimiter", { fg = "#ACACB6" })
hl(0, "@punctuation.bracket", { fg = "#ACACB6" })
hl(0, "@punctuation.special", { fg = "#DF8040" })
hl(0, "@comment", { fg = "#9696C8", italic = true })
hl(0, "@comment.documentation", { fg = "#9696C8", italic = true })
hl(0, "@comment.error", { fg = "#1A1A4E", bg = "#E67878", bold = true })
hl(0, "@comment.warning", { fg = "#1A1A4E", bg = "#DDAA22", bold = true })
hl(0, "@comment.todo", { link = "Todo" })
hl(0, "@comment.note", { fg = "#1A1A4E", bg = "#00BBBB", bold = true })
hl(0, "@tag", { fg = "#00BBBB" })
hl(0, "@tag.builtin", { fg = "#00BBBB" })
hl(0, "@tag.attribute", { fg = "#9292DE", italic = true })
hl(0, "@tag.delimiter", { fg = "#ACACB6" })
hl(0, "@markup.strong", { fg = "#D0D0D0", bold = true })
hl(0, "@markup.italic", { fg = "#D0D0D0", italic = true })
hl(0, "@markup.strikethrough", { fg = "#9898A9", strikethrough = true })
hl(0, "@markup.underline", { fg = "#D0D0D0", underline = true })
hl(0, "@markup.quote", { fg = "#9898A9", italic = true })
hl(0, "@markup.math", { fg = "#DDAA22" })
hl(0, "@markup.link", { fg = "#9292DE" })
hl(0, "@markup.link.label", { fg = "#00BBBB" })
hl(0, "@markup.link.url", { fg = "#9292DE", underline = true })
hl(0, "@markup.raw", { fg = "#44BB66" })
hl(0, "@markup.list", { fg = "#00BBBB" })
hl(0, "@markup.list.checked", { fg = "#44BB66" })
hl(0, "@markup.list.unchecked", { fg = "#9898A9" })
hl(0, "@diff.plus", { fg = "#44BB66" })
hl(0, "@diff.minus", { fg = "#E67878" })
hl(0, "@diff.delta", { fg = "#DDAA22" })
hl(0, "@lsp.type.namespace", { link = "@module" })
hl(0, "@lsp.type.class", { link = "@type" })
hl(0, "@lsp.type.enum", { link = "@type" })
hl(0, "@lsp.type.interface", { link = "@type" })
hl(0, "@lsp.type.struct", { link = "@type" })
hl(0, "@lsp.type.parameter", { link = "@variable.parameter" })
hl(0, "@lsp.type.property", { link = "@property" })
hl(0, "@lsp.type.enumMember", { link = "@constant" })
hl(0, "@lsp.type.method", { link = "@function.method" })
hl(0, "MiniIconsAzure", { fg = "#9292DE" })
hl(0, "MiniIconsBlue", { fg = "#00BBBB" })
hl(0, "MiniIconsCyan", { fg = "#22BB90" })
hl(0, "MiniIconsGreen", { fg = "#44BB66" })
hl(0, "MiniIconsGrey", { fg = "#9898A9" })
hl(0, "MiniIconsOrange", { fg = "#DDAA22" })
hl(0, "MiniIconsPurple", { fg = "#DF8040" })
hl(0, "MiniIconsRed", { fg = "#E67878" })
hl(0, "MiniIconsYellow", { fg = "#DDAA22" })
hl(0, "MiniFilesTitleFocused", { fg = "#00BBBB", bg = "#2C2C5B", bold = true })
hl(0, "MiniFilesDirectory", { fg = "#9292DE" })
hl(0, "MiniFilesFile", { fg = "#D0D0D0" })
hl(0, "MiniFilesCursorLine", { bg = "#3B3B65" })
hl(0, "MiniPickMatchCurrent", { bg = "#3B3B65", bold = true })
hl(0, "MiniPickMatchRanges", { fg = "#00BBBB", bold = true })
hl(0, "MiniPickPrompt", { fg = "#00BBBB", bold = true })
hl(0, "MiniPickBorderText", { fg = "#00BBBB" })
hl(0, "MiniClueDescGroup", { fg = "#22BB90" })
hl(0, "MiniClueDescSingle", { fg = "#D0D0D0" })
hl(0, "MiniClueNextKey", { fg = "#00BBBB", bold = true })
hl(0, "MiniClueTitle", { fg = "#00BBBB", bg = "#2C2C5B", bold = true })
hl(0, "RenderMarkdownCode", { bg = "#2C2C5B" })
hl(0, "RenderMarkdownCodeInline", { fg = "#44BB66", bg = "#2C2C5B" })
hl(0, "RenderMarkdownBullet", { fg = "#00BBBB" })
hl(0, "RenderMarkdownQuote", { fg = "#9898A9" })
hl(0, "RenderMarkdownDash", { fg = "#77779C" })
hl(0, "RenderMarkdownTableHead", { fg = "#22BB90", bold = true })
hl(0, "RenderMarkdownTableRow", { fg = "#9898A9" })
hl(0, "RenderMarkdownLink", { fg = "#9292DE" })
hl(0, "RenderMarkdownChecked", { fg = "#44BB66" })
hl(0, "RenderMarkdownUnchecked", { fg = "#9898A9" })
hl(0, "@markup.heading.1", { fg = "#00BBBB", bold = true })
hl(0, "RenderMarkdownH1", { fg = "#00BBBB", bold = true })
hl(0, "RenderMarkdownH1Bg", { fg = "#00BBBB", bg = "#16325E", bold = true })
hl(0, "@markup.heading.2", { fg = "#9292DE", bold = true })
hl(0, "RenderMarkdownH2", { fg = "#9292DE", bold = true })
hl(0, "RenderMarkdownH2Bg", { fg = "#9292DE", bg = "#2C2C64", bold = true })
hl(0, "@markup.heading.3", { fg = "#44BB66", bold = true })
hl(0, "RenderMarkdownH3", { fg = "#44BB66", bold = true })
hl(0, "RenderMarkdownH3Bg", { fg = "#44BB66", bg = "#203252", bold = true })
hl(0, "@markup.heading.4", { fg = "#DDAA22", bold = true })
hl(0, "RenderMarkdownH4", { fg = "#DDAA22", bold = true })
hl(0, "RenderMarkdownH4Bg", { fg = "#DDAA22", bg = "#373047", bold = true })
hl(0, "@markup.heading.5", { fg = "#22BB90", bold = true })
hl(0, "RenderMarkdownH5", { fg = "#22BB90", bold = true })
hl(0, "RenderMarkdownH5Bg", { fg = "#22BB90", bg = "#1B3258", bold = true })
hl(0, "@markup.heading.6", { fg = "#DF8040", bold = true })
hl(0, "RenderMarkdownH6", { fg = "#DF8040", bold = true })
hl(0, "RenderMarkdownH6Bg", { fg = "#DF8040", bg = "#38294C", bold = true })

vim.g.terminal_color_0 = "#48486E"
vim.g.terminal_color_1 = "#E67878"
vim.g.terminal_color_2 = "#44BB66"
vim.g.terminal_color_3 = "#DDAA22"
vim.g.terminal_color_4 = "#00BBBB"
vim.g.terminal_color_5 = "#DF8040"
vim.g.terminal_color_6 = "#00BBBB"
vim.g.terminal_color_7 = "#9898A9"
vim.g.terminal_color_8 = "#6C6C88"
vim.g.terminal_color_9 = "#EB9393"
vim.g.terminal_color_10 = "#69C985"
vim.g.terminal_color_11 = "#E4BB4E"
vim.g.terminal_color_12 = "#33C9C9"
vim.g.terminal_color_13 = "#E59966"
vim.g.terminal_color_14 = "#33C9C9"
vim.g.terminal_color_15 = "#D0D0D0"
