-- retro-joker - erzeugt von retro-coding-themes, nicht von Hand aendern.
-- Quelle: src/retro_coding_themes/data/joker.json, Ableitung in derive.py.

vim.cmd("highlight clear")
if vim.fn.exists("syntax_on") == 1 then
  vim.cmd("syntax reset")
end

vim.o.background = "dark"
vim.g.colors_name = "retro-joker"

local hl = vim.api.nvim_set_hl

hl(0, "Normal", { fg = "#F5F0E5", bg = "#0E0824" })
hl(0, "NormalNC", { link = "Normal" })
hl(0, "NormalFloat", { fg = "#F5F0E5", bg = "#251F37" })
hl(0, "FloatBorder", { fg = "#71697B", bg = "#251F37" })
hl(0, "FloatTitle", { fg = "#FFC72C", bg = "#251F37", bold = true })
hl(0, "ColorColumn", { bg = "#1E1832" })
hl(0, "Conceal", { fg = "#76707B" })
hl(0, "Cursor", { fg = "#0E0824", bg = "#F5F0E5" })
hl(0, "lCursor", { link = "Cursor" })
hl(0, "TermCursor", { link = "Cursor" })
hl(0, "CursorLine", { bg = "#1E1832" })
hl(0, "CursorColumn", { link = "CursorLine" })
hl(0, "CursorLineNr", { fg = "#FFC72C", bold = true })
hl(0, "LineNr", { fg = "#76707B" })
hl(0, "SignColumn", { bg = "#0E0824" })
hl(0, "FoldColumn", { fg = "#76707B" })
hl(0, "Folded", { fg = "#A49FA1", bg = "#251F37" })
hl(0, "EndOfBuffer", { fg = "#0E0824" })
hl(0, "NonText", { fg = "#76707B" })
hl(0, "Whitespace", { fg = "#484254" })
hl(0, "SpecialKey", { fg = "#76707B" })
hl(0, "Visual", { bg = "#624B27" })
hl(0, "VisualNOS", { link = "Visual" })
hl(0, "MatchParen", { fg = "#FFC72C", bg = "#383247", bold = true })
hl(0, "Pmenu", { fg = "#F5F0E5", bg = "#251F37" })
hl(0, "PmenuSel", { fg = "#F5F0E5", bg = "#383247", bold = true })
hl(0, "PmenuSbar", { bg = "#251F37" })
hl(0, "PmenuThumb", { bg = "#71697B" })
hl(0, "PmenuKind", { fg = "#5F967D" })
hl(0, "PmenuKindSel", { fg = "#5F967D", bg = "#383247" })
hl(0, "PmenuExtra", { fg = "#76707B" })
hl(0, "PmenuExtraSel", { fg = "#76707B", bg = "#383247" })
hl(0, "WildMenu", { link = "PmenuSel" })
hl(0, "StatusLine", { fg = "#FFFFFF", bg = "#7B3FB2", bold = true })
hl(0, "StatusLineNC", { fg = "#A49FA1", bg = "#251F37" })
hl(0, "WinBar", { fg = "#A49FA1", bg = "#0E0824" })
hl(0, "WinBarNC", { fg = "#76707B", bg = "#0E0824" })
hl(0, "WinSeparator", { fg = "#71697B" })
hl(0, "TabLine", { fg = "#A49FA1", bg = "#251F37" })
hl(0, "TabLineFill", { bg = "#0E0824" })
hl(0, "TabLineSel", { fg = "#FFFFFF", bg = "#7B3FB2", bold = true })
hl(0, "Search", { fg = "#F5F0E5", bg = "#5E3A29" })
hl(0, "IncSearch", { fg = "#0E0824", bg = "#F39833", bold = true })
hl(0, "CurSearch", { link = "IncSearch" })
hl(0, "Substitute", { fg = "#0E0824", bg = "#E25E5E" })
hl(0, "QuickFixLine", { bg = "#383247", bold = true })
hl(0, "Directory", { fg = "#A375CE" })
hl(0, "Title", { fg = "#FFC72C", bold = true })
hl(0, "Question", { fg = "#2FCC2F" })
hl(0, "MoreMsg", { fg = "#2FCC2F" })
hl(0, "ModeMsg", { fg = "#F5F0E5", bold = true })
hl(0, "MsgArea", { fg = "#F5F0E5", bg = "#0E0824" })
hl(0, "MsgSeparator", { fg = "#71697B" })
hl(0, "WarningMsg", { fg = "#FFC72C" })
hl(0, "ErrorMsg", { fg = "#E25E5E" })
hl(0, "SpellBad", { sp = "#E25E5E", undercurl = true })
hl(0, "SpellCap", { sp = "#FFC72C", undercurl = true })
hl(0, "SpellLocal", { sp = "#A375CE", undercurl = true })
hl(0, "SpellRare", { sp = "#74D96F", undercurl = true })
hl(0, "Comment", { fg = "#92DE8A", italic = true })
hl(0, "Constant", { fg = "#F39833" })
hl(0, "String", { fg = "#2FCC2F" })
hl(0, "Character", { fg = "#2FCC2F" })
hl(0, "Number", { fg = "#F39833" })
hl(0, "Boolean", { fg = "#F39833" })
hl(0, "Float", { fg = "#F39833" })
hl(0, "Identifier", { fg = "#F5F0E5" })
hl(0, "Function", { fg = "#A375CE" })
hl(0, "Statement", { fg = "#FFC72C" })
hl(0, "Conditional", { fg = "#FFC72C" })
hl(0, "Repeat", { fg = "#FFC72C" })
hl(0, "Label", { fg = "#FFC72C" })
hl(0, "Operator", { fg = "#C7C2BE" })
hl(0, "Keyword", { fg = "#FFC72C" })
hl(0, "Exception", { fg = "#FFC72C" })
hl(0, "PreProc", { fg = "#BD836F" })
hl(0, "Include", { fg = "#FFC72C" })
hl(0, "Define", { fg = "#BD836F" })
hl(0, "Macro", { fg = "#BD836F" })
hl(0, "PreCondit", { fg = "#BD836F" })
hl(0, "Type", { fg = "#5F967D" })
hl(0, "StorageClass", { fg = "#FFC72C" })
hl(0, "Structure", { fg = "#5F967D" })
hl(0, "Typedef", { fg = "#5F967D" })
hl(0, "Special", { fg = "#BD836F" })
hl(0, "SpecialChar", { fg = "#BD836F" })
hl(0, "Tag", { fg = "#FFC72C" })
hl(0, "Delimiter", { fg = "#C7C2BE" })
hl(0, "SpecialComment", { fg = "#92DE8A", bold = true })
hl(0, "Debug", { fg = "#E25E5E" })
hl(0, "Underlined", { fg = "#A375CE", underline = true })
hl(0, "Ignore", { fg = "#76707B" })
hl(0, "Error", { fg = "#E25E5E", bold = true })
hl(0, "Todo", { fg = "#0E0824", bg = "#F39833", bold = true })
hl(0, "Added", { fg = "#2FCC2F" })
hl(0, "Changed", { fg = "#FFC72C" })
hl(0, "Removed", { fg = "#E25E5E" })
hl(0, "DiffAdd", { bg = "#142B26" })
hl(0, "DiffChange", { bg = "#2B1F25" })
hl(0, "DiffDelete", { bg = "#34172E" })
hl(0, "DiffText", { bg = "#564126", bold = true })
hl(0, "DiagnosticError", { fg = "#E25E5E" })
hl(0, "DiagnosticWarn", { fg = "#FFC72C" })
hl(0, "DiagnosticInfo", { fg = "#A375CE" })
hl(0, "DiagnosticHint", { fg = "#74D96F" })
hl(0, "DiagnosticOk", { fg = "#2FCC2F" })
hl(0, "DiagnosticUnderlineError", { sp = "#E25E5E", undercurl = true })
hl(0, "DiagnosticUnderlineWarn", { sp = "#FFC72C", undercurl = true })
hl(0, "DiagnosticUnderlineInfo", { sp = "#A375CE", undercurl = true })
hl(0, "DiagnosticUnderlineHint", { sp = "#74D96F", undercurl = true })
hl(0, "DiagnosticUnderlineOk", { sp = "#2FCC2F", undercurl = true })
hl(0, "DiagnosticVirtualTextError", { fg = "#E25E5E", bg = "#27122B" })
hl(0, "DiagnosticVirtualTextWarn", { fg = "#FFC72C", bg = "#2B1F25" })
hl(0, "DiagnosticVirtualTextInfo", { fg = "#A375CE", bg = "#201538" })
hl(0, "DiagnosticVirtualTextHint", { fg = "#74D96F", bg = "#1A212D" })
hl(0, "@variable", { fg = "#F5F0E5" })
hl(0, "@variable.builtin", { fg = "#BD836F", italic = true })
hl(0, "@variable.parameter", { fg = "#F5F0E5" })
hl(0, "@variable.member", { fg = "#F5F0E5" })
hl(0, "@constant", { fg = "#F39833" })
hl(0, "@constant.builtin", { fg = "#BD836F" })
hl(0, "@constant.macro", { fg = "#BD836F" })
hl(0, "@module", { fg = "#5F967D" })
hl(0, "@label", { fg = "#FFC72C" })
hl(0, "@string", { fg = "#2FCC2F" })
hl(0, "@string.documentation", { fg = "#92DE8A" })
hl(0, "@string.escape", { fg = "#BD836F" })
hl(0, "@string.regexp", { fg = "#BD836F" })
hl(0, "@string.special", { fg = "#BD836F" })
hl(0, "@character", { fg = "#2FCC2F" })
hl(0, "@character.special", { fg = "#BD836F" })
hl(0, "@boolean", { fg = "#F39833" })
hl(0, "@number", { fg = "#F39833" })
hl(0, "@number.float", { fg = "#F39833" })
hl(0, "@type", { fg = "#5F967D" })
hl(0, "@type.builtin", { fg = "#5F967D", italic = true })
hl(0, "@type.definition", { fg = "#5F967D" })
hl(0, "@attribute", { fg = "#BD836F" })
hl(0, "@attribute.builtin", { fg = "#BD836F" })
hl(0, "@property", { fg = "#F5F0E5" })
hl(0, "@function", { fg = "#A375CE" })
hl(0, "@function.builtin", { fg = "#BD836F" })
hl(0, "@function.macro", { fg = "#BD836F" })
hl(0, "@function.method", { fg = "#A375CE" })
hl(0, "@constructor", { fg = "#5F967D" })
hl(0, "@operator", { fg = "#C7C2BE" })
hl(0, "@keyword", { fg = "#FFC72C" })
hl(0, "@keyword.function", { fg = "#FFC72C" })
hl(0, "@keyword.operator", { fg = "#FFC72C" })
hl(0, "@keyword.import", { fg = "#FFC72C" })
hl(0, "@keyword.return", { fg = "#FFC72C" })
hl(0, "@keyword.exception", { fg = "#FFC72C" })
hl(0, "@punctuation.delimiter", { fg = "#C7C2BE" })
hl(0, "@punctuation.bracket", { fg = "#C7C2BE" })
hl(0, "@punctuation.special", { fg = "#BD836F" })
hl(0, "@comment", { fg = "#92DE8A", italic = true })
hl(0, "@comment.documentation", { fg = "#92DE8A", italic = true })
hl(0, "@comment.error", { fg = "#0E0824", bg = "#E25E5E", bold = true })
hl(0, "@comment.warning", { fg = "#0E0824", bg = "#FFC72C", bold = true })
hl(0, "@comment.todo", { link = "Todo" })
hl(0, "@comment.note", { fg = "#0E0824", bg = "#A375CE", bold = true })
hl(0, "@tag", { fg = "#FFC72C" })
hl(0, "@tag.builtin", { fg = "#FFC72C" })
hl(0, "@tag.attribute", { fg = "#A375CE", italic = true })
hl(0, "@tag.delimiter", { fg = "#C7C2BE" })
hl(0, "@markup.strong", { fg = "#F5F0E5", bold = true })
hl(0, "@markup.italic", { fg = "#F5F0E5", italic = true })
hl(0, "@markup.strikethrough", { fg = "#A49FA1", strikethrough = true })
hl(0, "@markup.underline", { fg = "#F5F0E5", underline = true })
hl(0, "@markup.quote", { fg = "#A49FA1", italic = true })
hl(0, "@markup.math", { fg = "#F39833" })
hl(0, "@markup.link", { fg = "#A375CE" })
hl(0, "@markup.link.label", { fg = "#FFC72C" })
hl(0, "@markup.link.url", { fg = "#A375CE", underline = true })
hl(0, "@markup.raw", { fg = "#2FCC2F" })
hl(0, "@markup.list", { fg = "#FFC72C" })
hl(0, "@markup.list.checked", { fg = "#2FCC2F" })
hl(0, "@markup.list.unchecked", { fg = "#A49FA1" })
hl(0, "@diff.plus", { fg = "#2FCC2F" })
hl(0, "@diff.minus", { fg = "#E25E5E" })
hl(0, "@diff.delta", { fg = "#FFC72C" })
hl(0, "@lsp.type.namespace", { link = "@module" })
hl(0, "@lsp.type.class", { link = "@type" })
hl(0, "@lsp.type.enum", { link = "@type" })
hl(0, "@lsp.type.interface", { link = "@type" })
hl(0, "@lsp.type.struct", { link = "@type" })
hl(0, "@lsp.type.parameter", { link = "@variable.parameter" })
hl(0, "@lsp.type.property", { link = "@property" })
hl(0, "@lsp.type.enumMember", { link = "@constant" })
hl(0, "@lsp.type.method", { link = "@function.method" })
hl(0, "MiniIconsAzure", { fg = "#A375CE" })
hl(0, "MiniIconsBlue", { fg = "#A375CE" })
hl(0, "MiniIconsCyan", { fg = "#5F967D" })
hl(0, "MiniIconsGreen", { fg = "#2FCC2F" })
hl(0, "MiniIconsGrey", { fg = "#A49FA1" })
hl(0, "MiniIconsOrange", { fg = "#F39833" })
hl(0, "MiniIconsPurple", { fg = "#BD836F" })
hl(0, "MiniIconsRed", { fg = "#E25E5E" })
hl(0, "MiniIconsYellow", { fg = "#FFC72C" })
hl(0, "MiniFilesTitleFocused", { fg = "#FFC72C", bg = "#251F37", bold = true })
hl(0, "MiniFilesDirectory", { fg = "#A375CE" })
hl(0, "MiniFilesFile", { fg = "#F5F0E5" })
hl(0, "MiniFilesCursorLine", { bg = "#383247" })
hl(0, "MiniPickMatchCurrent", { bg = "#383247", bold = true })
hl(0, "MiniPickMatchRanges", { fg = "#FFC72C", bold = true })
hl(0, "MiniPickPrompt", { fg = "#FFC72C", bold = true })
hl(0, "MiniPickBorderText", { fg = "#FFC72C" })
hl(0, "MiniClueDescGroup", { fg = "#5F967D" })
hl(0, "MiniClueDescSingle", { fg = "#F5F0E5" })
hl(0, "MiniClueNextKey", { fg = "#FFC72C", bold = true })
hl(0, "MiniClueTitle", { fg = "#FFC72C", bg = "#251F37", bold = true })
hl(0, "RenderMarkdownCode", { bg = "#251F37" })
hl(0, "RenderMarkdownCodeInline", { fg = "#2FCC2F", bg = "#251F37" })
hl(0, "RenderMarkdownBullet", { fg = "#FFC72C" })
hl(0, "RenderMarkdownQuote", { fg = "#A49FA1" })
hl(0, "RenderMarkdownDash", { fg = "#71697B" })
hl(0, "RenderMarkdownTableHead", { fg = "#5F967D", bold = true })
hl(0, "RenderMarkdownTableRow", { fg = "#A49FA1" })
hl(0, "RenderMarkdownLink", { fg = "#A375CE" })
hl(0, "RenderMarkdownChecked", { fg = "#2FCC2F" })
hl(0, "RenderMarkdownUnchecked", { fg = "#A49FA1" })
hl(0, "@markup.heading.1", { fg = "#FFC72C", bold = true })
hl(0, "RenderMarkdownH1", { fg = "#FFC72C", bold = true })
hl(0, "RenderMarkdownH1Bg", { fg = "#FFC72C", bg = "#322525", bold = true })
hl(0, "@markup.heading.2", { fg = "#A375CE", bold = true })
hl(0, "RenderMarkdownH2", { fg = "#A375CE", bold = true })
hl(0, "RenderMarkdownH2Bg", { fg = "#A375CE", bg = "#24183E", bold = true })
hl(0, "@markup.heading.3", { fg = "#2FCC2F", bold = true })
hl(0, "RenderMarkdownH3", { fg = "#2FCC2F", bold = true })
hl(0, "RenderMarkdownH3Bg", { fg = "#2FCC2F", bg = "#132526", bold = true })
hl(0, "@markup.heading.4", { fg = "#F39833", bold = true })
hl(0, "RenderMarkdownH4", { fg = "#F39833", bold = true })
hl(0, "RenderMarkdownH4Bg", { fg = "#F39833", bg = "#301E26", bold = true })
hl(0, "@markup.heading.5", { fg = "#5F967D", bold = true })
hl(0, "RenderMarkdownH5", { fg = "#5F967D", bold = true })
hl(0, "RenderMarkdownH5Bg", { fg = "#5F967D", bg = "#1A1D31", bold = true })
hl(0, "@markup.heading.6", { fg = "#BD836F", bold = true })
hl(0, "RenderMarkdownH6", { fg = "#BD836F", bold = true })
hl(0, "RenderMarkdownH6Bg", { fg = "#BD836F", bg = "#281A2F", bold = true })

vim.g.terminal_color_0 = "#484254"
vim.g.terminal_color_1 = "#E25E5E"
vim.g.terminal_color_2 = "#2FCC2F"
vim.g.terminal_color_3 = "#FFC72C"
vim.g.terminal_color_4 = "#A375CE"
vim.g.terminal_color_5 = "#BD836F"
vim.g.terminal_color_6 = "#FFC72C"
vim.g.terminal_color_7 = "#A49FA1"
vim.g.terminal_color_8 = "#76707B"
vim.g.terminal_color_9 = "#E87E7E"
vim.g.terminal_color_10 = "#59D659"
vim.g.terminal_color_11 = "#FFD256"
vim.g.terminal_color_12 = "#B591D8"
vim.g.terminal_color_13 = "#CA9C8C"
vim.g.terminal_color_14 = "#FFD256"
vim.g.terminal_color_15 = "#F5F0E5"
