-- retro-geeko - erzeugt von retro-coding-themes, nicht von Hand aendern.
-- Quelle: src/retro_coding_themes/data/geeko.json, Ableitung in derive.py.

vim.cmd("highlight clear")
if vim.fn.exists("syntax_on") == 1 then
  vim.cmd("syntax reset")
end

vim.o.background = "dark"
vim.g.colors_name = "retro-geeko"

local hl = vim.api.nvim_set_hl

hl(0, "Normal", { fg = "#EEEEEE", bg = "#173F0F" })
hl(0, "NormalNC", { link = "Normal" })
hl(0, "NormalFloat", { fg = "#EEEEEE", bg = "#2C5025" })
hl(0, "FloatBorder", { fg = "#809C7B", bg = "#2C5025" })
hl(0, "FloatTitle", { fg = "#7ECB28", bg = "#2C5025", bold = true })
hl(0, "ColorColumn", { bg = "#264B1F" })
hl(0, "Conceal", { fg = "#869981" })
hl(0, "Cursor", { fg = "#173F0F", bg = "#EEEEEE" })
hl(0, "lCursor", { link = "Cursor" })
hl(0, "TermCursor", { link = "Cursor" })
hl(0, "CursorLine", { bg = "#264B1F" })
hl(0, "CursorColumn", { link = "CursorLine" })
hl(0, "CursorLineNr", { fg = "#7ECB28", bold = true })
hl(0, "LineNr", { fg = "#869981" })
hl(0, "SignColumn", { bg = "#173F0F" })
hl(0, "FoldColumn", { fg = "#869981" })
hl(0, "Folded", { fg = "#AEBAAB", bg = "#2C5025" })
hl(0, "EndOfBuffer", { fg = "#173F0F" })
hl(0, "NonText", { fg = "#869981" })
hl(0, "Whitespace", { fg = "#4D6B47" })
hl(0, "SpecialKey", { fg = "#869981" })
hl(0, "Visual", { bg = "#376A17" })
hl(0, "VisualNOS", { link = "Visual" })
hl(0, "MatchParen", { fg = "#7ECB28", bg = "#3E5E37", bold = true })
hl(0, "Pmenu", { fg = "#EEEEEE", bg = "#2C5025" })
hl(0, "PmenuSel", { fg = "#EEEEEE", bg = "#3E5E37", bold = true })
hl(0, "PmenuSbar", { bg = "#2C5025" })
hl(0, "PmenuThumb", { bg = "#809C7B" })
hl(0, "PmenuKind", { fg = "#B9D996" })
hl(0, "PmenuKindSel", { fg = "#B9D996", bg = "#3E5E37" })
hl(0, "PmenuExtra", { fg = "#869981" })
hl(0, "PmenuExtraSel", { fg = "#869981", bg = "#3E5E37" })
hl(0, "WildMenu", { link = "PmenuSel" })
hl(0, "StatusLine", { fg = "#000000", bg = "#73BA25", bold = true })
hl(0, "StatusLineNC", { fg = "#AEBAAB", bg = "#2C5025" })
hl(0, "WinBar", { fg = "#AEBAAB", bg = "#173F0F" })
hl(0, "WinBarNC", { fg = "#869981", bg = "#173F0F" })
hl(0, "WinSeparator", { fg = "#809C7B" })
hl(0, "TabLine", { fg = "#AEBAAB", bg = "#2C5025" })
hl(0, "TabLineFill", { bg = "#173F0F" })
hl(0, "TabLineSel", { fg = "#000000", bg = "#73BA25", bold = true })
hl(0, "Search", { fg = "#EEEEEE", bg = "#65630D" })
hl(0, "IncSearch", { fg = "#173F0F", bg = "#F5A60A", bold = true })
hl(0, "CurSearch", { link = "IncSearch" })
hl(0, "Substitute", { fg = "#173F0F", bg = "#F0A5A5" })
hl(0, "QuickFixLine", { bg = "#3E5E37", bold = true })
hl(0, "Directory", { fg = "#43C9BB" })
hl(0, "Title", { fg = "#7ECB28", bold = true })
hl(0, "Question", { fg = "#7ECB28" })
hl(0, "MoreMsg", { fg = "#7ECB28" })
hl(0, "ModeMsg", { fg = "#EEEEEE", bold = true })
hl(0, "MsgArea", { fg = "#EEEEEE", bg = "#173F0F" })
hl(0, "MsgSeparator", { fg = "#809C7B" })
hl(0, "WarningMsg", { fg = "#F5A60A" })
hl(0, "ErrorMsg", { fg = "#F0A5A5" })
hl(0, "SpellBad", { sp = "#F0A5A5", undercurl = true })
hl(0, "SpellCap", { sp = "#F5A60A", undercurl = true })
hl(0, "SpellLocal", { sp = "#7ECB28", undercurl = true })
hl(0, "SpellRare", { sp = "#76CCC2", undercurl = true })
hl(0, "Comment", { fg = "#92D3CC", italic = true })
hl(0, "Constant", { fg = "#F5A60A" })
hl(0, "String", { fg = "#B0E475" })
hl(0, "Character", { fg = "#B0E475" })
hl(0, "Number", { fg = "#F5A60A" })
hl(0, "Boolean", { fg = "#F5A60A" })
hl(0, "Float", { fg = "#F5A60A" })
hl(0, "Identifier", { fg = "#EEEEEE" })
hl(0, "Function", { fg = "#43C9BB" })
hl(0, "Statement", { fg = "#7ECB28" })
hl(0, "Conditional", { fg = "#7ECB28" })
hl(0, "Repeat", { fg = "#7ECB28" })
hl(0, "Label", { fg = "#7ECB28" })
hl(0, "Operator", { fg = "#C3CBC1" })
hl(0, "Keyword", { fg = "#7ECB28" })
hl(0, "Exception", { fg = "#7ECB28" })
hl(0, "PreProc", { fg = "#F0A475" })
hl(0, "Include", { fg = "#7ECB28" })
hl(0, "Define", { fg = "#F0A475" })
hl(0, "Macro", { fg = "#F0A475" })
hl(0, "PreCondit", { fg = "#F0A475" })
hl(0, "Type", { fg = "#B9D996" })
hl(0, "StorageClass", { fg = "#7ECB28" })
hl(0, "Structure", { fg = "#B9D996" })
hl(0, "Typedef", { fg = "#B9D996" })
hl(0, "Special", { fg = "#F0A475" })
hl(0, "SpecialChar", { fg = "#F0A475" })
hl(0, "Tag", { fg = "#7ECB28" })
hl(0, "Delimiter", { fg = "#C3CBC1" })
hl(0, "SpecialComment", { fg = "#92D3CC", bold = true })
hl(0, "Debug", { fg = "#F0A5A5" })
hl(0, "Underlined", { fg = "#43C9BB", underline = true })
hl(0, "Ignore", { fg = "#869981" })
hl(0, "Error", { fg = "#F0A5A5", bold = true })
hl(0, "Todo", { fg = "#173F0F", bg = "#F5A60A", bold = true })
hl(0, "Added", { fg = "#7ECB28" })
hl(0, "Changed", { fg = "#F5A60A" })
hl(0, "Removed", { fg = "#F0A5A5" })
hl(0, "DiffAdd", { bg = "#2A5814" })
hl(0, "DiffChange", { bg = "#324B0E" })
hl(0, "DiffDelete", { bg = "#3E512A" })
hl(0, "DiffText", { bg = "#5A5E0E", bold = true })
hl(0, "DiagnosticError", { fg = "#F0A5A5" })
hl(0, "DiagnosticWarn", { fg = "#F5A60A" })
hl(0, "DiagnosticInfo", { fg = "#7ECB28" })
hl(0, "DiagnosticHint", { fg = "#76CCC2" })
hl(0, "DiagnosticOk", { fg = "#7ECB28" })
hl(0, "DiagnosticUnderlineError", { sp = "#F0A5A5", undercurl = true })
hl(0, "DiagnosticUnderlineWarn", { sp = "#F5A60A", undercurl = true })
hl(0, "DiagnosticUnderlineInfo", { sp = "#7ECB28", undercurl = true })
hl(0, "DiagnosticUnderlineHint", { sp = "#76CCC2", undercurl = true })
hl(0, "DiagnosticUnderlineOk", { sp = "#7ECB28", undercurl = true })
hl(0, "DiagnosticVirtualTextError", { fg = "#F0A5A5", bg = "#314B21" })
hl(0, "DiagnosticVirtualTextWarn", { fg = "#F5A60A", bg = "#324B0E" })
hl(0, "DiagnosticVirtualTextInfo", { fg = "#7ECB28", bg = "#235012" })
hl(0, "DiagnosticVirtualTextHint", { fg = "#76CCC2", bg = "#225024" })
hl(0, "@variable", { fg = "#EEEEEE" })
hl(0, "@variable.builtin", { fg = "#F0A475", italic = true })
hl(0, "@variable.parameter", { fg = "#EEEEEE" })
hl(0, "@variable.member", { fg = "#EEEEEE" })
hl(0, "@constant", { fg = "#F5A60A" })
hl(0, "@constant.builtin", { fg = "#F0A475" })
hl(0, "@constant.macro", { fg = "#F0A475" })
hl(0, "@module", { fg = "#B9D996" })
hl(0, "@label", { fg = "#7ECB28" })
hl(0, "@string", { fg = "#B0E475" })
hl(0, "@string.documentation", { fg = "#92D3CC" })
hl(0, "@string.escape", { fg = "#F0A475" })
hl(0, "@string.regexp", { fg = "#F0A475" })
hl(0, "@string.special", { fg = "#F0A475" })
hl(0, "@character", { fg = "#B0E475" })
hl(0, "@character.special", { fg = "#F0A475" })
hl(0, "@boolean", { fg = "#F5A60A" })
hl(0, "@number", { fg = "#F5A60A" })
hl(0, "@number.float", { fg = "#F5A60A" })
hl(0, "@type", { fg = "#B9D996" })
hl(0, "@type.builtin", { fg = "#B9D996", italic = true })
hl(0, "@type.definition", { fg = "#B9D996" })
hl(0, "@attribute", { fg = "#F0A475" })
hl(0, "@attribute.builtin", { fg = "#F0A475" })
hl(0, "@property", { fg = "#EEEEEE" })
hl(0, "@function", { fg = "#43C9BB" })
hl(0, "@function.builtin", { fg = "#F0A475" })
hl(0, "@function.macro", { fg = "#F0A475" })
hl(0, "@function.method", { fg = "#43C9BB" })
hl(0, "@constructor", { fg = "#B9D996" })
hl(0, "@operator", { fg = "#C3CBC1" })
hl(0, "@keyword", { fg = "#7ECB28" })
hl(0, "@keyword.function", { fg = "#7ECB28" })
hl(0, "@keyword.operator", { fg = "#7ECB28" })
hl(0, "@keyword.import", { fg = "#7ECB28" })
hl(0, "@keyword.return", { fg = "#7ECB28" })
hl(0, "@keyword.exception", { fg = "#7ECB28" })
hl(0, "@punctuation.delimiter", { fg = "#C3CBC1" })
hl(0, "@punctuation.bracket", { fg = "#C3CBC1" })
hl(0, "@punctuation.special", { fg = "#F0A475" })
hl(0, "@comment", { fg = "#92D3CC", italic = true })
hl(0, "@comment.documentation", { fg = "#92D3CC", italic = true })
hl(0, "@comment.error", { fg = "#173F0F", bg = "#F0A5A5", bold = true })
hl(0, "@comment.warning", { fg = "#173F0F", bg = "#F5A60A", bold = true })
hl(0, "@comment.todo", { link = "Todo" })
hl(0, "@comment.note", { fg = "#173F0F", bg = "#7ECB28", bold = true })
hl(0, "@tag", { fg = "#7ECB28" })
hl(0, "@tag.builtin", { fg = "#7ECB28" })
hl(0, "@tag.attribute", { fg = "#43C9BB", italic = true })
hl(0, "@tag.delimiter", { fg = "#C3CBC1" })
hl(0, "@markup.strong", { fg = "#EEEEEE", bold = true })
hl(0, "@markup.italic", { fg = "#EEEEEE", italic = true })
hl(0, "@markup.strikethrough", { fg = "#AEBAAB", strikethrough = true })
hl(0, "@markup.underline", { fg = "#EEEEEE", underline = true })
hl(0, "@markup.quote", { fg = "#AEBAAB", italic = true })
hl(0, "@markup.math", { fg = "#F5A60A" })
hl(0, "@markup.link", { fg = "#43C9BB" })
hl(0, "@markup.link.label", { fg = "#7ECB28" })
hl(0, "@markup.link.url", { fg = "#43C9BB", underline = true })
hl(0, "@markup.raw", { fg = "#B0E475" })
hl(0, "@markup.list", { fg = "#7ECB28" })
hl(0, "@markup.list.checked", { fg = "#7ECB28" })
hl(0, "@markup.list.unchecked", { fg = "#AEBAAB" })
hl(0, "@diff.plus", { fg = "#7ECB28" })
hl(0, "@diff.minus", { fg = "#F0A5A5" })
hl(0, "@diff.delta", { fg = "#F5A60A" })
hl(0, "@lsp.type.namespace", { link = "@module" })
hl(0, "@lsp.type.class", { link = "@type" })
hl(0, "@lsp.type.enum", { link = "@type" })
hl(0, "@lsp.type.interface", { link = "@type" })
hl(0, "@lsp.type.struct", { link = "@type" })
hl(0, "@lsp.type.parameter", { link = "@variable.parameter" })
hl(0, "@lsp.type.property", { link = "@property" })
hl(0, "@lsp.type.enumMember", { link = "@constant" })
hl(0, "@lsp.type.method", { link = "@function.method" })
hl(0, "MiniIconsAzure", { fg = "#43C9BB" })
hl(0, "MiniIconsBlue", { fg = "#7ECB28" })
hl(0, "MiniIconsCyan", { fg = "#B9D996" })
hl(0, "MiniIconsGreen", { fg = "#7ECB28" })
hl(0, "MiniIconsGrey", { fg = "#AEBAAB" })
hl(0, "MiniIconsOrange", { fg = "#F5A60A" })
hl(0, "MiniIconsPurple", { fg = "#F0A475" })
hl(0, "MiniIconsRed", { fg = "#F0A5A5" })
hl(0, "MiniIconsYellow", { fg = "#F5A60A" })
hl(0, "MiniFilesTitleFocused", { fg = "#7ECB28", bg = "#2C5025", bold = true })
hl(0, "MiniFilesDirectory", { fg = "#43C9BB" })
hl(0, "MiniFilesFile", { fg = "#EEEEEE" })
hl(0, "MiniFilesCursorLine", { bg = "#3E5E37" })
hl(0, "MiniPickMatchCurrent", { bg = "#3E5E37", bold = true })
hl(0, "MiniPickMatchRanges", { fg = "#7ECB28", bold = true })
hl(0, "MiniPickPrompt", { fg = "#7ECB28", bold = true })
hl(0, "MiniPickBorderText", { fg = "#7ECB28" })
hl(0, "MiniClueDescGroup", { fg = "#B9D996" })
hl(0, "MiniClueDescSingle", { fg = "#EEEEEE" })
hl(0, "MiniClueNextKey", { fg = "#7ECB28", bold = true })
hl(0, "MiniClueTitle", { fg = "#7ECB28", bg = "#2C5025", bold = true })
hl(0, "RenderMarkdownCode", { bg = "#2C5025" })
hl(0, "RenderMarkdownCodeInline", { fg = "#B0E475", bg = "#2C5025" })
hl(0, "RenderMarkdownBullet", { fg = "#7ECB28" })
hl(0, "RenderMarkdownQuote", { fg = "#AEBAAB" })
hl(0, "RenderMarkdownDash", { fg = "#809C7B" })
hl(0, "RenderMarkdownTableHead", { fg = "#B9D996", bold = true })
hl(0, "RenderMarkdownTableRow", { fg = "#AEBAAB" })
hl(0, "RenderMarkdownLink", { fg = "#43C9BB" })
hl(0, "RenderMarkdownChecked", { fg = "#7ECB28" })
hl(0, "RenderMarkdownUnchecked", { fg = "#AEBAAB" })
hl(0, "@markup.heading.1", { fg = "#7ECB28", bold = true })
hl(0, "RenderMarkdownH1", { fg = "#7ECB28", bold = true })
hl(0, "RenderMarkdownH1Bg", { fg = "#7ECB28", bg = "#265413", bold = true })
hl(0, "@markup.heading.2", { fg = "#43C9BB", bold = true })
hl(0, "RenderMarkdownH2", { fg = "#43C9BB", bold = true })
hl(0, "RenderMarkdownH2Bg", { fg = "#43C9BB", bg = "#1E5429", bold = true })
hl(0, "@markup.heading.3", { fg = "#B0E475", bold = true })
hl(0, "RenderMarkdownH3", { fg = "#B0E475", bold = true })
hl(0, "RenderMarkdownH3Bg", { fg = "#B0E475", bg = "#2E581E", bold = true })
hl(0, "@markup.heading.4", { fg = "#F5A60A", bold = true })
hl(0, "RenderMarkdownH4", { fg = "#F5A60A", bold = true })
hl(0, "RenderMarkdownH4Bg", { fg = "#F5A60A", bg = "#384E0E", bold = true })
hl(0, "@markup.heading.5", { fg = "#B9D996", bold = true })
hl(0, "RenderMarkdownH5", { fg = "#B9D996", bold = true })
hl(0, "RenderMarkdownH5Bg", { fg = "#B9D996", bg = "#2F5623", bold = true })
hl(0, "@markup.heading.6", { fg = "#F0A475", bold = true })
hl(0, "RenderMarkdownH6", { fg = "#F0A475", bold = true })
hl(0, "RenderMarkdownH6Bg", { fg = "#F0A475", bg = "#384E1E", bold = true })

vim.g.terminal_color_0 = "#4D6B47"
vim.g.terminal_color_1 = "#F0A5A5"
vim.g.terminal_color_2 = "#7ECB28"
vim.g.terminal_color_3 = "#F5A60A"
vim.g.terminal_color_4 = "#7ECB28"
vim.g.terminal_color_5 = "#F0A475"
vim.g.terminal_color_6 = "#7ECB28"
vim.g.terminal_color_7 = "#AEBAAB"
vim.g.terminal_color_8 = "#788E73"
vim.g.terminal_color_9 = "#F3B7B7"
vim.g.terminal_color_10 = "#98D553"
vim.g.terminal_color_11 = "#F7B83B"
vim.g.terminal_color_12 = "#98D553"
vim.g.terminal_color_13 = "#F3B691"
vim.g.terminal_color_14 = "#98D553"
vim.g.terminal_color_15 = "#EEEEEE"
