-- retro-classic-navy - erzeugt von retro-coding-themes, nicht von Hand aendern.
-- Quelle: src/retro_coding_themes/data/classic-navy.json, Ableitung in derive.py.

vim.cmd("highlight clear")
if vim.fn.exists("syntax_on") == 1 then
  vim.cmd("syntax reset")
end

vim.o.background = "dark"
vim.g.colors_name = "retro-classic-navy"

local hl = vim.api.nvim_set_hl

hl(0, "Normal", { fg = "#EEF0F5", bg = "#0C2B5C" })
hl(0, "NormalNC", { link = "Normal" })
hl(0, "NormalFloat", { fg = "#EEF0F5", bg = "#233F6B" })
hl(0, "FloatBorder", { fg = "#768AAA", bg = "#233F6B" })
hl(0, "FloatTitle", { fg = "#DB9CA1", bg = "#233F6B", bold = true })
hl(0, "ColorColumn", { bg = "#1C3967" })
hl(0, "Conceal", { fg = "#7B8CA7" })
hl(0, "Cursor", { fg = "#0C2B5C", bg = "#EEF0F5" })
hl(0, "lCursor", { link = "Cursor" })
hl(0, "TermCursor", { link = "Cursor" })
hl(0, "CursorLine", { bg = "#1C3967" })
hl(0, "CursorColumn", { link = "CursorLine" })
hl(0, "CursorLineNr", { fg = "#DB9CA1", bold = true })
hl(0, "LineNr", { fg = "#7B8CA7" })
hl(0, "SignColumn", { bg = "#0C2B5C" })
hl(0, "FoldColumn", { fg = "#7B8CA7" })
hl(0, "Folded", { fg = "#9FABBF", bg = "#233F6B" })
hl(0, "EndOfBuffer", { fg = "#0C2B5C" })
hl(0, "NonText", { fg = "#7B8CA7" })
hl(0, "Whitespace", { fg = "#445C82" })
hl(0, "SpecialKey", { fg = "#7B8CA7" })
hl(0, "Visual", { bg = "#3F3053" })
hl(0, "VisualNOS", { link = "Visual" })
hl(0, "MatchParen", { fg = "#DB9CA1", bg = "#354E78", bold = true })
hl(0, "Pmenu", { fg = "#EEF0F5", bg = "#233F6B" })
hl(0, "PmenuSel", { fg = "#EEF0F5", bg = "#354E78", bold = true })
hl(0, "PmenuSbar", { bg = "#233F6B" })
hl(0, "PmenuThumb", { bg = "#768AAA" })
hl(0, "PmenuKind", { fg = "#95C09A" })
hl(0, "PmenuKindSel", { fg = "#95C09A", bg = "#354E78" })
hl(0, "PmenuExtra", { fg = "#7B8CA7" })
hl(0, "PmenuExtraSel", { fg = "#7B8CA7", bg = "#354E78" })
hl(0, "WildMenu", { link = "PmenuSel" })
hl(0, "StatusLine", { fg = "#000000", bg = "#C0C5CC", bold = true })
hl(0, "StatusLineNC", { fg = "#9FABBF", bg = "#233F6B" })
hl(0, "WinBar", { fg = "#9FABBF", bg = "#0C2B5C" })
hl(0, "WinBarNC", { fg = "#7B8CA7", bg = "#0C2B5C" })
hl(0, "WinSeparator", { fg = "#768AAA" })
hl(0, "TabLine", { fg = "#9FABBF", bg = "#233F6B" })
hl(0, "TabLineFill", { bg = "#0C2B5C" })
hl(0, "TabLineSel", { fg = "#000000", bg = "#C0C5CC", bold = true })
hl(0, "Search", { fg = "#EEF0F5", bg = "#525554" })
hl(0, "IncSearch", { fg = "#0C2B5C", bg = "#D5A244", bold = true })
hl(0, "CurSearch", { link = "IncSearch" })
hl(0, "Substitute", { fg = "#0C2B5C", bg = "#DA9A9F" })
hl(0, "QuickFixLine", { bg = "#354E78", bold = true })
hl(0, "Directory", { fg = "#8AADE5" })
hl(0, "Title", { fg = "#DB9CA1", bold = true })
hl(0, "Question", { fg = "#71BC71" })
hl(0, "MoreMsg", { fg = "#71BC71" })
hl(0, "ModeMsg", { fg = "#EEF0F5", bold = true })
hl(0, "MsgArea", { fg = "#EEF0F5", bg = "#0C2B5C" })
hl(0, "MsgSeparator", { fg = "#768AAA" })
hl(0, "WarningMsg", { fg = "#D5A244" })
hl(0, "ErrorMsg", { fg = "#DA9A9F" })
hl(0, "SpellBad", { sp = "#DA9A9F", undercurl = true })
hl(0, "SpellCap", { sp = "#D5A244", undercurl = true })
hl(0, "SpellLocal", { sp = "#C0C5CC", undercurl = true })
hl(0, "SpellRare", { sp = "#9CADC9", undercurl = true })
hl(0, "Comment", { fg = "#9AABC8", italic = true })
hl(0, "Constant", { fg = "#D5A244" })
hl(0, "String", { fg = "#71BC71" })
hl(0, "Character", { fg = "#71BC71" })
hl(0, "Number", { fg = "#D5A244" })
hl(0, "Boolean", { fg = "#D5A244" })
hl(0, "Float", { fg = "#D5A244" })
hl(0, "Identifier", { fg = "#EEF0F5" })
hl(0, "Function", { fg = "#8AADE5" })
hl(0, "Statement", { fg = "#DB9CA1" })
hl(0, "Conditional", { fg = "#DB9CA1" })
hl(0, "Repeat", { fg = "#DB9CA1" })
hl(0, "Label", { fg = "#DB9CA1" })
hl(0, "Operator", { fg = "#C1C9D6" })
hl(0, "Keyword", { fg = "#DB9CA1" })
hl(0, "Exception", { fg = "#DB9CA1" })
hl(0, "PreProc", { fg = "#D6AD82" })
hl(0, "Include", { fg = "#DB9CA1" })
hl(0, "Define", { fg = "#D6AD82" })
hl(0, "Macro", { fg = "#D6AD82" })
hl(0, "PreCondit", { fg = "#D6AD82" })
hl(0, "Type", { fg = "#95C09A" })
hl(0, "StorageClass", { fg = "#DB9CA1" })
hl(0, "Structure", { fg = "#95C09A" })
hl(0, "Typedef", { fg = "#95C09A" })
hl(0, "Special", { fg = "#D6AD82" })
hl(0, "SpecialChar", { fg = "#D6AD82" })
hl(0, "Tag", { fg = "#DB9CA1" })
hl(0, "Delimiter", { fg = "#C1C9D6" })
hl(0, "SpecialComment", { fg = "#9AABC8", bold = true })
hl(0, "Debug", { fg = "#DA9A9F" })
hl(0, "Underlined", { fg = "#8AADE5", underline = true })
hl(0, "Ignore", { fg = "#7B8CA7" })
hl(0, "Error", { fg = "#DA9A9F", bold = true })
hl(0, "Todo", { fg = "#0C2B5C", bg = "#D5A244", bold = true })
hl(0, "Added", { fg = "#71BC71" })
hl(0, "Changed", { fg = "#D5A244" })
hl(0, "Removed", { fg = "#DA9A9F" })
hl(0, "DiffAdd", { bg = "#1E4560" })
hl(0, "DiffChange", { bg = "#243959" })
hl(0, "DiffDelete", { bg = "#313F68" })
hl(0, "DiffText", { bg = "#484F55", bold = true })
hl(0, "DiagnosticError", { fg = "#DA9A9F" })
hl(0, "DiagnosticWarn", { fg = "#D5A244" })
hl(0, "DiagnosticInfo", { fg = "#C0C5CC" })
hl(0, "DiagnosticHint", { fg = "#9CADC9" })
hl(0, "DiagnosticOk", { fg = "#71BC71" })
hl(0, "DiagnosticUnderlineError", { sp = "#DA9A9F", undercurl = true })
hl(0, "DiagnosticUnderlineWarn", { sp = "#D5A244", undercurl = true })
hl(0, "DiagnosticUnderlineInfo", { sp = "#C0C5CC", undercurl = true })
hl(0, "DiagnosticUnderlineHint", { sp = "#9CADC9", undercurl = true })
hl(0, "DiagnosticUnderlineOk", { sp = "#71BC71", undercurl = true })
hl(0, "DiagnosticVirtualTextError", { fg = "#DA9A9F", bg = "#253864" })
hl(0, "DiagnosticVirtualTextWarn", { fg = "#D5A244", bg = "#243959" })
hl(0, "DiagnosticVirtualTextInfo", { fg = "#C0C5CC", bg = "#223D69" })
hl(0, "DiagnosticVirtualTextHint", { fg = "#9CADC9", bg = "#1D3B69" })
hl(0, "@variable", { fg = "#EEF0F5" })
hl(0, "@variable.builtin", { fg = "#D6AD82", italic = true })
hl(0, "@variable.parameter", { fg = "#EEF0F5" })
hl(0, "@variable.member", { fg = "#EEF0F5" })
hl(0, "@constant", { fg = "#D5A244" })
hl(0, "@constant.builtin", { fg = "#D6AD82" })
hl(0, "@constant.macro", { fg = "#D6AD82" })
hl(0, "@module", { fg = "#95C09A" })
hl(0, "@label", { fg = "#DB9CA1" })
hl(0, "@string", { fg = "#71BC71" })
hl(0, "@string.documentation", { fg = "#9AABC8" })
hl(0, "@string.escape", { fg = "#D6AD82" })
hl(0, "@string.regexp", { fg = "#D6AD82" })
hl(0, "@string.special", { fg = "#D6AD82" })
hl(0, "@character", { fg = "#71BC71" })
hl(0, "@character.special", { fg = "#D6AD82" })
hl(0, "@boolean", { fg = "#D5A244" })
hl(0, "@number", { fg = "#D5A244" })
hl(0, "@number.float", { fg = "#D5A244" })
hl(0, "@type", { fg = "#95C09A" })
hl(0, "@type.builtin", { fg = "#95C09A", italic = true })
hl(0, "@type.definition", { fg = "#95C09A" })
hl(0, "@attribute", { fg = "#D6AD82" })
hl(0, "@attribute.builtin", { fg = "#D6AD82" })
hl(0, "@property", { fg = "#EEF0F5" })
hl(0, "@function", { fg = "#8AADE5" })
hl(0, "@function.builtin", { fg = "#D6AD82" })
hl(0, "@function.macro", { fg = "#D6AD82" })
hl(0, "@function.method", { fg = "#8AADE5" })
hl(0, "@constructor", { fg = "#95C09A" })
hl(0, "@operator", { fg = "#C1C9D6" })
hl(0, "@keyword", { fg = "#DB9CA1" })
hl(0, "@keyword.function", { fg = "#DB9CA1" })
hl(0, "@keyword.operator", { fg = "#DB9CA1" })
hl(0, "@keyword.import", { fg = "#DB9CA1" })
hl(0, "@keyword.return", { fg = "#DB9CA1" })
hl(0, "@keyword.exception", { fg = "#DB9CA1" })
hl(0, "@punctuation.delimiter", { fg = "#C1C9D6" })
hl(0, "@punctuation.bracket", { fg = "#C1C9D6" })
hl(0, "@punctuation.special", { fg = "#D6AD82" })
hl(0, "@comment", { fg = "#9AABC8", italic = true })
hl(0, "@comment.documentation", { fg = "#9AABC8", italic = true })
hl(0, "@comment.error", { fg = "#0C2B5C", bg = "#DA9A9F", bold = true })
hl(0, "@comment.warning", { fg = "#0C2B5C", bg = "#D5A244", bold = true })
hl(0, "@comment.todo", { link = "Todo" })
hl(0, "@comment.note", { fg = "#0C2B5C", bg = "#C0C5CC", bold = true })
hl(0, "@tag", { fg = "#DB9CA1" })
hl(0, "@tag.builtin", { fg = "#DB9CA1" })
hl(0, "@tag.attribute", { fg = "#8AADE5", italic = true })
hl(0, "@tag.delimiter", { fg = "#C1C9D6" })
hl(0, "@markup.strong", { fg = "#EEF0F5", bold = true })
hl(0, "@markup.italic", { fg = "#EEF0F5", italic = true })
hl(0, "@markup.strikethrough", { fg = "#9FABBF", strikethrough = true })
hl(0, "@markup.underline", { fg = "#EEF0F5", underline = true })
hl(0, "@markup.quote", { fg = "#9FABBF", italic = true })
hl(0, "@markup.math", { fg = "#D5A244" })
hl(0, "@markup.link", { fg = "#8AADE5" })
hl(0, "@markup.link.label", { fg = "#DB9CA1" })
hl(0, "@markup.link.url", { fg = "#8AADE5", underline = true })
hl(0, "@markup.raw", { fg = "#71BC71" })
hl(0, "@markup.list", { fg = "#DB9CA1" })
hl(0, "@markup.list.checked", { fg = "#71BC71" })
hl(0, "@markup.list.unchecked", { fg = "#9FABBF" })
hl(0, "@diff.plus", { fg = "#71BC71" })
hl(0, "@diff.minus", { fg = "#DA9A9F" })
hl(0, "@diff.delta", { fg = "#D5A244" })
hl(0, "@lsp.type.namespace", { link = "@module" })
hl(0, "@lsp.type.class", { link = "@type" })
hl(0, "@lsp.type.enum", { link = "@type" })
hl(0, "@lsp.type.interface", { link = "@type" })
hl(0, "@lsp.type.struct", { link = "@type" })
hl(0, "@lsp.type.parameter", { link = "@variable.parameter" })
hl(0, "@lsp.type.property", { link = "@property" })
hl(0, "@lsp.type.enumMember", { link = "@constant" })
hl(0, "@lsp.type.method", { link = "@function.method" })
hl(0, "MiniIconsAzure", { fg = "#8AADE5" })
hl(0, "MiniIconsBlue", { fg = "#C0C5CC" })
hl(0, "MiniIconsCyan", { fg = "#95C09A" })
hl(0, "MiniIconsGreen", { fg = "#71BC71" })
hl(0, "MiniIconsGrey", { fg = "#9FABBF" })
hl(0, "MiniIconsOrange", { fg = "#D5A244" })
hl(0, "MiniIconsPurple", { fg = "#D6AD82" })
hl(0, "MiniIconsRed", { fg = "#DA9A9F" })
hl(0, "MiniIconsYellow", { fg = "#D5A244" })
hl(0, "MiniFilesTitleFocused", { fg = "#DB9CA1", bg = "#233F6B", bold = true })
hl(0, "MiniFilesDirectory", { fg = "#8AADE5" })
hl(0, "MiniFilesFile", { fg = "#EEF0F5" })
hl(0, "MiniFilesCursorLine", { bg = "#354E78" })
hl(0, "MiniPickMatchCurrent", { bg = "#354E78", bold = true })
hl(0, "MiniPickMatchRanges", { fg = "#DB9CA1", bold = true })
hl(0, "MiniPickPrompt", { fg = "#DB9CA1", bold = true })
hl(0, "MiniPickBorderText", { fg = "#DB9CA1" })
hl(0, "MiniClueDescGroup", { fg = "#95C09A" })
hl(0, "MiniClueDescSingle", { fg = "#EEF0F5" })
hl(0, "MiniClueNextKey", { fg = "#DB9CA1", bold = true })
hl(0, "MiniClueTitle", { fg = "#DB9CA1", bg = "#233F6B", bold = true })
hl(0, "RenderMarkdownCode", { bg = "#233F6B" })
hl(0, "RenderMarkdownCodeInline", { fg = "#71BC71", bg = "#233F6B" })
hl(0, "RenderMarkdownBullet", { fg = "#DB9CA1" })
hl(0, "RenderMarkdownQuote", { fg = "#9FABBF" })
hl(0, "RenderMarkdownDash", { fg = "#768AAA" })
hl(0, "RenderMarkdownTableHead", { fg = "#95C09A", bold = true })
hl(0, "RenderMarkdownTableRow", { fg = "#9FABBF" })
hl(0, "RenderMarkdownLink", { fg = "#8AADE5" })
hl(0, "RenderMarkdownChecked", { fg = "#71BC71" })
hl(0, "RenderMarkdownUnchecked", { fg = "#9FABBF" })
hl(0, "@markup.heading.1", { fg = "#DB9CA1", bold = true })
hl(0, "RenderMarkdownH1", { fg = "#DB9CA1", bold = true })
hl(0, "RenderMarkdownH1Bg", { fg = "#DB9CA1", bg = "#2B3C66", bold = true })
hl(0, "@markup.heading.2", { fg = "#8AADE5", bold = true })
hl(0, "RenderMarkdownH2", { fg = "#8AADE5", bold = true })
hl(0, "RenderMarkdownH2Bg", { fg = "#8AADE5", bg = "#1F3F71", bold = true })
hl(0, "@markup.heading.3", { fg = "#71BC71", bold = true })
hl(0, "RenderMarkdownH3", { fg = "#71BC71", bold = true })
hl(0, "RenderMarkdownH3Bg", { fg = "#71BC71", bg = "#1B415F", bold = true })
hl(0, "@markup.heading.4", { fg = "#D5A244", bold = true })
hl(0, "RenderMarkdownH4", { fg = "#D5A244", bold = true })
hl(0, "RenderMarkdownH4Bg", { fg = "#D5A244", bg = "#2A3D58", bold = true })
hl(0, "@markup.heading.5", { fg = "#95C09A", bold = true })
hl(0, "RenderMarkdownH5", { fg = "#95C09A", bold = true })
hl(0, "RenderMarkdownH5Bg", { fg = "#95C09A", bg = "#214165", bold = true })
hl(0, "@markup.heading.6", { fg = "#D6AD82", bold = true })
hl(0, "RenderMarkdownH6", { fg = "#D6AD82", bold = true })
hl(0, "RenderMarkdownH6Bg", { fg = "#D6AD82", bg = "#2A3F62", bold = true })

vim.g.terminal_color_0 = "#445C82"
vim.g.terminal_color_1 = "#DA9A9F"
vim.g.terminal_color_2 = "#71BC71"
vim.g.terminal_color_3 = "#D5A244"
vim.g.terminal_color_4 = "#C0C5CC"
vim.g.terminal_color_5 = "#D6AD82"
vim.g.terminal_color_6 = "#DB9CA1"
vim.g.terminal_color_7 = "#9FABBF"
vim.g.terminal_color_8 = "#7284A1"
vim.g.terminal_color_9 = "#E1AEB2"
vim.g.terminal_color_10 = "#8DC98D"
vim.g.terminal_color_11 = "#DDB569"
vim.g.terminal_color_12 = "#CDD1D6"
vim.g.terminal_color_13 = "#DEBD9B"
vim.g.terminal_color_14 = "#E2B0B4"
vim.g.terminal_color_15 = "#EEF0F5"
