-- retro-spiderized - erzeugt von retro-coding-themes, nicht von Hand aendern.
-- Quelle: src/retro_coding_themes/data/spiderized.json, Ableitung in derive.py.

vim.cmd("highlight clear")
if vim.fn.exists("syntax_on") == 1 then
  vim.cmd("syntax reset")
end

vim.o.background = "dark"
vim.g.colors_name = "retro-spiderized"

local hl = vim.api.nvim_set_hl

hl(0, "Normal", { fg = "#FFFFFF", bg = "#0E1A3A" })
hl(0, "NormalNC", { link = "Normal" })
hl(0, "NormalFloat", { fg = "#FFFFFF", bg = "#26314E" })
hl(0, "FloatBorder", { fg = "#727B92", bg = "#26314E" })
hl(0, "FloatTitle", { fg = "#5C9BFE", bg = "#26314E", bold = true })
hl(0, "ColorColumn", { bg = "#1F2A48" })
hl(0, "Conceal", { fg = "#7A8193" })
hl(0, "Cursor", { fg = "#0E1A3A", bg = "#FFFFFF" })
hl(0, "lCursor", { link = "Cursor" })
hl(0, "TermCursor", { link = "Cursor" })
hl(0, "CursorLine", { bg = "#1F2A48" })
hl(0, "CursorColumn", { link = "CursorLine" })
hl(0, "CursorLineNr", { fg = "#5C9BFE", bold = true })
hl(0, "LineNr", { fg = "#7A8193" })
hl(0, "SignColumn", { bg = "#0E1A3A" })
hl(0, "FoldColumn", { fg = "#7A8193" })
hl(0, "Folded", { fg = "#ABAFBA", bg = "#26314E" })
hl(0, "EndOfBuffer", { fg = "#0E1A3A" })
hl(0, "NonText", { fg = "#7A8193" })
hl(0, "Whitespace", { fg = "#4A536B" })
hl(0, "SpecialKey", { fg = "#7A8193" })
hl(0, "Visual", { bg = "#143A7F" })
hl(0, "VisualNOS", { link = "Visual" })
hl(0, "MatchParen", { fg = "#5C9BFE", bg = "#39435D", bold = true })
hl(0, "Pmenu", { fg = "#FFFFFF", bg = "#26314E" })
hl(0, "PmenuSel", { fg = "#FFFFFF", bg = "#39435D", bold = true })
hl(0, "PmenuSbar", { bg = "#26314E" })
hl(0, "PmenuThumb", { bg = "#727B92" })
hl(0, "PmenuKind", { fg = "#C1906D" })
hl(0, "PmenuKindSel", { fg = "#C1906D", bg = "#39435D" })
hl(0, "PmenuExtra", { fg = "#7A8193" })
hl(0, "PmenuExtraSel", { fg = "#7A8193", bg = "#39435D" })
hl(0, "WildMenu", { link = "PmenuSel" })
hl(0, "StatusLine", { fg = "#FFFFFF", bg = "#D71920", bold = true })
hl(0, "StatusLineNC", { fg = "#ABAFBA", bg = "#26314E" })
hl(0, "WinBar", { fg = "#ABAFBA", bg = "#0E1A3A" })
hl(0, "WinBarNC", { fg = "#7A8193", bg = "#0E1A3A" })
hl(0, "WinSeparator", { fg = "#727B92" })
hl(0, "TabLine", { fg = "#ABAFBA", bg = "#26314E" })
hl(0, "TabLineFill", { bg = "#0E1A3A" })
hl(0, "TabLineSel", { fg = "#FFFFFF", bg = "#D71920", bold = true })
hl(0, "Search", { fg = "#FFFFFF", bg = "#624C36" })
hl(0, "IncSearch", { fg = "#0E1A3A", bg = "#FFA830", bold = true })
hl(0, "CurSearch", { link = "IncSearch" })
hl(0, "Substitute", { fg = "#0E1A3A", bg = "#F86E78" })
hl(0, "QuickFixLine", { bg = "#39435D", bold = true })
hl(0, "Directory", { fg = "#EF767B" })
hl(0, "Title", { fg = "#5C9BFE", bold = true })
hl(0, "Question", { fg = "#4CAC5C" })
hl(0, "MoreMsg", { fg = "#4CAC5C" })
hl(0, "ModeMsg", { fg = "#FFFFFF", bold = true })
hl(0, "MsgArea", { fg = "#FFFFFF", bg = "#0E1A3A" })
hl(0, "MsgSeparator", { fg = "#727B92" })
hl(0, "WarningMsg", { fg = "#FFA830" })
hl(0, "ErrorMsg", { fg = "#F86E78" })
hl(0, "SpellBad", { sp = "#F86E78", undercurl = true })
hl(0, "SpellCap", { sp = "#FFA830", undercurl = true })
hl(0, "SpellLocal", { sp = "#EF767B", undercurl = true })
hl(0, "SpellRare", { sp = "#6DA5FE", undercurl = true })
hl(0, "Comment", { fg = "#8FBAFE", italic = true })
hl(0, "Constant", { fg = "#FFA830" })
hl(0, "String", { fg = "#4CAC5C" })
hl(0, "Character", { fg = "#4CAC5C" })
hl(0, "Number", { fg = "#FFA830" })
hl(0, "Boolean", { fg = "#FFA830" })
hl(0, "Float", { fg = "#FFA830" })
hl(0, "Identifier", { fg = "#FFFFFF" })
hl(0, "Function", { fg = "#EF767B" })
hl(0, "Statement", { fg = "#5C9BFE" })
hl(0, "Conditional", { fg = "#5C9BFE" })
hl(0, "Repeat", { fg = "#5C9BFE" })
hl(0, "Label", { fg = "#5C9BFE" })
hl(0, "Operator", { fg = "#CFD1D8" })
hl(0, "Keyword", { fg = "#5C9BFE" })
hl(0, "Exception", { fg = "#5C9BFE" })
hl(0, "PreProc", { fg = "#E97B51" })
hl(0, "Include", { fg = "#5C9BFE" })
hl(0, "Define", { fg = "#E97B51" })
hl(0, "Macro", { fg = "#E97B51" })
hl(0, "PreCondit", { fg = "#E97B51" })
hl(0, "Type", { fg = "#C1906D" })
hl(0, "StorageClass", { fg = "#5C9BFE" })
hl(0, "Structure", { fg = "#C1906D" })
hl(0, "Typedef", { fg = "#C1906D" })
hl(0, "Special", { fg = "#E97B51" })
hl(0, "SpecialChar", { fg = "#E97B51" })
hl(0, "Tag", { fg = "#5C9BFE" })
hl(0, "Delimiter", { fg = "#CFD1D8" })
hl(0, "SpecialComment", { fg = "#8FBAFE", bold = true })
hl(0, "Debug", { fg = "#F86E78" })
hl(0, "Underlined", { fg = "#EF767B", underline = true })
hl(0, "Ignore", { fg = "#7A8193" })
hl(0, "Error", { fg = "#F86E78", bold = true })
hl(0, "Todo", { fg = "#0E1A3A", bg = "#FFA830", bold = true })
hl(0, "Added", { fg = "#4CAC5C" })
hl(0, "Changed", { fg = "#FFA830" })
hl(0, "Removed", { fg = "#F86E78" })
hl(0, "DiffAdd", { bg = "#193440" })
hl(0, "DiffChange", { bg = "#2B2B39" })
hl(0, "DiffDelete", { bg = "#382945" })
hl(0, "DiffText", { bg = "#564537", bold = true })
hl(0, "DiagnosticError", { fg = "#F86E78" })
hl(0, "DiagnosticWarn", { fg = "#FFA830" })
hl(0, "DiagnosticInfo", { fg = "#EF767B" })
hl(0, "DiagnosticHint", { fg = "#6DA5FE" })
hl(0, "DiagnosticOk", { fg = "#4CAC5C" })
hl(0, "DiagnosticUnderlineError", { sp = "#F86E78", undercurl = true })
hl(0, "DiagnosticUnderlineWarn", { sp = "#FFA830", undercurl = true })
hl(0, "DiagnosticUnderlineInfo", { sp = "#EF767B", undercurl = true })
hl(0, "DiagnosticUnderlineHint", { sp = "#6DA5FE", undercurl = true })
hl(0, "DiagnosticUnderlineOk", { sp = "#4CAC5C", undercurl = true })
hl(0, "DiagnosticVirtualTextError", { fg = "#F86E78", bg = "#2A2441" })
hl(0, "DiagnosticVirtualTextWarn", { fg = "#FFA830", bg = "#2B2B39" })
hl(0, "DiagnosticVirtualTextInfo", { fg = "#EF767B", bg = "#292542" })
hl(0, "DiagnosticVirtualTextHint", { fg = "#6DA5FE", bg = "#192B52" })
hl(0, "@variable", { fg = "#FFFFFF" })
hl(0, "@variable.builtin", { fg = "#E97B51", italic = true })
hl(0, "@variable.parameter", { fg = "#FFFFFF" })
hl(0, "@variable.member", { fg = "#FFFFFF" })
hl(0, "@constant", { fg = "#FFA830" })
hl(0, "@constant.builtin", { fg = "#E97B51" })
hl(0, "@constant.macro", { fg = "#E97B51" })
hl(0, "@module", { fg = "#C1906D" })
hl(0, "@label", { fg = "#5C9BFE" })
hl(0, "@string", { fg = "#4CAC5C" })
hl(0, "@string.documentation", { fg = "#8FBAFE" })
hl(0, "@string.escape", { fg = "#E97B51" })
hl(0, "@string.regexp", { fg = "#E97B51" })
hl(0, "@string.special", { fg = "#E97B51" })
hl(0, "@character", { fg = "#4CAC5C" })
hl(0, "@character.special", { fg = "#E97B51" })
hl(0, "@boolean", { fg = "#FFA830" })
hl(0, "@number", { fg = "#FFA830" })
hl(0, "@number.float", { fg = "#FFA830" })
hl(0, "@type", { fg = "#C1906D" })
hl(0, "@type.builtin", { fg = "#C1906D", italic = true })
hl(0, "@type.definition", { fg = "#C1906D" })
hl(0, "@attribute", { fg = "#E97B51" })
hl(0, "@attribute.builtin", { fg = "#E97B51" })
hl(0, "@property", { fg = "#FFFFFF" })
hl(0, "@function", { fg = "#EF767B" })
hl(0, "@function.builtin", { fg = "#E97B51" })
hl(0, "@function.macro", { fg = "#E97B51" })
hl(0, "@function.method", { fg = "#EF767B" })
hl(0, "@constructor", { fg = "#C1906D" })
hl(0, "@operator", { fg = "#CFD1D8" })
hl(0, "@keyword", { fg = "#5C9BFE" })
hl(0, "@keyword.function", { fg = "#5C9BFE" })
hl(0, "@keyword.operator", { fg = "#5C9BFE" })
hl(0, "@keyword.import", { fg = "#5C9BFE" })
hl(0, "@keyword.return", { fg = "#5C9BFE" })
hl(0, "@keyword.exception", { fg = "#5C9BFE" })
hl(0, "@punctuation.delimiter", { fg = "#CFD1D8" })
hl(0, "@punctuation.bracket", { fg = "#CFD1D8" })
hl(0, "@punctuation.special", { fg = "#E97B51" })
hl(0, "@comment", { fg = "#8FBAFE", italic = true })
hl(0, "@comment.documentation", { fg = "#8FBAFE", italic = true })
hl(0, "@comment.error", { fg = "#0E1A3A", bg = "#F86E78", bold = true })
hl(0, "@comment.warning", { fg = "#0E1A3A", bg = "#FFA830", bold = true })
hl(0, "@comment.todo", { link = "Todo" })
hl(0, "@comment.note", { fg = "#0E1A3A", bg = "#EF767B", bold = true })
hl(0, "@tag", { fg = "#5C9BFE" })
hl(0, "@tag.builtin", { fg = "#5C9BFE" })
hl(0, "@tag.attribute", { fg = "#EF767B", italic = true })
hl(0, "@tag.delimiter", { fg = "#CFD1D8" })
hl(0, "@markup.strong", { fg = "#FFFFFF", bold = true })
hl(0, "@markup.italic", { fg = "#FFFFFF", italic = true })
hl(0, "@markup.strikethrough", { fg = "#ABAFBA", strikethrough = true })
hl(0, "@markup.underline", { fg = "#FFFFFF", underline = true })
hl(0, "@markup.quote", { fg = "#ABAFBA", italic = true })
hl(0, "@markup.math", { fg = "#FFA830" })
hl(0, "@markup.link", { fg = "#EF767B" })
hl(0, "@markup.link.label", { fg = "#5C9BFE" })
hl(0, "@markup.link.url", { fg = "#EF767B", underline = true })
hl(0, "@markup.raw", { fg = "#4CAC5C" })
hl(0, "@markup.list", { fg = "#5C9BFE" })
hl(0, "@markup.list.checked", { fg = "#4CAC5C" })
hl(0, "@markup.list.unchecked", { fg = "#ABAFBA" })
hl(0, "@diff.plus", { fg = "#4CAC5C" })
hl(0, "@diff.minus", { fg = "#F86E78" })
hl(0, "@diff.delta", { fg = "#FFA830" })
hl(0, "@lsp.type.namespace", { link = "@module" })
hl(0, "@lsp.type.class", { link = "@type" })
hl(0, "@lsp.type.enum", { link = "@type" })
hl(0, "@lsp.type.interface", { link = "@type" })
hl(0, "@lsp.type.struct", { link = "@type" })
hl(0, "@lsp.type.parameter", { link = "@variable.parameter" })
hl(0, "@lsp.type.property", { link = "@property" })
hl(0, "@lsp.type.enumMember", { link = "@constant" })
hl(0, "@lsp.type.method", { link = "@function.method" })
hl(0, "MiniIconsAzure", { fg = "#EF767B" })
hl(0, "MiniIconsBlue", { fg = "#EF767B" })
hl(0, "MiniIconsCyan", { fg = "#C1906D" })
hl(0, "MiniIconsGreen", { fg = "#4CAC5C" })
hl(0, "MiniIconsGrey", { fg = "#ABAFBA" })
hl(0, "MiniIconsOrange", { fg = "#FFA830" })
hl(0, "MiniIconsPurple", { fg = "#E97B51" })
hl(0, "MiniIconsRed", { fg = "#F86E78" })
hl(0, "MiniIconsYellow", { fg = "#FFA830" })
hl(0, "MiniFilesTitleFocused", { fg = "#5C9BFE", bg = "#26314E", bold = true })
hl(0, "MiniFilesDirectory", { fg = "#EF767B" })
hl(0, "MiniFilesFile", { fg = "#FFFFFF" })
hl(0, "MiniFilesCursorLine", { bg = "#39435D" })
hl(0, "MiniPickMatchCurrent", { bg = "#39435D", bold = true })
hl(0, "MiniPickMatchRanges", { fg = "#5C9BFE", bold = true })
hl(0, "MiniPickPrompt", { fg = "#5C9BFE", bold = true })
hl(0, "MiniPickBorderText", { fg = "#5C9BFE" })
hl(0, "MiniClueDescGroup", { fg = "#C1906D" })
hl(0, "MiniClueDescSingle", { fg = "#FFFFFF" })
hl(0, "MiniClueNextKey", { fg = "#5C9BFE", bold = true })
hl(0, "MiniClueTitle", { fg = "#5C9BFE", bg = "#26314E", bold = true })
hl(0, "RenderMarkdownCode", { bg = "#26314E" })
hl(0, "RenderMarkdownCodeInline", { fg = "#4CAC5C", bg = "#26314E" })
hl(0, "RenderMarkdownBullet", { fg = "#5C9BFE" })
hl(0, "RenderMarkdownQuote", { fg = "#ABAFBA" })
hl(0, "RenderMarkdownDash", { fg = "#727B92" })
hl(0, "RenderMarkdownTableHead", { fg = "#C1906D", bold = true })
hl(0, "RenderMarkdownTableRow", { fg = "#ABAFBA" })
hl(0, "RenderMarkdownLink", { fg = "#EF767B" })
hl(0, "RenderMarkdownChecked", { fg = "#4CAC5C" })
hl(0, "RenderMarkdownUnchecked", { fg = "#ABAFBA" })
hl(0, "@markup.heading.1", { fg = "#5C9BFE", bold = true })
hl(0, "RenderMarkdownH1", { fg = "#5C9BFE", bold = true })
hl(0, "RenderMarkdownH1Bg", { fg = "#5C9BFE", bg = "#1A2D57", bold = true })
hl(0, "@markup.heading.2", { fg = "#EF767B", bold = true })
hl(0, "RenderMarkdownH2", { fg = "#EF767B", bold = true })
hl(0, "RenderMarkdownH2Bg", { fg = "#EF767B", bg = "#302844", bold = true })
hl(0, "@markup.heading.3", { fg = "#4CAC5C", bold = true })
hl(0, "RenderMarkdownH3", { fg = "#4CAC5C", bold = true })
hl(0, "RenderMarkdownH3Bg", { fg = "#4CAC5C", bg = "#17303F", bold = true })
hl(0, "@markup.heading.4", { fg = "#FFA830", bold = true })
hl(0, "RenderMarkdownH4", { fg = "#FFA830", bold = true })
hl(0, "RenderMarkdownH4Bg", { fg = "#FFA830", bg = "#322F38", bold = true })
hl(0, "@markup.heading.5", { fg = "#C1906D", bold = true })
hl(0, "RenderMarkdownH5", { fg = "#C1906D", bold = true })
hl(0, "RenderMarkdownH5Bg", { fg = "#C1906D", bg = "#292C42", bold = true })
hl(0, "@markup.heading.6", { fg = "#E97B51", bold = true })
hl(0, "RenderMarkdownH6", { fg = "#E97B51", bold = true })
hl(0, "RenderMarkdownH6Bg", { fg = "#E97B51", bg = "#2F293D", bold = true })

vim.g.terminal_color_0 = "#4A536B"
vim.g.terminal_color_1 = "#F86E78"
vim.g.terminal_color_2 = "#4CAC5C"
vim.g.terminal_color_3 = "#FFA830"
vim.g.terminal_color_4 = "#EF767B"
vim.g.terminal_color_5 = "#E97B51"
vim.g.terminal_color_6 = "#5C9BFE"
vim.g.terminal_color_7 = "#ABAFBA"
vim.g.terminal_color_8 = "#7A8193"
vim.g.terminal_color_9 = "#F98B93"
vim.g.terminal_color_10 = "#70BD7D"
vim.g.terminal_color_11 = "#FFB959"
vim.g.terminal_color_12 = "#F29195"
vim.g.terminal_color_13 = "#ED9574"
vim.g.terminal_color_14 = "#7DAFFE"
vim.g.terminal_color_15 = "#FFFFFF"
