-- retro-goldrunner - erzeugt von retro-coding-themes, nicht von Hand aendern.
-- Quelle: src/retro_coding_themes/data/goldrunner.json, Ableitung in derive.py.

vim.cmd("highlight clear")
if vim.fn.exists("syntax_on") == 1 then
  vim.cmd("syntax reset")
end

vim.o.background = "dark"
vim.g.colors_name = "retro-goldrunner"

local hl = vim.api.nvim_set_hl

hl(0, "Normal", { fg = "#EEEECA", bg = "#080520" })
hl(0, "NormalNC", { link = "Normal" })
hl(0, "NormalFloat", { fg = "#EEEECA", bg = "#1F1C31" })
hl(0, "FloatBorder", { fg = "#6A686D", bg = "#1F1C31" })
hl(0, "FloatTitle", { fg = "#E8C547", bg = "#1F1C31", bold = true })
hl(0, "ColorColumn", { bg = "#18152C" })
hl(0, "Conceal", { fg = "#6F6E6C" })
hl(0, "Cursor", { fg = "#080520", bg = "#EEEECA" })
hl(0, "lCursor", { link = "Cursor" })
hl(0, "TermCursor", { link = "Cursor" })
hl(0, "CursorLine", { bg = "#18152C" })
hl(0, "CursorColumn", { link = "CursorLine" })
hl(0, "CursorLineNr", { fg = "#E8C547", bold = true })
hl(0, "LineNr", { fg = "#6F6E6C" })
hl(0, "SignColumn", { bg = "#080520" })
hl(0, "FoldColumn", { fg = "#6F6E6C" })
hl(0, "Folded", { fg = "#9E9C8E", bg = "#1F1C31" })
hl(0, "EndOfBuffer", { fg = "#080520" })
hl(0, "NonText", { fg = "#6F6E6C" })
hl(0, "Whitespace", { fg = "#423F4A" })
hl(0, "SpecialKey", { fg = "#6F6E6C" })
hl(0, "Visual", { bg = "#56482E" })
hl(0, "VisualNOS", { link = "Visual" })
hl(0, "MatchParen", { fg = "#E8C547", bg = "#312F3F", bold = true })
hl(0, "Pmenu", { fg = "#EEEECA", bg = "#1F1C31" })
hl(0, "PmenuSel", { fg = "#EEEECA", bg = "#312F3F", bold = true })
hl(0, "PmenuSbar", { bg = "#1F1C31" })
hl(0, "PmenuThumb", { bg = "#6A686D" })
hl(0, "PmenuKind", { fg = "#A58B1A" })
hl(0, "PmenuKindSel", { fg = "#A58B1A", bg = "#312F3F" })
hl(0, "PmenuExtra", { fg = "#6F6E6C" })
hl(0, "PmenuExtraSel", { fg = "#6F6E6C", bg = "#312F3F" })
hl(0, "WildMenu", { link = "PmenuSel" })
hl(0, "StatusLine", { fg = "#000000", bg = "#C8A93A", bold = true })
hl(0, "StatusLineNC", { fg = "#9E9C8E", bg = "#1F1C31" })
hl(0, "WinBar", { fg = "#9E9C8E", bg = "#080520" })
hl(0, "WinBarNC", { fg = "#6F6E6C", bg = "#080520" })
hl(0, "WinSeparator", { fg = "#6A686D" })
hl(0, "TabLine", { fg = "#9E9C8E", bg = "#1F1C31" })
hl(0, "TabLineFill", { bg = "#080520" })
hl(0, "TabLineSel", { fg = "#000000", bg = "#C8A93A", bold = true })
hl(0, "Search", { fg = "#EEEECA", bg = "#4C2B15" })
hl(0, "IncSearch", { fg = "#080520", bg = "#CA7200", bold = true })
hl(0, "CurSearch", { link = "IncSearch" })
hl(0, "Substitute", { fg = "#080520", bg = "#DB5A7B" })
hl(0, "QuickFixLine", { bg = "#312F3F", bold = true })
hl(0, "Directory", { fg = "#C788CE" })
hl(0, "Title", { fg = "#E8C547", bold = true })
hl(0, "Question", { fg = "#5FA82E" })
hl(0, "MoreMsg", { fg = "#5FA82E" })
hl(0, "ModeMsg", { fg = "#EEEECA", bold = true })
hl(0, "MsgArea", { fg = "#EEEECA", bg = "#080520" })
hl(0, "MsgSeparator", { fg = "#6A686D" })
hl(0, "WarningMsg", { fg = "#CA7200" })
hl(0, "ErrorMsg", { fg = "#DB5A7B" })
hl(0, "SpellBad", { sp = "#DB5A7B", undercurl = true })
hl(0, "SpellCap", { sp = "#CA7200", undercurl = true })
hl(0, "SpellLocal", { sp = "#C8A93A", undercurl = true })
hl(0, "SpellRare", { sp = "#D5ACCD", undercurl = true })
hl(0, "Comment", { fg = "#DBBBCC", italic = true })
hl(0, "Constant", { fg = "#CA7200" })
hl(0, "String", { fg = "#5FA82E" })
hl(0, "Character", { fg = "#5FA82E" })
hl(0, "Number", { fg = "#CA7200" })
hl(0, "Boolean", { fg = "#CA7200" })
hl(0, "Float", { fg = "#CA7200" })
hl(0, "Identifier", { fg = "#EEEECA" })
hl(0, "Function", { fg = "#C788CE" })
hl(0, "Statement", { fg = "#E8C547" })
hl(0, "Conditional", { fg = "#E8C547" })
hl(0, "Repeat", { fg = "#E8C547" })
hl(0, "Label", { fg = "#E8C547" })
hl(0, "Operator", { fg = "#C0BFA8" })
hl(0, "Keyword", { fg = "#E8C547" })
hl(0, "Exception", { fg = "#E8C547" })
hl(0, "PreProc", { fg = "#CF7F4D" })
hl(0, "Include", { fg = "#E8C547" })
hl(0, "Define", { fg = "#CF7F4D" })
hl(0, "Macro", { fg = "#CF7F4D" })
hl(0, "PreCondit", { fg = "#CF7F4D" })
hl(0, "Type", { fg = "#A58B1A" })
hl(0, "StorageClass", { fg = "#E8C547" })
hl(0, "Structure", { fg = "#A58B1A" })
hl(0, "Typedef", { fg = "#A58B1A" })
hl(0, "Special", { fg = "#CF7F4D" })
hl(0, "SpecialChar", { fg = "#CF7F4D" })
hl(0, "Tag", { fg = "#E8C547" })
hl(0, "Delimiter", { fg = "#C0BFA8" })
hl(0, "SpecialComment", { fg = "#DBBBCC", bold = true })
hl(0, "Debug", { fg = "#DB5A7B" })
hl(0, "Underlined", { fg = "#C788CE", underline = true })
hl(0, "Ignore", { fg = "#6F6E6C" })
hl(0, "Error", { fg = "#DB5A7B", bold = true })
hl(0, "Todo", { fg = "#080520", bg = "#CA7200", bold = true })
hl(0, "Added", { fg = "#5FA82E" })
hl(0, "Changed", { fg = "#CA7200" })
hl(0, "Removed", { fg = "#DB5A7B" })
hl(0, "DiffAdd", { bg = "#182223" })
hl(0, "DiffChange", { bg = "#1F121C" })
hl(0, "DiffDelete", { bg = "#2E1430" })
hl(0, "DiffText", { bg = "#422616", bold = true })
hl(0, "DiagnosticError", { fg = "#DB5A7B" })
hl(0, "DiagnosticWarn", { fg = "#CA7200" })
hl(0, "DiagnosticInfo", { fg = "#C8A93A" })
hl(0, "DiagnosticHint", { fg = "#D5ACCD" })
hl(0, "DiagnosticOk", { fg = "#5FA82E" })
hl(0, "DiagnosticUnderlineError", { sp = "#DB5A7B", undercurl = true })
hl(0, "DiagnosticUnderlineWarn", { sp = "#CA7200", undercurl = true })
hl(0, "DiagnosticUnderlineInfo", { sp = "#C8A93A", undercurl = true })
hl(0, "DiagnosticUnderlineHint", { sp = "#D5ACCD", undercurl = true })
hl(0, "DiagnosticUnderlineOk", { sp = "#5FA82E", undercurl = true })
hl(0, "DiagnosticVirtualTextError", { fg = "#DB5A7B", bg = "#210F2B" })
hl(0, "DiagnosticVirtualTextWarn", { fg = "#CA7200", bg = "#1F121C" })
hl(0, "DiagnosticVirtualTextInfo", { fg = "#C8A93A", bg = "#1F1923" })
hl(0, "DiagnosticVirtualTextHint", { fg = "#D5ACCD", bg = "#211935" })
hl(0, "@variable", { fg = "#EEEECA" })
hl(0, "@variable.builtin", { fg = "#CF7F4D", italic = true })
hl(0, "@variable.parameter", { fg = "#EEEECA" })
hl(0, "@variable.member", { fg = "#EEEECA" })
hl(0, "@constant", { fg = "#CA7200" })
hl(0, "@constant.builtin", { fg = "#CF7F4D" })
hl(0, "@constant.macro", { fg = "#CF7F4D" })
hl(0, "@module", { fg = "#A58B1A" })
hl(0, "@label", { fg = "#E8C547" })
hl(0, "@string", { fg = "#5FA82E" })
hl(0, "@string.documentation", { fg = "#DBBBCC" })
hl(0, "@string.escape", { fg = "#CF7F4D" })
hl(0, "@string.regexp", { fg = "#CF7F4D" })
hl(0, "@string.special", { fg = "#CF7F4D" })
hl(0, "@character", { fg = "#5FA82E" })
hl(0, "@character.special", { fg = "#CF7F4D" })
hl(0, "@boolean", { fg = "#CA7200" })
hl(0, "@number", { fg = "#CA7200" })
hl(0, "@number.float", { fg = "#CA7200" })
hl(0, "@type", { fg = "#A58B1A" })
hl(0, "@type.builtin", { fg = "#A58B1A", italic = true })
hl(0, "@type.definition", { fg = "#A58B1A" })
hl(0, "@attribute", { fg = "#CF7F4D" })
hl(0, "@attribute.builtin", { fg = "#CF7F4D" })
hl(0, "@property", { fg = "#EEEECA" })
hl(0, "@function", { fg = "#C788CE" })
hl(0, "@function.builtin", { fg = "#CF7F4D" })
hl(0, "@function.macro", { fg = "#CF7F4D" })
hl(0, "@function.method", { fg = "#C788CE" })
hl(0, "@constructor", { fg = "#A58B1A" })
hl(0, "@operator", { fg = "#C0BFA8" })
hl(0, "@keyword", { fg = "#E8C547" })
hl(0, "@keyword.function", { fg = "#E8C547" })
hl(0, "@keyword.operator", { fg = "#E8C547" })
hl(0, "@keyword.import", { fg = "#E8C547" })
hl(0, "@keyword.return", { fg = "#E8C547" })
hl(0, "@keyword.exception", { fg = "#E8C547" })
hl(0, "@punctuation.delimiter", { fg = "#C0BFA8" })
hl(0, "@punctuation.bracket", { fg = "#C0BFA8" })
hl(0, "@punctuation.special", { fg = "#CF7F4D" })
hl(0, "@comment", { fg = "#DBBBCC", italic = true })
hl(0, "@comment.documentation", { fg = "#DBBBCC", italic = true })
hl(0, "@comment.error", { fg = "#080520", bg = "#DB5A7B", bold = true })
hl(0, "@comment.warning", { fg = "#080520", bg = "#CA7200", bold = true })
hl(0, "@comment.todo", { link = "Todo" })
hl(0, "@comment.note", { fg = "#080520", bg = "#C8A93A", bold = true })
hl(0, "@tag", { fg = "#E8C547" })
hl(0, "@tag.builtin", { fg = "#E8C547" })
hl(0, "@tag.attribute", { fg = "#C788CE", italic = true })
hl(0, "@tag.delimiter", { fg = "#C0BFA8" })
hl(0, "@markup.strong", { fg = "#EEEECA", bold = true })
hl(0, "@markup.italic", { fg = "#EEEECA", italic = true })
hl(0, "@markup.strikethrough", { fg = "#9E9C8E", strikethrough = true })
hl(0, "@markup.underline", { fg = "#EEEECA", underline = true })
hl(0, "@markup.quote", { fg = "#9E9C8E", italic = true })
hl(0, "@markup.math", { fg = "#CA7200" })
hl(0, "@markup.link", { fg = "#C788CE" })
hl(0, "@markup.link.label", { fg = "#E8C547" })
hl(0, "@markup.link.url", { fg = "#C788CE", underline = true })
hl(0, "@markup.raw", { fg = "#5FA82E" })
hl(0, "@markup.list", { fg = "#E8C547" })
hl(0, "@markup.list.checked", { fg = "#5FA82E" })
hl(0, "@markup.list.unchecked", { fg = "#9E9C8E" })
hl(0, "@diff.plus", { fg = "#5FA82E" })
hl(0, "@diff.minus", { fg = "#DB5A7B" })
hl(0, "@diff.delta", { fg = "#CA7200" })
hl(0, "@lsp.type.namespace", { link = "@module" })
hl(0, "@lsp.type.class", { link = "@type" })
hl(0, "@lsp.type.enum", { link = "@type" })
hl(0, "@lsp.type.interface", { link = "@type" })
hl(0, "@lsp.type.struct", { link = "@type" })
hl(0, "@lsp.type.parameter", { link = "@variable.parameter" })
hl(0, "@lsp.type.property", { link = "@property" })
hl(0, "@lsp.type.enumMember", { link = "@constant" })
hl(0, "@lsp.type.method", { link = "@function.method" })
hl(0, "MiniIconsAzure", { fg = "#C788CE" })
hl(0, "MiniIconsBlue", { fg = "#C8A93A" })
hl(0, "MiniIconsCyan", { fg = "#A58B1A" })
hl(0, "MiniIconsGreen", { fg = "#5FA82E" })
hl(0, "MiniIconsGrey", { fg = "#9E9C8E" })
hl(0, "MiniIconsOrange", { fg = "#CA7200" })
hl(0, "MiniIconsPurple", { fg = "#CF7F4D" })
hl(0, "MiniIconsRed", { fg = "#DB5A7B" })
hl(0, "MiniIconsYellow", { fg = "#CA7200" })
hl(0, "MiniFilesTitleFocused", { fg = "#E8C547", bg = "#1F1C31", bold = true })
hl(0, "MiniFilesDirectory", { fg = "#C788CE" })
hl(0, "MiniFilesFile", { fg = "#EEEECA" })
hl(0, "MiniFilesCursorLine", { bg = "#312F3F" })
hl(0, "MiniPickMatchCurrent", { bg = "#312F3F", bold = true })
hl(0, "MiniPickMatchRanges", { fg = "#E8C547", bold = true })
hl(0, "MiniPickPrompt", { fg = "#E8C547", bold = true })
hl(0, "MiniPickBorderText", { fg = "#E8C547" })
hl(0, "MiniClueDescGroup", { fg = "#A58B1A" })
hl(0, "MiniClueDescSingle", { fg = "#EEEECA" })
hl(0, "MiniClueNextKey", { fg = "#E8C547", bold = true })
hl(0, "MiniClueTitle", { fg = "#E8C547", bg = "#1F1C31", bold = true })
hl(0, "RenderMarkdownCode", { bg = "#1F1C31" })
hl(0, "RenderMarkdownCodeInline", { fg = "#5FA82E", bg = "#1F1C31" })
hl(0, "RenderMarkdownBullet", { fg = "#E8C547" })
hl(0, "RenderMarkdownQuote", { fg = "#9E9C8E" })
hl(0, "RenderMarkdownDash", { fg = "#6A686D" })
hl(0, "RenderMarkdownTableHead", { fg = "#A58B1A", bold = true })
hl(0, "RenderMarkdownTableRow", { fg = "#9E9C8E" })
hl(0, "RenderMarkdownLink", { fg = "#C788CE" })
hl(0, "RenderMarkdownChecked", { fg = "#5FA82E" })
hl(0, "RenderMarkdownUnchecked", { fg = "#9E9C8E" })
hl(0, "@markup.heading.1", { fg = "#E8C547", bold = true })
hl(0, "RenderMarkdownH1", { fg = "#E8C547", bold = true })
hl(0, "RenderMarkdownH1Bg", { fg = "#E8C547", bg = "#2A2226", bold = true })
hl(0, "@markup.heading.2", { fg = "#C788CE", bold = true })
hl(0, "RenderMarkdownH2", { fg = "#C788CE", bold = true })
hl(0, "RenderMarkdownH2Bg", { fg = "#C788CE", bg = "#25193A", bold = true })
hl(0, "@markup.heading.3", { fg = "#5FA82E", bold = true })
hl(0, "RenderMarkdownH3", { fg = "#5FA82E", bold = true })
hl(0, "RenderMarkdownH3Bg", { fg = "#5FA82E", bg = "#151D22", bold = true })
hl(0, "@markup.heading.4", { fg = "#CA7200", bold = true })
hl(0, "RenderMarkdownH4", { fg = "#CA7200", bold = true })
hl(0, "RenderMarkdownH4Bg", { fg = "#CA7200", bg = "#25151B", bold = true })
hl(0, "@markup.heading.5", { fg = "#A58B1A", bold = true })
hl(0, "RenderMarkdownH5", { fg = "#A58B1A", bold = true })
hl(0, "RenderMarkdownH5Bg", { fg = "#A58B1A", bg = "#20191F", bold = true })
hl(0, "@markup.heading.6", { fg = "#CF7F4D", bold = true })
hl(0, "RenderMarkdownH6", { fg = "#CF7F4D", bold = true })
hl(0, "RenderMarkdownH6Bg", { fg = "#CF7F4D", bg = "#261727", bold = true })

vim.g.terminal_color_0 = "#423F4A"
vim.g.terminal_color_1 = "#DB5A7B"
vim.g.terminal_color_2 = "#5FA82E"
vim.g.terminal_color_3 = "#CA7200"
vim.g.terminal_color_4 = "#C8A93A"
vim.g.terminal_color_5 = "#CF7F4D"
vim.g.terminal_color_6 = "#E8C547"
vim.g.terminal_color_7 = "#9E9C8E"
vim.g.terminal_color_8 = "#706E6C"
vim.g.terminal_color_9 = "#E27B95"
vim.g.terminal_color_10 = "#7FB958"
vim.g.terminal_color_11 = "#D58E33"
vim.g.terminal_color_12 = "#D3BA61"
vim.g.terminal_color_13 = "#D99971"
vim.g.terminal_color_14 = "#EDD16C"
vim.g.terminal_color_15 = "#EEEECA"
