-- retro-minty - erzeugt von retro-coding-themes, nicht von Hand aendern.
-- Quelle: src/retro_coding_themes/data/minty.json, Ableitung in derive.py.

vim.cmd("highlight clear")
if vim.fn.exists("syntax_on") == 1 then
  vim.cmd("syntax reset")
end

vim.o.background = "dark"
vim.g.colors_name = "retro-minty"

local hl = vim.api.nvim_set_hl

hl(0, "Normal", { fg = "#E8E8E8", bg = "#2B2B2B" })
hl(0, "NormalNC", { link = "Normal" })
hl(0, "NormalFloat", { fg = "#E8E8E8", bg = "#3E3E3E" })
hl(0, "FloatBorder", { fg = "#898989", bg = "#3E3E3E" })
hl(0, "FloatTitle", { fg = "#90B45F", bg = "#3E3E3E", bold = true })
hl(0, "ColorColumn", { bg = "#383838" })
hl(0, "Conceal", { fg = "#888888" })
hl(0, "Cursor", { fg = "#2B2B2B", bg = "#E8E8E8" })
hl(0, "lCursor", { link = "Cursor" })
hl(0, "TermCursor", { link = "Cursor" })
hl(0, "CursorLine", { bg = "#383838" })
hl(0, "CursorColumn", { link = "CursorLine" })
hl(0, "CursorLineNr", { fg = "#90B45F", bold = true })
hl(0, "LineNr", { fg = "#888888" })
hl(0, "SignColumn", { bg = "#2B2B2B" })
hl(0, "FoldColumn", { fg = "#888888" })
hl(0, "Folded", { fg = "#A9A9A9", bg = "#3E3E3E" })
hl(0, "EndOfBuffer", { fg = "#2B2B2B" })
hl(0, "NonText", { fg = "#888888" })
hl(0, "Whitespace", { fg = "#5A5A5A" })
hl(0, "SpecialKey", { fg = "#888888" })
hl(0, "Visual", { bg = "#4D5A3B" })
hl(0, "VisualNOS", { link = "Visual" })
hl(0, "MatchParen", { fg = "#90B45F", bg = "#4D4D4D", bold = true })
hl(0, "Pmenu", { fg = "#E8E8E8", bg = "#3E3E3E" })
hl(0, "PmenuSel", { fg = "#E8E8E8", bg = "#4D4D4D", bold = true })
hl(0, "PmenuSbar", { bg = "#3E3E3E" })
hl(0, "PmenuThumb", { bg = "#898989" })
hl(0, "PmenuKind", { fg = "#CAC699" })
hl(0, "PmenuKindSel", { fg = "#CAC699", bg = "#4D4D4D" })
hl(0, "PmenuExtra", { fg = "#888888" })
hl(0, "PmenuExtraSel", { fg = "#888888", bg = "#4D4D4D" })
hl(0, "WildMenu", { link = "PmenuSel" })
hl(0, "StatusLine", { fg = "#000000", bg = "#8BB158", bold = true })
hl(0, "StatusLineNC", { fg = "#A9A9A9", bg = "#3E3E3E" })
hl(0, "WinBar", { fg = "#A9A9A9", bg = "#2B2B2B" })
hl(0, "WinBarNC", { fg = "#888888", bg = "#2B2B2B" })
hl(0, "WinSeparator", { fg = "#898989" })
hl(0, "TabLine", { fg = "#A9A9A9", bg = "#3E3E3E" })
hl(0, "TabLineFill", { bg = "#2B2B2B" })
hl(0, "TabLineSel", { fg = "#000000", bg = "#8BB158", bold = true })
hl(0, "Search", { fg = "#E8E8E8", bg = "#6F5438" })
hl(0, "IncSearch", { fg = "#2B2B2B", bg = "#ECA04F", bold = true })
hl(0, "CurSearch", { link = "IncSearch" })
hl(0, "Substitute", { fg = "#2B2B2B", bg = "#E49595" })
hl(0, "QuickFixLine", { bg = "#4D4D4D", bold = true })
hl(0, "Directory", { fg = "#86BA8E" })
hl(0, "Title", { fg = "#90B45F", bold = true })
hl(0, "Question", { fg = "#90B45F" })
hl(0, "MoreMsg", { fg = "#90B45F" })
hl(0, "ModeMsg", { fg = "#E8E8E8", bold = true })
hl(0, "MsgArea", { fg = "#E8E8E8", bg = "#2B2B2B" })
hl(0, "MsgSeparator", { fg = "#898989" })
hl(0, "WarningMsg", { fg = "#E5A50A" })
hl(0, "ErrorMsg", { fg = "#E49595" })
hl(0, "SpellBad", { sp = "#E49595", undercurl = true })
hl(0, "SpellCap", { sp = "#E5A50A", undercurl = true })
hl(0, "SpellLocal", { sp = "#90B45F", undercurl = true })
hl(0, "SpellRare", { sp = "#98C09E", undercurl = true })
hl(0, "Comment", { fg = "#AACAAF", italic = true })
hl(0, "Constant", { fg = "#ECA04F" })
hl(0, "String", { fg = "#E5A50A" })
hl(0, "Character", { fg = "#E5A50A" })
hl(0, "Number", { fg = "#ECA04F" })
hl(0, "Boolean", { fg = "#ECA04F" })
hl(0, "Float", { fg = "#ECA04F" })
hl(0, "Identifier", { fg = "#E8E8E8" })
hl(0, "Function", { fg = "#86BA8E" })
hl(0, "Statement", { fg = "#90B45F" })
hl(0, "Conditional", { fg = "#90B45F" })
hl(0, "Repeat", { fg = "#90B45F" })
hl(0, "Label", { fg = "#90B45F" })
hl(0, "Operator", { fg = "#C2C2C2" })
hl(0, "Keyword", { fg = "#90B45F" })
hl(0, "Exception", { fg = "#90B45F" })
hl(0, "PreProc", { fg = "#EEB388" })
hl(0, "Include", { fg = "#90B45F" })
hl(0, "Define", { fg = "#EEB388" })
hl(0, "Macro", { fg = "#EEB388" })
hl(0, "PreCondit", { fg = "#EEB388" })
hl(0, "Type", { fg = "#CAC699" })
hl(0, "StorageClass", { fg = "#90B45F" })
hl(0, "Structure", { fg = "#CAC699" })
hl(0, "Typedef", { fg = "#CAC699" })
hl(0, "Special", { fg = "#EEB388" })
hl(0, "SpecialChar", { fg = "#EEB388" })
hl(0, "Tag", { fg = "#90B45F" })
hl(0, "Delimiter", { fg = "#C2C2C2" })
hl(0, "SpecialComment", { fg = "#AACAAF", bold = true })
hl(0, "Debug", { fg = "#E49595" })
hl(0, "Underlined", { fg = "#86BA8E", underline = true })
hl(0, "Ignore", { fg = "#888888" })
hl(0, "Error", { fg = "#E49595", bold = true })
hl(0, "Todo", { fg = "#2B2B2B", bg = "#ECA04F", bold = true })
hl(0, "Added", { fg = "#90B45F" })
hl(0, "Changed", { fg = "#E5A50A" })
hl(0, "Removed", { fg = "#E49595" })
hl(0, "DiffAdd", { bg = "#3D4434" })
hl(0, "DiffChange", { bg = "#413A27" })
hl(0, "DiffDelete", { bg = "#4C3E3E" })
hl(0, "DiffText", { bg = "#635021", bold = true })
hl(0, "DiagnosticError", { fg = "#E49595" })
hl(0, "DiagnosticWarn", { fg = "#E5A50A" })
hl(0, "DiagnosticInfo", { fg = "#90B45F" })
hl(0, "DiagnosticHint", { fg = "#98C09E" })
hl(0, "DiagnosticOk", { fg = "#90B45F" })
hl(0, "DiagnosticUnderlineError", { sp = "#E49595", undercurl = true })
hl(0, "DiagnosticUnderlineWarn", { sp = "#E5A50A", undercurl = true })
hl(0, "DiagnosticUnderlineInfo", { sp = "#90B45F", undercurl = true })
hl(0, "DiagnosticUnderlineHint", { sp = "#98C09E", undercurl = true })
hl(0, "DiagnosticUnderlineOk", { sp = "#90B45F", undercurl = true })
hl(0, "DiagnosticVirtualTextError", { fg = "#E49595", bg = "#413838" })
hl(0, "DiagnosticVirtualTextWarn", { fg = "#E5A50A", bg = "#413A27" })
hl(0, "DiagnosticVirtualTextInfo", { fg = "#90B45F", bg = "#373B31" })
hl(0, "DiagnosticVirtualTextHint", { fg = "#98C09E", bg = "#383D39" })
hl(0, "@variable", { fg = "#E8E8E8" })
hl(0, "@variable.builtin", { fg = "#EEB388", italic = true })
hl(0, "@variable.parameter", { fg = "#E8E8E8" })
hl(0, "@variable.member", { fg = "#E8E8E8" })
hl(0, "@constant", { fg = "#ECA04F" })
hl(0, "@constant.builtin", { fg = "#EEB388" })
hl(0, "@constant.macro", { fg = "#EEB388" })
hl(0, "@module", { fg = "#CAC699" })
hl(0, "@label", { fg = "#90B45F" })
hl(0, "@string", { fg = "#E5A50A" })
hl(0, "@string.documentation", { fg = "#AACAAF" })
hl(0, "@string.escape", { fg = "#EEB388" })
hl(0, "@string.regexp", { fg = "#EEB388" })
hl(0, "@string.special", { fg = "#EEB388" })
hl(0, "@character", { fg = "#E5A50A" })
hl(0, "@character.special", { fg = "#EEB388" })
hl(0, "@boolean", { fg = "#ECA04F" })
hl(0, "@number", { fg = "#ECA04F" })
hl(0, "@number.float", { fg = "#ECA04F" })
hl(0, "@type", { fg = "#CAC699" })
hl(0, "@type.builtin", { fg = "#CAC699", italic = true })
hl(0, "@type.definition", { fg = "#CAC699" })
hl(0, "@attribute", { fg = "#EEB388" })
hl(0, "@attribute.builtin", { fg = "#EEB388" })
hl(0, "@property", { fg = "#E8E8E8" })
hl(0, "@function", { fg = "#86BA8E" })
hl(0, "@function.builtin", { fg = "#EEB388" })
hl(0, "@function.macro", { fg = "#EEB388" })
hl(0, "@function.method", { fg = "#86BA8E" })
hl(0, "@constructor", { fg = "#CAC699" })
hl(0, "@operator", { fg = "#C2C2C2" })
hl(0, "@keyword", { fg = "#90B45F" })
hl(0, "@keyword.function", { fg = "#90B45F" })
hl(0, "@keyword.operator", { fg = "#90B45F" })
hl(0, "@keyword.import", { fg = "#90B45F" })
hl(0, "@keyword.return", { fg = "#90B45F" })
hl(0, "@keyword.exception", { fg = "#90B45F" })
hl(0, "@punctuation.delimiter", { fg = "#C2C2C2" })
hl(0, "@punctuation.bracket", { fg = "#C2C2C2" })
hl(0, "@punctuation.special", { fg = "#EEB388" })
hl(0, "@comment", { fg = "#AACAAF", italic = true })
hl(0, "@comment.documentation", { fg = "#AACAAF", italic = true })
hl(0, "@comment.error", { fg = "#2B2B2B", bg = "#E49595", bold = true })
hl(0, "@comment.warning", { fg = "#2B2B2B", bg = "#E5A50A", bold = true })
hl(0, "@comment.todo", { link = "Todo" })
hl(0, "@comment.note", { fg = "#2B2B2B", bg = "#90B45F", bold = true })
hl(0, "@tag", { fg = "#90B45F" })
hl(0, "@tag.builtin", { fg = "#90B45F" })
hl(0, "@tag.attribute", { fg = "#86BA8E", italic = true })
hl(0, "@tag.delimiter", { fg = "#C2C2C2" })
hl(0, "@markup.strong", { fg = "#E8E8E8", bold = true })
hl(0, "@markup.italic", { fg = "#E8E8E8", italic = true })
hl(0, "@markup.strikethrough", { fg = "#A9A9A9", strikethrough = true })
hl(0, "@markup.underline", { fg = "#E8E8E8", underline = true })
hl(0, "@markup.quote", { fg = "#A9A9A9", italic = true })
hl(0, "@markup.math", { fg = "#ECA04F" })
hl(0, "@markup.link", { fg = "#86BA8E" })
hl(0, "@markup.link.label", { fg = "#90B45F" })
hl(0, "@markup.link.url", { fg = "#86BA8E", underline = true })
hl(0, "@markup.raw", { fg = "#E5A50A" })
hl(0, "@markup.list", { fg = "#90B45F" })
hl(0, "@markup.list.checked", { fg = "#90B45F" })
hl(0, "@markup.list.unchecked", { fg = "#A9A9A9" })
hl(0, "@diff.plus", { fg = "#90B45F" })
hl(0, "@diff.minus", { fg = "#E49595" })
hl(0, "@diff.delta", { fg = "#E5A50A" })
hl(0, "@lsp.type.namespace", { link = "@module" })
hl(0, "@lsp.type.class", { link = "@type" })
hl(0, "@lsp.type.enum", { link = "@type" })
hl(0, "@lsp.type.interface", { link = "@type" })
hl(0, "@lsp.type.struct", { link = "@type" })
hl(0, "@lsp.type.parameter", { link = "@variable.parameter" })
hl(0, "@lsp.type.property", { link = "@property" })
hl(0, "@lsp.type.enumMember", { link = "@constant" })
hl(0, "@lsp.type.method", { link = "@function.method" })
hl(0, "MiniIconsAzure", { fg = "#86BA8E" })
hl(0, "MiniIconsBlue", { fg = "#90B45F" })
hl(0, "MiniIconsCyan", { fg = "#CAC699" })
hl(0, "MiniIconsGreen", { fg = "#90B45F" })
hl(0, "MiniIconsGrey", { fg = "#A9A9A9" })
hl(0, "MiniIconsOrange", { fg = "#ECA04F" })
hl(0, "MiniIconsPurple", { fg = "#EEB388" })
hl(0, "MiniIconsRed", { fg = "#E49595" })
hl(0, "MiniIconsYellow", { fg = "#E5A50A" })
hl(0, "MiniFilesTitleFocused", { fg = "#90B45F", bg = "#3E3E3E", bold = true })
hl(0, "MiniFilesDirectory", { fg = "#86BA8E" })
hl(0, "MiniFilesFile", { fg = "#E8E8E8" })
hl(0, "MiniFilesCursorLine", { bg = "#4D4D4D" })
hl(0, "MiniPickMatchCurrent", { bg = "#4D4D4D", bold = true })
hl(0, "MiniPickMatchRanges", { fg = "#90B45F", bold = true })
hl(0, "MiniPickPrompt", { fg = "#90B45F", bold = true })
hl(0, "MiniPickBorderText", { fg = "#90B45F" })
hl(0, "MiniClueDescGroup", { fg = "#CAC699" })
hl(0, "MiniClueDescSingle", { fg = "#E8E8E8" })
hl(0, "MiniClueNextKey", { fg = "#90B45F", bold = true })
hl(0, "MiniClueTitle", { fg = "#90B45F", bg = "#3E3E3E", bold = true })
hl(0, "RenderMarkdownCode", { bg = "#3E3E3E" })
hl(0, "RenderMarkdownCodeInline", { fg = "#E5A50A", bg = "#3E3E3E" })
hl(0, "RenderMarkdownBullet", { fg = "#90B45F" })
hl(0, "RenderMarkdownQuote", { fg = "#A9A9A9" })
hl(0, "RenderMarkdownDash", { fg = "#898989" })
hl(0, "RenderMarkdownTableHead", { fg = "#CAC699", bold = true })
hl(0, "RenderMarkdownTableRow", { fg = "#A9A9A9" })
hl(0, "RenderMarkdownLink", { fg = "#86BA8E" })
hl(0, "RenderMarkdownChecked", { fg = "#90B45F" })
hl(0, "RenderMarkdownUnchecked", { fg = "#A9A9A9" })
hl(0, "@markup.heading.1", { fg = "#90B45F", bold = true })
hl(0, "RenderMarkdownH1", { fg = "#90B45F", bold = true })
hl(0, "RenderMarkdownH1Bg", { fg = "#90B45F", bg = "#3A4033", bold = true })
hl(0, "@markup.heading.2", { fg = "#86BA8E", bold = true })
hl(0, "RenderMarkdownH2", { fg = "#86BA8E", bold = true })
hl(0, "RenderMarkdownH2Bg", { fg = "#86BA8E", bg = "#39403A", bold = true })
hl(0, "@markup.heading.3", { fg = "#E5A50A", bold = true })
hl(0, "RenderMarkdownH3", { fg = "#E5A50A", bold = true })
hl(0, "RenderMarkdownH3Bg", { fg = "#E5A50A", bg = "#473D26", bold = true })
hl(0, "@markup.heading.4", { fg = "#ECA04F", bold = true })
hl(0, "RenderMarkdownH4", { fg = "#ECA04F", bold = true })
hl(0, "RenderMarkdownH4Bg", { fg = "#ECA04F", bg = "#483D30", bold = true })
hl(0, "@markup.heading.5", { fg = "#CAC699", bold = true })
hl(0, "RenderMarkdownH5", { fg = "#CAC699", bold = true })
hl(0, "RenderMarkdownH5Bg", { fg = "#CAC699", bg = "#43423C", bold = true })
hl(0, "@markup.heading.6", { fg = "#EEB388", bold = true })
hl(0, "RenderMarkdownH6", { fg = "#EEB388", bold = true })
hl(0, "RenderMarkdownH6Bg", { fg = "#EEB388", bg = "#483F39", bold = true })

vim.g.terminal_color_0 = "#5A5A5A"
vim.g.terminal_color_1 = "#E49595"
vim.g.terminal_color_2 = "#90B45F"
vim.g.terminal_color_3 = "#E5A50A"
vim.g.terminal_color_4 = "#90B45F"
vim.g.terminal_color_5 = "#EEB388"
vim.g.terminal_color_6 = "#90B45F"
vim.g.terminal_color_7 = "#A9A9A9"
vim.g.terminal_color_8 = "#808080"
vim.g.terminal_color_9 = "#E9AAAA"
vim.g.terminal_color_10 = "#A6C37F"
vim.g.terminal_color_11 = "#EAB73B"
vim.g.terminal_color_12 = "#A6C37F"
vim.g.terminal_color_13 = "#F1C2A0"
vim.g.terminal_color_14 = "#A6C37F"
vim.g.terminal_color_15 = "#E8E8E8"
