-- retro-commandr - erzeugt von retro-coding-themes, nicht von Hand aendern.
-- Quelle: src/retro_coding_themes/data/commandr.json, Ableitung in derive.py.

vim.cmd("highlight clear")
if vim.fn.exists("syntax_on") == 1 then
  vim.cmd("syntax reset")
end

vim.o.background = "dark"
vim.g.colors_name = "retro-commandr"

local hl = vim.api.nvim_set_hl

hl(0, "Normal", { fg = "#FFFFFF", bg = "#0000AA" })
hl(0, "NormalNC", { link = "Normal" })
hl(0, "NormalFloat", { fg = "#FFFFFF", bg = "#1A1AB2" })
hl(0, "FloatBorder", { fg = "#7B7BD3", bg = "#1A1AB2" })
hl(0, "FloatTitle", { fg = "#FFFF55", bg = "#1A1AB2", bold = true })
hl(0, "ColorColumn", { bg = "#1212B0" })
hl(0, "Conceal", { fg = "#7B7BD3" })
hl(0, "Cursor", { fg = "#0000AA", bg = "#FFFFFF" })
hl(0, "lCursor", { link = "Cursor" })
hl(0, "TermCursor", { link = "Cursor" })
hl(0, "CursorLine", { bg = "#1212B0" })
hl(0, "CursorColumn", { link = "CursorLine" })
hl(0, "CursorLineNr", { fg = "#FFFF55", bold = true })
hl(0, "LineNr", { fg = "#7B7BD3" })
hl(0, "SignColumn", { bg = "#0000AA" })
hl(0, "FoldColumn", { fg = "#7B7BD3" })
hl(0, "Folded", { fg = "#A6A6E1", bg = "#1A1AB2" })
hl(0, "EndOfBuffer", { fg = "#0000AA" })
hl(0, "NonText", { fg = "#7B7BD3" })
hl(0, "Whitespace", { fg = "#4040BF" })
hl(0, "SpecialKey", { fg = "#7B7BD3" })
hl(0, "Visual", { bg = "#59598C" })
hl(0, "VisualNOS", { link = "Visual" })
hl(0, "MatchParen", { fg = "#FFFF55", bg = "#2E2EB9", bold = true })
hl(0, "Pmenu", { fg = "#FFFFFF", bg = "#1A1AB2" })
hl(0, "PmenuSel", { fg = "#FFFFFF", bg = "#2E2EB9", bold = true })
hl(0, "PmenuSbar", { bg = "#1A1AB2" })
hl(0, "PmenuThumb", { bg = "#7B7BD3" })
hl(0, "PmenuKind", { fg = "#AAFF55" })
hl(0, "PmenuKindSel", { fg = "#AAFF55", bg = "#2E2EB9" })
hl(0, "PmenuExtra", { fg = "#7B7BD3" })
hl(0, "PmenuExtraSel", { fg = "#7B7BD3", bg = "#2E2EB9" })
hl(0, "WildMenu", { link = "PmenuSel" })
hl(0, "StatusLine", { fg = "#000000", bg = "#FFFF55", bold = true })
hl(0, "StatusLineNC", { fg = "#A6A6E1", bg = "#1A1AB2" })
hl(0, "WinBar", { fg = "#A6A6E1", bg = "#0000AA" })
hl(0, "WinBarNC", { fg = "#7B7BD3", bg = "#0000AA" })
hl(0, "WinSeparator", { fg = "#7B7BD3" })
hl(0, "TabLine", { fg = "#A6A6E1", bg = "#1A1AB2" })
hl(0, "TabLineFill", { bg = "#0000AA" })
hl(0, "TabLineSel", { fg = "#000000", bg = "#FFFF55", bold = true })
hl(0, "Search", { fg = "#FFFFFF", bg = "#593B6E" })
hl(0, "IncSearch", { fg = "#0000AA", bg = "#FFAA00", bold = true })
hl(0, "CurSearch", { link = "IncSearch" })
hl(0, "Substitute", { fg = "#0000AA", bg = "#FF7979" })
hl(0, "QuickFixLine", { bg = "#2E2EB9", bold = true })
hl(0, "Directory", { fg = "#55FFFF" })
hl(0, "Title", { fg = "#FFFF55", bold = true })
hl(0, "Question", { fg = "#55FF55" })
hl(0, "MoreMsg", { fg = "#55FF55" })
hl(0, "ModeMsg", { fg = "#FFFFFF", bold = true })
hl(0, "MsgArea", { fg = "#FFFFFF", bg = "#0000AA" })
hl(0, "MsgSeparator", { fg = "#7B7BD3" })
hl(0, "WarningMsg", { fg = "#FFAA00" })
hl(0, "ErrorMsg", { fg = "#FF7979" })
hl(0, "SpellBad", { sp = "#FF7979", undercurl = true })
hl(0, "SpellCap", { sp = "#FFAA00", undercurl = true })
hl(0, "SpellLocal", { sp = "#FFFF55", undercurl = true })
hl(0, "SpellRare", { sp = "#90FFFF", undercurl = true })
hl(0, "Comment", { fg = "#AAFFFF", italic = true })
hl(0, "Constant", { fg = "#FFAA00" })
hl(0, "String", { fg = "#55FF55" })
hl(0, "Character", { fg = "#55FF55" })
hl(0, "Number", { fg = "#FFAA00" })
hl(0, "Boolean", { fg = "#FFAA00" })
hl(0, "Float", { fg = "#FFAA00" })
hl(0, "Identifier", { fg = "#FFFFFF" })
hl(0, "Function", { fg = "#55FFFF" })
hl(0, "Statement", { fg = "#FFFF55" })
hl(0, "Conditional", { fg = "#FFFF55" })
hl(0, "Repeat", { fg = "#FFFF55" })
hl(0, "Label", { fg = "#FFFF55" })
hl(0, "Operator", { fg = "#CCCCEE" })
hl(0, "Keyword", { fg = "#FFFF55" })
hl(0, "Exception", { fg = "#FFFF55" })
hl(0, "PreProc", { fg = "#FF802A" })
hl(0, "Include", { fg = "#FFFF55" })
hl(0, "Define", { fg = "#FF802A" })
hl(0, "Macro", { fg = "#FF802A" })
hl(0, "PreCondit", { fg = "#FF802A" })
hl(0, "Type", { fg = "#AAFF55" })
hl(0, "StorageClass", { fg = "#FFFF55" })
hl(0, "Structure", { fg = "#AAFF55" })
hl(0, "Typedef", { fg = "#AAFF55" })
hl(0, "Special", { fg = "#FF802A" })
hl(0, "SpecialChar", { fg = "#FF802A" })
hl(0, "Tag", { fg = "#FFFF55" })
hl(0, "Delimiter", { fg = "#CCCCEE" })
hl(0, "SpecialComment", { fg = "#AAFFFF", bold = true })
hl(0, "Debug", { fg = "#FF7979" })
hl(0, "Underlined", { fg = "#55FFFF", underline = true })
hl(0, "Ignore", { fg = "#7B7BD3" })
hl(0, "Error", { fg = "#FF7979", bold = true })
hl(0, "Todo", { fg = "#0000AA", bg = "#FFAA00", bold = true })
hl(0, "Added", { fg = "#55FF55" })
hl(0, "Changed", { fg = "#FFAA00" })
hl(0, "Removed", { fg = "#FF7979" })
hl(0, "DiffAdd", { bg = "#0F2E9B" })
hl(0, "DiffChange", { bg = "#1F1496" })
hl(0, "DiffDelete", { bg = "#2E16A1" })
hl(0, "DiffText", { bg = "#4C3377", bold = true })
hl(0, "DiagnosticError", { fg = "#FF7979" })
hl(0, "DiagnosticWarn", { fg = "#FFAA00" })
hl(0, "DiagnosticInfo", { fg = "#FFFF55" })
hl(0, "DiagnosticHint", { fg = "#90FFFF" })
hl(0, "DiagnosticOk", { fg = "#55FF55" })
hl(0, "DiagnosticUnderlineError", { sp = "#FF7979", undercurl = true })
hl(0, "DiagnosticUnderlineWarn", { sp = "#FFAA00", undercurl = true })
hl(0, "DiagnosticUnderlineInfo", { sp = "#FFFF55", undercurl = true })
hl(0, "DiagnosticUnderlineHint", { sp = "#90FFFF", undercurl = true })
hl(0, "DiagnosticUnderlineOk", { sp = "#55FF55", undercurl = true })
hl(0, "DiagnosticVirtualTextError", { fg = "#FF7979", bg = "#1F0FA4" })
hl(0, "DiagnosticVirtualTextWarn", { fg = "#FFAA00", bg = "#1F1496" })
hl(0, "DiagnosticVirtualTextInfo", { fg = "#FFFF55", bg = "#1F1FA0" })
hl(0, "DiagnosticVirtualTextHint", { fg = "#90FFFF", bg = "#111FB4" })
hl(0, "@variable", { fg = "#FFFFFF" })
hl(0, "@variable.builtin", { fg = "#FF802A", italic = true })
hl(0, "@variable.parameter", { fg = "#FFFFFF" })
hl(0, "@variable.member", { fg = "#FFFFFF" })
hl(0, "@constant", { fg = "#FFAA00" })
hl(0, "@constant.builtin", { fg = "#FF802A" })
hl(0, "@constant.macro", { fg = "#FF802A" })
hl(0, "@module", { fg = "#AAFF55" })
hl(0, "@label", { fg = "#FFFF55" })
hl(0, "@string", { fg = "#55FF55" })
hl(0, "@string.documentation", { fg = "#AAFFFF" })
hl(0, "@string.escape", { fg = "#FF802A" })
hl(0, "@string.regexp", { fg = "#FF802A" })
hl(0, "@string.special", { fg = "#FF802A" })
hl(0, "@character", { fg = "#55FF55" })
hl(0, "@character.special", { fg = "#FF802A" })
hl(0, "@boolean", { fg = "#FFAA00" })
hl(0, "@number", { fg = "#FFAA00" })
hl(0, "@number.float", { fg = "#FFAA00" })
hl(0, "@type", { fg = "#AAFF55" })
hl(0, "@type.builtin", { fg = "#AAFF55", italic = true })
hl(0, "@type.definition", { fg = "#AAFF55" })
hl(0, "@attribute", { fg = "#FF802A" })
hl(0, "@attribute.builtin", { fg = "#FF802A" })
hl(0, "@property", { fg = "#FFFFFF" })
hl(0, "@function", { fg = "#55FFFF" })
hl(0, "@function.builtin", { fg = "#FF802A" })
hl(0, "@function.macro", { fg = "#FF802A" })
hl(0, "@function.method", { fg = "#55FFFF" })
hl(0, "@constructor", { fg = "#AAFF55" })
hl(0, "@operator", { fg = "#CCCCEE" })
hl(0, "@keyword", { fg = "#FFFF55" })
hl(0, "@keyword.function", { fg = "#FFFF55" })
hl(0, "@keyword.operator", { fg = "#FFFF55" })
hl(0, "@keyword.import", { fg = "#FFFF55" })
hl(0, "@keyword.return", { fg = "#FFFF55" })
hl(0, "@keyword.exception", { fg = "#FFFF55" })
hl(0, "@punctuation.delimiter", { fg = "#CCCCEE" })
hl(0, "@punctuation.bracket", { fg = "#CCCCEE" })
hl(0, "@punctuation.special", { fg = "#FF802A" })
hl(0, "@comment", { fg = "#AAFFFF", italic = true })
hl(0, "@comment.documentation", { fg = "#AAFFFF", italic = true })
hl(0, "@comment.error", { fg = "#0000AA", bg = "#FF7979", bold = true })
hl(0, "@comment.warning", { fg = "#0000AA", bg = "#FFAA00", bold = true })
hl(0, "@comment.todo", { link = "Todo" })
hl(0, "@comment.note", { fg = "#0000AA", bg = "#FFFF55", bold = true })
hl(0, "@tag", { fg = "#FFFF55" })
hl(0, "@tag.builtin", { fg = "#FFFF55" })
hl(0, "@tag.attribute", { fg = "#55FFFF", italic = true })
hl(0, "@tag.delimiter", { fg = "#CCCCEE" })
hl(0, "@markup.strong", { fg = "#FFFFFF", bold = true })
hl(0, "@markup.italic", { fg = "#FFFFFF", italic = true })
hl(0, "@markup.strikethrough", { fg = "#A6A6E1", strikethrough = true })
hl(0, "@markup.underline", { fg = "#FFFFFF", underline = true })
hl(0, "@markup.quote", { fg = "#A6A6E1", italic = true })
hl(0, "@markup.math", { fg = "#FFAA00" })
hl(0, "@markup.link", { fg = "#55FFFF" })
hl(0, "@markup.link.label", { fg = "#FFFF55" })
hl(0, "@markup.link.url", { fg = "#55FFFF", underline = true })
hl(0, "@markup.raw", { fg = "#55FF55" })
hl(0, "@markup.list", { fg = "#FFFF55" })
hl(0, "@markup.list.checked", { fg = "#55FF55" })
hl(0, "@markup.list.unchecked", { fg = "#A6A6E1" })
hl(0, "@diff.plus", { fg = "#55FF55" })
hl(0, "@diff.minus", { fg = "#FF7979" })
hl(0, "@diff.delta", { fg = "#FFAA00" })
hl(0, "@lsp.type.namespace", { link = "@module" })
hl(0, "@lsp.type.class", { link = "@type" })
hl(0, "@lsp.type.enum", { link = "@type" })
hl(0, "@lsp.type.interface", { link = "@type" })
hl(0, "@lsp.type.struct", { link = "@type" })
hl(0, "@lsp.type.parameter", { link = "@variable.parameter" })
hl(0, "@lsp.type.property", { link = "@property" })
hl(0, "@lsp.type.enumMember", { link = "@constant" })
hl(0, "@lsp.type.method", { link = "@function.method" })
hl(0, "MiniIconsAzure", { fg = "#55FFFF" })
hl(0, "MiniIconsBlue", { fg = "#FFFF55" })
hl(0, "MiniIconsCyan", { fg = "#AAFF55" })
hl(0, "MiniIconsGreen", { fg = "#55FF55" })
hl(0, "MiniIconsGrey", { fg = "#A6A6E1" })
hl(0, "MiniIconsOrange", { fg = "#FFAA00" })
hl(0, "MiniIconsPurple", { fg = "#FF802A" })
hl(0, "MiniIconsRed", { fg = "#FF7979" })
hl(0, "MiniIconsYellow", { fg = "#FFAA00" })
hl(0, "MiniFilesTitleFocused", { fg = "#FFFF55", bg = "#1A1AB2", bold = true })
hl(0, "MiniFilesDirectory", { fg = "#55FFFF" })
hl(0, "MiniFilesFile", { fg = "#FFFFFF" })
hl(0, "MiniFilesCursorLine", { bg = "#2E2EB9" })
hl(0, "MiniPickMatchCurrent", { bg = "#2E2EB9", bold = true })
hl(0, "MiniPickMatchRanges", { fg = "#FFFF55", bold = true })
hl(0, "MiniPickPrompt", { fg = "#FFFF55", bold = true })
hl(0, "MiniPickBorderText", { fg = "#FFFF55" })
hl(0, "MiniClueDescGroup", { fg = "#AAFF55" })
hl(0, "MiniClueDescSingle", { fg = "#FFFFFF" })
hl(0, "MiniClueNextKey", { fg = "#FFFF55", bold = true })
hl(0, "MiniClueTitle", { fg = "#FFFF55", bg = "#1A1AB2", bold = true })
hl(0, "RenderMarkdownCode", { bg = "#1A1AB2" })
hl(0, "RenderMarkdownCodeInline", { fg = "#55FF55", bg = "#1A1AB2" })
hl(0, "RenderMarkdownBullet", { fg = "#FFFF55" })
hl(0, "RenderMarkdownQuote", { fg = "#A6A6E1" })
hl(0, "RenderMarkdownDash", { fg = "#7B7BD3" })
hl(0, "RenderMarkdownTableHead", { fg = "#AAFF55", bold = true })
hl(0, "RenderMarkdownTableRow", { fg = "#A6A6E1" })
hl(0, "RenderMarkdownLink", { fg = "#55FFFF" })
hl(0, "RenderMarkdownChecked", { fg = "#55FF55" })
hl(0, "RenderMarkdownUnchecked", { fg = "#A6A6E1" })
hl(0, "@markup.heading.1", { fg = "#FFFF55", bold = true })
hl(0, "RenderMarkdownH1", { fg = "#FFFF55", bold = true })
hl(0, "RenderMarkdownH1Bg", { fg = "#FFFF55", bg = "#26269D", bold = true })
hl(0, "@markup.heading.2", { fg = "#55FFFF", bold = true })
hl(0, "RenderMarkdownH2", { fg = "#55FFFF", bold = true })
hl(0, "RenderMarkdownH2Bg", { fg = "#55FFFF", bg = "#0D26B7", bold = true })
hl(0, "@markup.heading.3", { fg = "#55FF55", bold = true })
hl(0, "RenderMarkdownH3", { fg = "#55FF55", bold = true })
hl(0, "RenderMarkdownH3Bg", { fg = "#55FF55", bg = "#0D269D", bold = true })
hl(0, "@markup.heading.4", { fg = "#FFAA00", bold = true })
hl(0, "RenderMarkdownH4", { fg = "#FFAA00", bold = true })
hl(0, "RenderMarkdownH4Bg", { fg = "#FFAA00", bg = "#261990", bold = true })
hl(0, "@markup.heading.5", { fg = "#AAFF55", bold = true })
hl(0, "RenderMarkdownH5", { fg = "#AAFF55", bold = true })
hl(0, "RenderMarkdownH5Bg", { fg = "#AAFF55", bg = "#19269D", bold = true })
hl(0, "@markup.heading.6", { fg = "#FF802A", bold = true })
hl(0, "RenderMarkdownH6", { fg = "#FF802A", bold = true })
hl(0, "RenderMarkdownH6Bg", { fg = "#FF802A", bg = "#261397", bold = true })

vim.g.terminal_color_0 = "#4040BF"
vim.g.terminal_color_1 = "#FF7979"
vim.g.terminal_color_2 = "#55FF55"
vim.g.terminal_color_3 = "#FFAA00"
vim.g.terminal_color_4 = "#FFFF55"
vim.g.terminal_color_5 = "#FF802A"
vim.g.terminal_color_6 = "#FFFF55"
vim.g.terminal_color_7 = "#A6A6E1"
vim.g.terminal_color_8 = "#7373D0"
vim.g.terminal_color_9 = "#FF9494"
vim.g.terminal_color_10 = "#77FF77"
vim.g.terminal_color_11 = "#FFBB33"
vim.g.terminal_color_12 = "#FFFF77"
vim.g.terminal_color_13 = "#FF9955"
vim.g.terminal_color_14 = "#FFFF77"
vim.g.terminal_color_15 = "#FFFFFF"
