"""Ordnet die Farbrollen den Hervorhebungsgruppen von Neovim zu."""

from __future__ import annotations

from ..color import mix
from ..derive import Scheme

# Ein Eintrag ist entweder ein Verweis auf eine andere Gruppe oder eine Farbangabe
Spec = dict[str, str | bool]


def _fg(color: str, **flags: bool) -> Spec:
    return {"fg": color, **flags}


def build(s: Scheme) -> dict[str, Spec]:
    """Baut die vollstaendige Gruppentabelle eines Themes."""
    heading = (s.keyword, s.function, s.string, s.number, s.type_, s.special)
    groups: dict[str, Spec] = {
        # --- Oberflaeche ---
        "Normal": {"fg": s.fg, "bg": s.bg},
        "NormalNC": {"link": "Normal"},
        "NormalFloat": {"fg": s.fg, "bg": s.bg_float},
        "FloatBorder": {"fg": s.border, "bg": s.bg_float},
        "FloatTitle": {"fg": s.accent, "bg": s.bg_float, "bold": True},
        "ColorColumn": {"bg": s.bg_cursorline},
        "Conceal": _fg(s.fg_faint),
        "Cursor": {"fg": s.bg, "bg": s.fg},
        "lCursor": {"link": "Cursor"},
        "TermCursor": {"link": "Cursor"},
        "CursorLine": {"bg": s.bg_cursorline},
        "CursorColumn": {"link": "CursorLine"},
        "CursorLineNr": {"fg": s.accent, "bold": True},
        "LineNr": _fg(s.fg_faint),
        "SignColumn": {"bg": s.bg},
        "FoldColumn": _fg(s.fg_faint),
        "Folded": {"fg": s.fg_dim, "bg": s.bg_float},
        "EndOfBuffer": _fg(s.bg),
        "NonText": _fg(s.fg_faint),
        "Whitespace": _fg(mix(s.bg, s.fg, 0.25)),
        "SpecialKey": _fg(s.fg_faint),
        "Visual": {"bg": s.bg_visual},
        "VisualNOS": {"link": "Visual"},
        "MatchParen": {"fg": s.accent, "bg": s.bg_elevated, "bold": True},
        "Pmenu": {"fg": s.fg, "bg": s.bg_float},
        "PmenuSel": {"fg": s.fg, "bg": s.bg_elevated, "bold": True},
        "PmenuSbar": {"bg": s.bg_float},
        "PmenuThumb": {"bg": s.border},
        "PmenuKind": _fg(s.type_),
        "PmenuKindSel": {"fg": s.type_, "bg": s.bg_elevated},
        "PmenuExtra": _fg(s.fg_faint),
        "PmenuExtraSel": {"fg": s.fg_faint, "bg": s.bg_elevated},
        "WildMenu": {"link": "PmenuSel"},
        "StatusLine": {"fg": s.statusline_fg, "bg": s.statusline_bg, "bold": True},
        "StatusLineNC": {"fg": s.fg_dim, "bg": s.bg_float},
        "WinBar": {"fg": s.fg_dim, "bg": s.bg},
        "WinBarNC": {"fg": s.fg_faint, "bg": s.bg},
        "WinSeparator": _fg(s.border),
        "TabLine": {"fg": s.fg_dim, "bg": s.bg_float},
        "TabLineFill": {"bg": s.bg},
        "TabLineSel": {"fg": s.statusline_fg, "bg": s.statusline_bg, "bold": True},
        "Search": {"fg": s.fg, "bg": mix(s.bg, s.number, 0.35)},
        "IncSearch": {"fg": s.bg, "bg": s.number, "bold": True},
        "CurSearch": {"link": "IncSearch"},
        "Substitute": {"fg": s.bg, "bg": s.error},
        "QuickFixLine": {"bg": s.bg_elevated, "bold": True},
        "Directory": _fg(s.function),
        "Title": _fg(s.accent, bold=True),
        "Question": _fg(s.success),
        "MoreMsg": _fg(s.success),
        "ModeMsg": _fg(s.fg, bold=True),
        "MsgArea": {"fg": s.fg, "bg": s.bg},
        "MsgSeparator": _fg(s.border),
        "WarningMsg": _fg(s.warning),
        "ErrorMsg": _fg(s.error),
        "SpellBad": {"sp": s.error, "undercurl": True},
        "SpellCap": {"sp": s.warning, "undercurl": True},
        "SpellLocal": {"sp": s.info, "undercurl": True},
        "SpellRare": {"sp": s.hint, "undercurl": True},
        # --- Klassische Syntaxgruppen ---
        "Comment": _fg(s.comment, italic=True),
        "Constant": _fg(s.number),
        "String": _fg(s.string),
        "Character": _fg(s.string),
        "Number": _fg(s.number),
        "Boolean": _fg(s.number),
        "Float": _fg(s.number),
        "Identifier": _fg(s.fg),
        "Function": _fg(s.function),
        "Statement": _fg(s.keyword),
        "Conditional": _fg(s.keyword),
        "Repeat": _fg(s.keyword),
        "Label": _fg(s.keyword),
        "Operator": _fg(s.operator),
        "Keyword": _fg(s.keyword),
        "Exception": _fg(s.keyword),
        "PreProc": _fg(s.special),
        "Include": _fg(s.keyword),
        "Define": _fg(s.special),
        "Macro": _fg(s.special),
        "PreCondit": _fg(s.special),
        "Type": _fg(s.type_),
        "StorageClass": _fg(s.keyword),
        "Structure": _fg(s.type_),
        "Typedef": _fg(s.type_),
        "Special": _fg(s.special),
        "SpecialChar": _fg(s.special),
        "Tag": _fg(s.keyword),
        "Delimiter": _fg(s.operator),
        "SpecialComment": _fg(s.comment, bold=True),
        "Debug": _fg(s.error),
        "Underlined": _fg(s.function, underline=True),
        "Ignore": _fg(s.fg_faint),
        "Error": {"fg": s.error, "bold": True},
        "Todo": {"fg": s.bg, "bg": s.number, "bold": True},
        "Added": _fg(s.success),
        "Changed": _fg(s.warning),
        "Removed": _fg(s.error),
        # --- Diff ---
        "DiffAdd": {"bg": mix(s.bg, s.success, 0.18)},
        "DiffChange": {"bg": mix(s.bg, s.warning, 0.12)},
        "DiffDelete": {"bg": mix(s.bg, s.error, 0.18)},
        "DiffText": {"bg": mix(s.bg, s.warning, 0.3), "bold": True},
        # --- Diagnosen ---
        "DiagnosticError": _fg(s.error),
        "DiagnosticWarn": _fg(s.warning),
        "DiagnosticInfo": _fg(s.info),
        "DiagnosticHint": _fg(s.hint),
        "DiagnosticOk": _fg(s.success),
        "DiagnosticUnderlineError": {"sp": s.error, "undercurl": True},
        "DiagnosticUnderlineWarn": {"sp": s.warning, "undercurl": True},
        "DiagnosticUnderlineInfo": {"sp": s.info, "undercurl": True},
        "DiagnosticUnderlineHint": {"sp": s.hint, "undercurl": True},
        "DiagnosticUnderlineOk": {"sp": s.success, "undercurl": True},
        "DiagnosticVirtualTextError": {"fg": s.error, "bg": mix(s.bg, s.error, 0.12)},
        "DiagnosticVirtualTextWarn": {"fg": s.warning, "bg": mix(s.bg, s.warning, 0.12)},
        "DiagnosticVirtualTextInfo": {"fg": s.info, "bg": mix(s.bg, s.info, 0.12)},
        "DiagnosticVirtualTextHint": {"fg": s.hint, "bg": mix(s.bg, s.hint, 0.12)},
        # --- Treesitter ---
        "@variable": _fg(s.fg),
        "@variable.builtin": _fg(s.special, italic=True),
        "@variable.parameter": _fg(s.fg),
        "@variable.member": _fg(s.fg),
        "@constant": _fg(s.number),
        "@constant.builtin": _fg(s.special),
        "@constant.macro": _fg(s.special),
        "@module": _fg(s.type_),
        "@label": _fg(s.keyword),
        "@string": _fg(s.string),
        "@string.documentation": _fg(s.comment),
        "@string.escape": _fg(s.special),
        "@string.regexp": _fg(s.special),
        "@string.special": _fg(s.special),
        "@character": _fg(s.string),
        "@character.special": _fg(s.special),
        "@boolean": _fg(s.number),
        "@number": _fg(s.number),
        "@number.float": _fg(s.number),
        "@type": _fg(s.type_),
        "@type.builtin": _fg(s.type_, italic=True),
        "@type.definition": _fg(s.type_),
        "@attribute": _fg(s.special),
        "@attribute.builtin": _fg(s.special),
        "@property": _fg(s.fg),
        "@function": _fg(s.function),
        "@function.builtin": _fg(s.special),
        "@function.macro": _fg(s.special),
        "@function.method": _fg(s.function),
        "@constructor": _fg(s.type_),
        "@operator": _fg(s.operator),
        "@keyword": _fg(s.keyword),
        "@keyword.function": _fg(s.keyword),
        "@keyword.operator": _fg(s.keyword),
        "@keyword.import": _fg(s.keyword),
        "@keyword.return": _fg(s.keyword),
        "@keyword.exception": _fg(s.keyword),
        "@punctuation.delimiter": _fg(s.operator),
        "@punctuation.bracket": _fg(s.operator),
        "@punctuation.special": _fg(s.special),
        "@comment": _fg(s.comment, italic=True),
        "@comment.documentation": _fg(s.comment, italic=True),
        "@comment.error": {"fg": s.bg, "bg": s.error, "bold": True},
        "@comment.warning": {"fg": s.bg, "bg": s.warning, "bold": True},
        "@comment.todo": {"link": "Todo"},
        "@comment.note": {"fg": s.bg, "bg": s.info, "bold": True},
        "@tag": _fg(s.keyword),
        "@tag.builtin": _fg(s.keyword),
        "@tag.attribute": _fg(s.function, italic=True),
        "@tag.delimiter": _fg(s.operator),
        "@markup.strong": {"fg": s.fg, "bold": True},
        "@markup.italic": {"fg": s.fg, "italic": True},
        "@markup.strikethrough": {"fg": s.fg_dim, "strikethrough": True},
        "@markup.underline": {"fg": s.fg, "underline": True},
        "@markup.quote": _fg(s.fg_dim, italic=True),
        "@markup.math": _fg(s.number),
        "@markup.link": _fg(s.function),
        "@markup.link.label": _fg(s.accent),
        "@markup.link.url": _fg(s.function, underline=True),
        "@markup.raw": _fg(s.string),
        "@markup.list": _fg(s.accent),
        "@markup.list.checked": _fg(s.success),
        "@markup.list.unchecked": _fg(s.fg_dim),
        "@diff.plus": _fg(s.success),
        "@diff.minus": _fg(s.error),
        "@diff.delta": _fg(s.warning),
        # --- LSP-Semantik, wo sie ueber Treesitter hinausgeht ---
        "@lsp.type.namespace": {"link": "@module"},
        "@lsp.type.class": {"link": "@type"},
        "@lsp.type.enum": {"link": "@type"},
        "@lsp.type.interface": {"link": "@type"},
        "@lsp.type.struct": {"link": "@type"},
        "@lsp.type.parameter": {"link": "@variable.parameter"},
        "@lsp.type.property": {"link": "@property"},
        "@lsp.type.enumMember": {"link": "@constant"},
        "@lsp.type.method": {"link": "@function.method"},
        # --- mini.nvim ---
        "MiniIconsAzure": _fg(s.function),
        "MiniIconsBlue": _fg(s.info),
        "MiniIconsCyan": _fg(s.type_),
        "MiniIconsGreen": _fg(s.success),
        "MiniIconsGrey": _fg(s.fg_dim),
        "MiniIconsOrange": _fg(s.number),
        "MiniIconsPurple": _fg(s.special),
        "MiniIconsRed": _fg(s.error),
        "MiniIconsYellow": _fg(s.warning),
        "MiniFilesTitleFocused": {"fg": s.accent, "bg": s.bg_float, "bold": True},
        "MiniFilesDirectory": _fg(s.function),
        "MiniFilesFile": _fg(s.fg),
        "MiniFilesCursorLine": {"bg": s.bg_elevated},
        "MiniPickMatchCurrent": {"bg": s.bg_elevated, "bold": True},
        "MiniPickMatchRanges": _fg(s.accent, bold=True),
        "MiniPickPrompt": _fg(s.accent, bold=True),
        "MiniPickBorderText": _fg(s.accent),
        "MiniClueDescGroup": _fg(s.type_),
        "MiniClueDescSingle": _fg(s.fg),
        "MiniClueNextKey": _fg(s.accent, bold=True),
        "MiniClueTitle": {"fg": s.accent, "bg": s.bg_float, "bold": True},
        # --- render-markdown.nvim ---
        "RenderMarkdownCode": {"bg": s.bg_float},
        "RenderMarkdownCodeInline": {"fg": s.string, "bg": s.bg_float},
        "RenderMarkdownBullet": _fg(s.accent),
        "RenderMarkdownQuote": _fg(s.fg_dim),
        "RenderMarkdownDash": _fg(s.border),
        "RenderMarkdownTableHead": _fg(s.type_, bold=True),
        "RenderMarkdownTableRow": _fg(s.fg_dim),
        "RenderMarkdownLink": _fg(s.function),
        "RenderMarkdownChecked": _fg(s.success),
        "RenderMarkdownUnchecked": _fg(s.fg_dim),
    }

    for level, color in enumerate(heading, start=1):
        groups[f"@markup.heading.{level}"] = {"fg": color, "bold": True}
        groups[f"RenderMarkdownH{level}"] = {"fg": color, "bold": True}
        groups[f"RenderMarkdownH{level}Bg"] = {"fg": color, "bg": mix(s.bg, color, 0.15), "bold": True}

    return groups
